<?php

declare(strict_types=1);

require dirname(__DIR__, 2) . '/scripts/bootstrap.php';

use App\Core\Database;
use PDO;

$registryPath=__DIR__.'/historical_products_registry.json';foreach($argv as $arg){if(!str_starts_with($arg,'--registry='))continue;$value=trim(substr($arg,11));if($value===''||str_contains($value,"\0")){fwrite(STDERR,"Valore --registry non valido.\n");exit(1);} $candidate=str_starts_with($value,DIRECTORY_SEPARATOR)?$value:__DIR__.DIRECTORY_SEPARATOR.ltrim($value,'/\\');$real=realpath($candidate);if($real===false||!is_file($real)){fwrite(STDERR,"Registry non trovato: {$value}\n");exit(1);} if(!str_starts_with($value,DIRECTORY_SEPARATOR)){$root=realpath(__DIR__);if($root===false||!str_starts_with($real,$root.DIRECTORY_SEPARATOR)){fwrite(STDERR,"Registry relativo fuori dalla cartella import non consentito.\n");exit(1);}}$registryPath=$real;}
$raw=file_get_contents($registryPath);if($raw===false)throw new RuntimeException('Registry non leggibile.');$data=json_decode($raw,true,flags:JSON_THROW_ON_ERROR);$pdo=Database::connection();
$stats=['registry_categories'=>0,'registry_products'=>0,'registry_models'=>0,'secondary_links'=>0,'existing_categories'=>0,'existing_products_same_slug'=>0,'existing_models_same_product'=>0,'missing_parent_categories'=>0,'missing_secondary_categories'=>0,'product_slug_conflicts'=>0,'model_conflicts'=>0];$issues=[];$categorySlugsInRegistry=[];
$collect=function(array $category)use(&$collect,&$categorySlugsInRegistry,&$stats):void{$slug=trim((string)($category['slug']??''));if($slug!=='')$categorySlugsInRegistry[$slug]=true;$stats['registry_categories']++;foreach($category['children']??[] as $child)$collect($child);};foreach($data['categories']??[] as $category)$collect($category);
$findCategory=$pdo->prepare('SELECT id,parent_id,name,slug FROM product_categories WHERE slug=? LIMIT 1');
$findProduct=$pdo->prepare('SELECT p.id,p.category_id,p.name,c.slug category_slug FROM products p JOIN product_categories c ON c.id=p.category_id WHERE p.slug=? LIMIT 1');
$findModelGlobal=$pdo->prepare('SELECT pm.id,pm.product_id,p.slug product_slug,p.name product_name FROM product_models pm JOIN products p ON p.id=pm.product_id WHERE LOWER(pm.code)=LOWER(?) LIMIT 1');$findModelScoped=$pdo->prepare('SELECT id FROM product_models WHERE product_id=? AND LOWER(code)=LOWER(?) LIMIT 1');
$walk=function(array $category)use(&$walk,$pdo,&$stats,&$issues,$categorySlugsInRegistry,$findCategory,$findProduct,$findModelGlobal,$findModelScoped):void{$categorySlug=trim((string)($category['slug']??''));$parentSlug=trim((string)($category['parent_slug']??''));if($parentSlug!==''&&!isset($categorySlugsInRegistry[$parentSlug])){$findCategory->execute([$parentSlug]);if(!$findCategory->fetch(PDO::FETCH_ASSOC)){$stats['missing_parent_categories']++;$issues[]=['type'=>'missing_parent_category','category'=>$categorySlug,'parent'=>$parentSlug];}}$findCategory->execute([$categorySlug]);if($findCategory->fetch(PDO::FETCH_ASSOC))$stats['existing_categories']++;
foreach($category['products']??[] as $product){$stats['registry_products']++;$productSlug=trim((string)($product['slug']??''));$secondary=array_values(array_unique(array_filter(array_map('trim',$product['also_category_slugs']??[]))));$findProduct->execute([$productSlug]);$existingProduct=$findProduct->fetch(PDO::FETCH_ASSOC);$existingProductId=$existingProduct?(int)$existingProduct['id']:null;if($existingProduct){$stats['existing_products_same_slug']++;$allowedCategories=array_merge([$categorySlug],$secondary);if(!in_array((string)$existingProduct['category_slug'],$allowedCategories,true)){$stats['product_slug_conflicts']++;$issues[]=['type'=>'product_slug_conflict','product'=>$productSlug,'registry_primary_category'=>$categorySlug,'registry_secondary_categories'=>$secondary,'database_primary_category'=>(string)$existingProduct['category_slug'],'database_product_name'=>(string)$existingProduct['name']];}}
foreach($secondary as $secondarySlug){if($secondarySlug==='')continue;$stats['secondary_links']++;if(!isset($categorySlugsInRegistry[$secondarySlug])){$findCategory->execute([$secondarySlug]);if(!$findCategory->fetch(PDO::FETCH_ASSOC)){$stats['missing_secondary_categories']++;$issues[]=['type'=>'missing_secondary_category','product'=>$productSlug,'category'=>$secondarySlug];}}}
foreach($product['models']??[] as $codeRaw){$code=trim((string)$codeRaw);if($code==='')continue;$stats['registry_models']++;$findModelGlobal->execute([$code]);$global=$findModelGlobal->fetch(PDO::FETCH_ASSOC);if(!$global)continue;if($existingProductId!==null&&(int)$global['product_id']===$existingProductId){$findModelScoped->execute([$existingProductId,$code]);if($findModelScoped->fetchColumn()!==false)$stats['existing_models_same_product']++;continue;}$stats['model_conflicts']++;$issues[]=['type'=>'model_conflict','model'=>$code,'registry_product'=>$productSlug,'database_product'=>(string)$global['product_slug'],'database_product_name'=>(string)$global['product_name']];}}
foreach($category['children']??[] as $child)$walk($child);};foreach($data['categories']??[] as $category)$walk($category);
$ok=$stats['missing_parent_categories']===0&&$stats['missing_secondary_categories']===0&&$stats['product_slug_conflicts']===0&&$stats['model_conflicts']===0;$report=['ok'=>$ok,'mode'=>'preflight-read-only','registry'=>basename($registryPath),'stats'=>$stats,'issues'=>$issues];$stem=preg_replace('/[^a-z0-9._-]+/i','-',pathinfo($registryPath,PATHINFO_FILENAME))?:'registry';$reportPath=__DIR__.'/reports/preflight-'.$stem.'-latest.json';file_put_contents($reportPath,json_encode($report,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE));echo "PREFLIGHT historical products (sola lettura)\n";echo 'registry                 : '.basename($registryPath)."\n";foreach($stats as $key=>$value)echo str_pad($key,25).': '.$value."\n";echo 'Report                   : '.$reportPath."\n";if(!$ok){fwrite(STDERR,"Preflight FALLITO: risolvere i conflitti prima di --execute.\n");exit(2);}echo "Preflight OK: nessuna scrittura DB eseguita.\n";
