<?php

declare(strict_types=1);

namespace App\Controllers\Admin;

use App\Auth\AdminAuth;
use App\Core\Database;
use App\Core\Security;
use App\Core\Upload;
use App\Core\Validator;
use PDO;

final class ContentController
{
    public static function catalogs(): void { AdminAuth::requireLogin(); $rows=Database::connection()->query('SELECT * FROM catalogs ORDER BY sort_order,title')->fetchAll(PDO::FETCH_ASSOC); self::view('content_catalogs',['title'=>'Cataloghi','rows'=>$rows]); }
    public static function catalogForm(): void { AdminAuth::requireLogin(); $id=Validator::int($_GET['id']??0); $row=['id'=>0,'title'=>'','slug'=>'','description'=>'','cover_image'=>'','pdf_path'=>'','document_year'=>'','published'=>1,'sort_order'=>0]; if($id){$s=Database::connection()->prepare('SELECT * FROM catalogs WHERE id=?');$s->execute([$id]);$row=$s->fetch(PDO::FETCH_ASSOC)?:$row;} self::view('content_catalog_form',['title'=>'Catalogo','row'=>$row,'errors'=>[]]); }
    public static function saveCatalog(): void { AdminAuth::requireLogin(); self::csrf(); $errors=[];$id=Validator::int($_POST['id']??0);$title=Validator::requiredString($_POST['title']??'','Titolo',220,$errors);$slug=trim((string)($_POST['slug']??''))?:self::slugify($title);$description=trim((string)($_POST['description']??''));$year=Validator::int($_POST['document_year']??0)?:null;$published=Validator::bool($_POST['published']??0);$sort=Validator::int($_POST['sort_order']??0);$pdo=Database::connection();$existing=['cover_image'=>'','pdf_path'=>''];if($id){$s=$pdo->prepare('SELECT cover_image,pdf_path FROM catalogs WHERE id=?');$s->execute([$id]);$existing=$s->fetch(PDO::FETCH_ASSOC)?:$existing;}$cover=Upload::contentImage('cover_image','catalogs',$errors);$pdf=Upload::contentPdf('pdf_file','catalogs',$errors);$coverPath=$cover['path']??$existing['cover_image'];$pdfPath=$pdf['path']??$existing['pdf_path'];if($pdfPath==='')$errors[]='Carica il PDF del catalogo.';$row=['id'=>$id,'title'=>$title,'slug'=>$slug,'description'=>$description,'cover_image'=>$coverPath,'pdf_path'=>$pdfPath,'document_year'=>$year,'published'=>$published,'sort_order'=>$sort];if($errors){if($cover)Upload::removeManaged($cover['path']);if($pdf)Upload::removeManaged($pdf['path']);self::view('content_catalog_form',['title'=>'Catalogo','row'=>$row,'errors'=>$errors]);return;}if($id){$s=$pdo->prepare('UPDATE catalogs SET title=?,slug=?,description=?,cover_image=?,pdf_path=?,document_year=?,published=?,sort_order=? WHERE id=?');$s->execute([$title,$slug,$description?:null,$coverPath?:null,$pdfPath,$year,$published,$sort,$id]);}else{$s=$pdo->prepare('INSERT INTO catalogs(title,slug,description,cover_image,pdf_path,document_year,published,sort_order) VALUES(?,?,?,?,?,?,?,?)');$s->execute([$title,$slug,$description?:null,$coverPath?:null,$pdfPath,$year,$published,$sort]);}header('Location:/admin/content/catalogs');exit; }

    public static function albums(): void { AdminAuth::requireLogin(); $rows=Database::connection()->query('SELECT a.*,COUNT(i.id) image_count FROM gallery_albums a LEFT JOIN gallery_images i ON i.album_id=a.id GROUP BY a.id ORDER BY a.sort_order,a.title')->fetchAll(PDO::FETCH_ASSOC); self::view('content_albums',['title'=>'Galleria','rows'=>$rows]); }
    public static function albumForm(): void { AdminAuth::requireLogin(); $id=Validator::int($_GET['id']??0);$pdo=Database::connection();$row=['id'=>0,'title'=>'','slug'=>'','description'=>'','cover_image'=>'','published'=>1,'sort_order'=>0];$images=[];if($id){$s=$pdo->prepare('SELECT * FROM gallery_albums WHERE id=?');$s->execute([$id]);$row=$s->fetch(PDO::FETCH_ASSOC)?:$row;$s=$pdo->prepare('SELECT * FROM gallery_images WHERE album_id=? ORDER BY sort_order,id');$s->execute([$id]);$images=$s->fetchAll(PDO::FETCH_ASSOC);} self::view('content_album_form',['title'=>'Album','row'=>$row,'images'=>$images,'errors'=>[]]); }
    public static function saveAlbum(): void { AdminAuth::requireLogin(); self::csrf();$errors=[];$id=Validator::int($_POST['id']??0);$title=Validator::requiredString($_POST['title']??'','Titolo',220,$errors);$slug=trim((string)($_POST['slug']??''))?:self::slugify($title);$desc=trim((string)($_POST['description']??''));$published=Validator::bool($_POST['published']??0);$sort=Validator::int($_POST['sort_order']??0);$pdo=Database::connection();$existing='';if($id){$s=$pdo->prepare('SELECT cover_image FROM gallery_albums WHERE id=?');$s->execute([$id]);$existing=(string)($s->fetchColumn()?:'');}$cover=Upload::contentImage('cover_image','gallery',$errors);$coverPath=$cover['path']??$existing;$row=['id'=>$id,'title'=>$title,'slug'=>$slug,'description'=>$desc,'cover_image'=>$coverPath,'published'=>$published,'sort_order'=>$sort];if($errors){if($cover)Upload::removeManaged($cover['path']);self::view('content_album_form',['title'=>'Album','row'=>$row,'images'=>[],'errors'=>$errors]);return;}if($id){$pdo->prepare('UPDATE gallery_albums SET title=?,slug=?,description=?,cover_image=?,published=?,sort_order=? WHERE id=?')->execute([$title,$slug,$desc?:null,$coverPath?:null,$published,$sort,$id]);}else{$pdo->prepare('INSERT INTO gallery_albums(title,slug,description,cover_image,published,sort_order) VALUES(?,?,?,?,?,?)')->execute([$title,$slug,$desc?:null,$coverPath?:null,$published,$sort]);$id=(int)$pdo->lastInsertId();}header('Location:/admin/content/gallery/form?id='.$id);exit; }
    public static function addGalleryImage(): void { AdminAuth::requireLogin();self::csrf();$errors=[];$albumId=Validator::int($_POST['album_id']??0);$upload=Upload::contentImage('image_file','gallery',$errors);if(!$upload||$albumId<1){header('Location:/admin/content/gallery/form?id='.$albumId);exit;}Database::connection()->prepare('INSERT INTO gallery_images(album_id,image_path,alt_text,caption,published,sort_order) VALUES(?,?,?,?,?,?)')->execute([$albumId,$upload['path'],trim((string)($_POST['alt_text']??''))?:null,trim((string)($_POST['caption']??''))?:null,Validator::bool($_POST['published']??1),Validator::int($_POST['sort_order']??0)]);header('Location:/admin/content/gallery/form?id='.$albumId);exit; }

    public static function references(): void { AdminAuth::requireLogin();$rows=Database::connection()->query('SELECT r.*,COUNT(i.id) image_count FROM references_projects r LEFT JOIN reference_images i ON i.reference_id=r.id GROUP BY r.id ORDER BY r.sort_order,r.title')->fetchAll(PDO::FETCH_ASSOC);self::view('content_references',['title'=>'Referenze','rows'=>$rows]); }
    public static function referenceForm(): void { AdminAuth::requireLogin();$id=Validator::int($_GET['id']??0);$pdo=Database::connection();$row=['id'=>0,'title'=>'','slug'=>'','location'=>'','project_year'=>'','short_description'=>'','description'=>'','cover_image'=>'','published'=>1,'sort_order'=>0];$images=[];if($id){$s=$pdo->prepare('SELECT * FROM references_projects WHERE id=?');$s->execute([$id]);$row=$s->fetch(PDO::FETCH_ASSOC)?:$row;$s=$pdo->prepare('SELECT * FROM reference_images WHERE reference_id=? ORDER BY sort_order,id');$s->execute([$id]);$images=$s->fetchAll(PDO::FETCH_ASSOC);}self::view('content_reference_form',['title'=>'Referenza','row'=>$row,'images'=>$images,'errors'=>[]]); }
    public static function saveReference(): void { AdminAuth::requireLogin();self::csrf();$errors=[];$id=Validator::int($_POST['id']??0);$title=Validator::requiredString($_POST['title']??'','Titolo',220,$errors);$slug=trim((string)($_POST['slug']??''))?:self::slugify($title);$location=trim((string)($_POST['location']??''));$year=Validator::int($_POST['project_year']??0)?:null;$short=trim((string)($_POST['short_description']??''));$desc=trim((string)($_POST['description']??''));$published=Validator::bool($_POST['published']??0);$sort=Validator::int($_POST['sort_order']??0);$pdo=Database::connection();$existing='';if($id){$s=$pdo->prepare('SELECT cover_image FROM references_projects WHERE id=?');$s->execute([$id]);$existing=(string)($s->fetchColumn()?:'');}$cover=Upload::contentImage('cover_image','references',$errors);$coverPath=$cover['path']??$existing;$row=['id'=>$id,'title'=>$title,'slug'=>$slug,'location'=>$location,'project_year'=>$year,'short_description'=>$short,'description'=>$desc,'cover_image'=>$coverPath,'published'=>$published,'sort_order'=>$sort];if($errors){if($cover)Upload::removeManaged($cover['path']);self::view('content_reference_form',['title'=>'Referenza','row'=>$row,'images'=>[],'errors'=>$errors]);return;}if($id){$pdo->prepare('UPDATE references_projects SET title=?,slug=?,location=?,project_year=?,short_description=?,description=?,cover_image=?,published=?,sort_order=? WHERE id=?')->execute([$title,$slug,$location?:null,$year,$short?:null,$desc?:null,$coverPath?:null,$published,$sort,$id]);}else{$pdo->prepare('INSERT INTO references_projects(title,slug,location,project_year,short_description,description,cover_image,published,sort_order) VALUES(?,?,?,?,?,?,?,?,?)')->execute([$title,$slug,$location?:null,$year,$short?:null,$desc?:null,$coverPath?:null,$published,$sort]);$id=(int)$pdo->lastInsertId();}header('Location:/admin/content/references/form?id='.$id);exit; }
    public static function addReferenceImage(): void { AdminAuth::requireLogin();self::csrf();$errors=[];$referenceId=Validator::int($_POST['reference_id']??0);$upload=Upload::contentImage('image_file','references',$errors);if(!$upload||$referenceId<1){header('Location:/admin/content/references/form?id='.$referenceId);exit;}Database::connection()->prepare('INSERT INTO reference_images(reference_id,image_path,alt_text,caption,published,sort_order) VALUES(?,?,?,?,?,?)')->execute([$referenceId,$upload['path'],trim((string)($_POST['alt_text']??''))?:null,trim((string)($_POST['caption']??''))?:null,Validator::bool($_POST['published']??1),Validator::int($_POST['sort_order']??0)]);header('Location:/admin/content/references/form?id='.$referenceId);exit; }

    private static function view(string $file,array $data):void{extract($data,EXTR_SKIP);$user=AdminAuth::user();$csrf=Security::csrfToken();require dirname(__DIR__,2).'/Views/admin/'.$file.'.php';}
    private static function csrf():void{if(!Security::verifyCsrf($_POST['_csrf']??null)){http_response_code(419);exit('Sessione non valida');}}
    private static function slugify(string $v):string{$a=iconv('UTF-8','ASCII//TRANSLIT//IGNORE',strtolower(trim($v)))?:$v;return trim((string)preg_replace('/[^a-z0-9]+/','-',$a),'-');}
}
