<?php require __DIR__.'/_layout_start.php'; ?>
<style>
.account-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(280px,.65fr);gap:20px}.account-summary dl{display:grid;grid-template-columns:130px minmax(0,1fr);gap:10px 16px;margin:0}.account-summary dt{color:var(--muted);font-weight:700}.account-summary dd{margin:0}.password-stack{display:grid;gap:16px;max-width:620px}.password-field{position:relative;margin-top:5px}.password-field input{margin:0;padding-right:52px}.password-toggle{position:absolute;top:50%;right:5px;display:grid;width:40px;height:40px;padding:0;place-items:center;transform:translateY(-50%);border:0;border-radius:8px;background:transparent;color:inherit;cursor:pointer}.password-toggle:hover{background:rgba(15,72,94,.08)}.password-toggle:focus-visible{outline:2px solid var(--blue);outline-offset:1px}.password-toggle svg{width:21px;height:21px;fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:2}.password-toggle .eye-off{display:none}.password-toggle[aria-pressed="true"] .eye-on{display:none}.password-toggle[aria-pressed="true"] .eye-off{display:block}.success{background:#f3faed;color:#285c20;border:1px solid #9acb70;padding:12px;border-radius:9px;margin-bottom:16px}@media(max-width:760px){.account-grid{grid-template-columns:1fr}.account-summary dl{grid-template-columns:1fr;gap:2px}.account-summary dd{margin-bottom:10px}}
</style>
<div class="toolbar"><div><h1>Il mio account</h1><p class="page-lead">Dati di accesso e modifica della password personale.</p></div></div>
<?php if($saved):?><div class="success" role="status">Password modificata correttamente.</div><?php endif;?>
<?php if($error!==''):?><div class="error" role="alert"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></div><?php endif;?>
<div class="account-grid">
<section class="panel account-summary"><h2>Dati account</h2><dl><dt>Nome</dt><dd><?=htmlspecialchars(trim(($user['first_name']??'').' '.($user['last_name']??'')),ENT_QUOTES,'UTF-8')?></dd><dt>Email</dt><dd><?=htmlspecialchars((string)($user['email']??''),ENT_QUOTES,'UTF-8')?></dd><dt>Username</dt><dd><?=htmlspecialchars((string)($user['username']??''),ENT_QUOTES,'UTF-8')?></dd></dl></section>
<section class="panel"><h2>Modifica password</h2><p class="muted">La nuova password deve contenere almeno 12 caratteri.</p><form method="post" action="/idemaclima/admin/account/password"><input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><div class="password-stack">
<?php foreach(['current_password'=>'Password attuale','new_password'=>'Nuova password','new_password_confirmation'=>'Conferma nuova password'] as $field=>$label):?><label for="<?=$field?>"><?=$label?></label><div class="password-field"><input id="<?=$field?>" type="password" name="<?=$field?>" required minlength="<?=$field==='current_password'?'1':'12'?>" autocomplete="<?=$field==='current_password'?'current-password':'new-password'?>"><button class="password-toggle" type="button" aria-label="Mostra <?=$label?>" aria-controls="<?=$field?>" aria-pressed="false"><svg class="eye-on" viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></svg><svg class="eye-off" viewBox="0 0 24 24" aria-hidden="true"><path d="m3 3 18 18"/><path d="M10.6 5.2A10.8 10.8 0 0 1 12 5c6.5 0 10 7 10 7a17.8 17.8 0 0 1-2.1 3.1M6.2 6.2C3.5 8.1 2 12 2 12s3.5 7 10 7a9.8 9.8 0 0 0 4.1-.9"/><path d="M9.9 9.9a3 3 0 0 0 4.2 4.2"/></svg></button></div><?php endforeach;?>
<button class="btn" type="submit">Aggiorna password</button></div></form></section>
</div>
<script nonce="<?=htmlspecialchars(\App\Core\Security::nonce(),ENT_QUOTES,'UTF-8')?>">(()=>{document.querySelectorAll('.password-toggle').forEach(button=>{const input=document.getElementById(button.getAttribute('aria-controls'));if(!input)return;button.addEventListener('click',()=>{const show=input.type==='password';input.type=show?'text':'password';button.setAttribute('aria-pressed',show?'true':'false');button.setAttribute('aria-label',(show?'Nascondi ':'Mostra ')+(input.previousElementSibling?.textContent||'password'));input.focus()})})})();</script>
<?php require __DIR__.'/_layout_end.php'; ?>
