<?php require __DIR__.'/_layout_start.php';$on=static fn($key)=>!empty($settings[$key]);$cmpReady=$on('iubenda_enabled')&&!empty($settings['iubenda_site_id'])&&!empty($settings['iubenda_cookie_policy_id']);$trackingReady=$on('analytics_enabled')&&(!$on('consent_required')||$cmpReady); ?>
<div class="toolbar"><div><h1>Analytics e integrazioni</h1><p class="muted">Identificativi controllati, senza campi per script arbitrari.</p></div></div>
<div class="cards" style="margin-bottom:22px"><div class="card"><span class="muted">Google Analytics</span><strong style="font-size:17px"><?= $trackingReady&&!empty($settings['ga4_measurement_id'])?'Attivo':(!empty($settings['ga4_measurement_id'])?'Configurato, non attivo':'Non configurato') ?></strong></div><div class="card"><span class="muted">Google Tag Manager</span><strong style="font-size:17px"><?= $trackingReady&&!empty($settings['gtm_container_id'])?'Attivo':(!empty($settings['gtm_container_id'])?'Configurato, non attivo':'Non configurato') ?></strong></div><div class="card"><span class="muted">Search Console</span><strong style="font-size:17px"><?= !empty($settings['search_console_verification'])?'Verificato':'Non configurato' ?></strong></div><div class="card"><span class="muted">Meta Pixel</span><strong style="font-size:17px"><?= $trackingReady&&!empty($settings['meta_pixel_id'])?'Attivo':(!empty($settings['meta_pixel_id'])?'Configurato, non attivo':'Non configurato') ?></strong></div><div class="card"><span class="muted">iubenda CMP</span><strong style="font-size:17px"><?= $cmpReady?'Attiva':'Non configurata' ?></strong></div></div>
<form method="post" action="/idemaclima/admin/analytics/save"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>">
<section class="panel" style="margin-bottom:18px"><h2>Google</h2><div class="formgrid"><label>GA4 Measurement ID<input name="ga4_measurement_id" placeholder="G-XXXXXXXXXX" value="<?= htmlspecialchars((string)($settings['ga4_measurement_id']??''),ENT_QUOTES,'UTF-8') ?>"></label><label>GA4 Property ID<input name="ga4_property_id" inputmode="numeric" value="<?= htmlspecialchars((string)($settings['ga4_property_id']??''),ENT_QUOTES,'UTF-8') ?>"></label><label>Google Tag Manager<input name="gtm_container_id" placeholder="GTM-XXXXXXX" value="<?= htmlspecialchars((string)($settings['gtm_container_id']??''),ENT_QUOTES,'UTF-8') ?>"></label><label>Verifica Search Console<input name="search_console_verification" autocomplete="off" value="<?= htmlspecialchars((string)($settings['search_console_verification']??''),ENT_QUOTES,'UTF-8') ?>"><small>Inserire solo il contenuto del meta tag, non HTML.</small></label><label class="check full"><input type="checkbox" name="analytics_enabled" value="1" <?= $on('analytics_enabled')?'checked':'' ?>> Attiva i servizi di analytics configurati</label><label class="check full"><input type="checkbox" name="consent_required" value="1" <?= !isset($settings['consent_required'])||$on('consent_required')?'checked':'' ?>> Blocca il tracking fino al consenso iubenda</label></div></section>
<section class="panel" style="margin-bottom:18px"><h2>iubenda</h2><p class="muted">La policy ufficiale resta la n. 38092343. Il banner mostra Accetta, Rifiuta e Personalizza e gestisce la revoca dal footer.</p><div class="formgrid"><label>Site ID<input name="iubenda_site_id" inputmode="numeric" value="<?= htmlspecialchars((string)($settings['iubenda_site_id']??''),ENT_QUOTES,'UTF-8') ?>"></label><label>Cookie Policy ID<input name="iubenda_cookie_policy_id" inputmode="numeric" value="<?= htmlspecialchars((string)($settings['iubenda_cookie_policy_id']??'38092343'),ENT_QUOTES,'UTF-8') ?>"></label><label class="check full"><input type="checkbox" name="iubenda_enabled" value="1" <?= $on('iubenda_enabled')?'checked':'' ?>> Attiva iubenda CMP</label></div></section>
<section class="panel" style="margin-bottom:18px"><h2>Altre integrazioni</h2><div class="formgrid"><label>Meta Pixel ID<input name="meta_pixel_id" inputmode="numeric" value="<?= htmlspecialchars((string)($settings['meta_pixel_id']??''),ENT_QUOTES,'UTF-8') ?>"><small>Il Pixel resta bloccato fino al consenso.</small></label></div></section>
<section class="panel"><h2>Statistiche interne</h2><div class="formgrid"><label class="check"><input type="checkbox" name="pdf_tracking_enabled" value="1" <?= !isset($settings['pdf_tracking_enabled'])||$on('pdf_tracking_enabled')?'checked':'' ?>> Traccia download PDF internamente</label><label>Conservazione (giorni)<input type="number" name="internal_tracking_retention_days" min="1" max="3650" value="<?= (int)($settings['internal_tracking_retention_days']??180) ?>"></label></div></section>
<p><button class="btn" type="submit">Salva integrazioni</button></p></form>
<h2>PDF più scaricati</h2><div class="table-wrap"><table><thead><tr><th>Documento</th><th>Download</th></tr></thead><tbody><?php foreach($top as $r): ?><tr><td><?= htmlspecialchars($r['title'],ENT_QUOTES,'UTF-8') ?></td><td><?= (int)$r['downloads'] ?></td></tr><?php endforeach; ?></tbody></table></div><?php require __DIR__.'/_layout_end.php'; ?>
