<?php $title=((int)$resource['id']?'Modifica':'Nuova').' risorsa Assistenza'; require __DIR__.'/_layout_start.php'; ?>
<h1><?= htmlspecialchars($title,ENT_QUOTES,'UTF-8') ?></h1><p class="muted">Carica direttamente il PDF oppure indica un URL esterno. Per sostituire un PDF già collegato basta selezionare il nuovo file.</p>
<?php foreach($errors as $error): ?><div class="error"><?= htmlspecialchars($error,ENT_QUOTES,'UTF-8') ?></div><?php endforeach; ?>
<form class="panel formgrid" method="post" action="/idemaclima/admin/assistance/save" enctype="multipart/form-data"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="id" value="<?= (int)$resource['id'] ?>">
<label>Sezione<select name="section" required><option value="warranty" <?= $resource['section']==='warranty'?'selected':'' ?>>Termini e condizioni</option><option value="error_code" <?= $resource['section']==='error_code'?'selected':'' ?>>Codici di errore</option></select></label>
<label>Etichetta<input name="label" required maxlength="220" value="<?= htmlspecialchars((string)$resource['label'],ENT_QUOTES,'UTF-8') ?>"></label>
<label class="full">Nuovo file PDF<input type="file" name="document_file" accept="application/pdf"><small>Solo PDF, massimo 25 MB. Se la risorsa ha già un documento, il file viene sostituito mantenendo il collegamento.</small></label>
<div class="full"><details><summary>Opzione avanzata: riutilizza un PDF dell’archivio</summary><label>Documento già presente<select name="document_id"><option value="">Nessuno / crea dal PDF caricato</option><?php foreach($documents as $document): ?><option value="<?= (int)$document['id'] ?>" <?= (int)($resource['document_id']??0)===(int)$document['id']?'selected':'' ?>><?= htmlspecialchars($document['title'],ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select><small>Lascia vuoto per caricare un nuovo PDF.</small></label></details></div>
<label class="full">Oppure URL esterno<input type="url" name="external_url" maxlength="2048" value="<?= htmlspecialchars((string)($resource['external_url']??''),ENT_QUOTES,'UTF-8') ?>"></label>
<label>Ordine<input type="number" name="sort_order" value="<?= (int)$resource['sort_order'] ?>"></label><label class="check"><input type="checkbox" name="published" value="1" <?= $resource['published']?'checked':'' ?>> Pubblicato</label>
<div class="full"><button class="btn" type="submit">Salva risorsa</button> <a href="/idemaclima/admin/assistance">Annulla</a></div></form>
<?php require __DIR__.'/_layout_end.php'; ?>
