<?php require __DIR__.'/_layout_start.php'; ?>
<div class="toolbar"><div><h1><?= (int)$row['id']?'Modifica referenza':'Nuova referenza' ?></h1></div><a href="/idemaclima/admin/content/references">Torna alle referenze</a></div>
<?php foreach($errors as $er): ?><div class="error"><?= htmlspecialchars($er,ENT_QUOTES,'UTF-8') ?></div><?php endforeach; ?>
<form method="post" enctype="multipart/form-data" action="/idemaclima/admin/content/references/save" class="panel"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><div class="formgrid"><label>Titolo<input name="title" maxlength="220" value="<?= htmlspecialchars((string)$row['title'],ENT_QUOTES,'UTF-8') ?>" required></label><label>Slug<input name="slug" maxlength="240" value="<?= htmlspecialchars((string)$row['slug'],ENT_QUOTES,'UTF-8') ?>"></label><label>Località<input name="location" maxlength="190" value="<?= htmlspecialchars((string)$row['location'],ENT_QUOTES,'UTF-8') ?>"></label><label>Anno<input type="number" min="1900" max="2100" name="project_year" value="<?= htmlspecialchars((string)$row['project_year'],ENT_QUOTES,'UTF-8') ?>"></label><label class="full">Descrizione breve<textarea name="short_description" rows="3" maxlength="3000"><?= htmlspecialchars((string)$row['short_description'],ENT_QUOTES,'UTF-8') ?></textarea></label><label class="full">Descrizione<textarea name="description" rows="7" maxlength="20000"><?= htmlspecialchars((string)$row['description'],ENT_QUOTES,'UTF-8') ?></textarea></label><label>Copertina<input type="file" name="cover_image" accept="image/jpeg,image/png,image/webp"><?php if(!empty($row['cover_image'])): ?><small>Attuale: <?= htmlspecialchars((string)$row['cover_image'],ENT_QUOTES,'UTF-8') ?></small><?php endif; ?></label><label>Ordine<input type="number" name="sort_order" value="<?= (int)$row['sort_order'] ?>"></label><label class="check"><input type="checkbox" name="published" value="1" <?= !empty($row['published'])?'checked':'' ?>> Pubblicata</label></div><p><button class="btn" type="submit">Salva referenza</button></p></form>
<?php if((int)$row['id']): ?>
<div class="panel"><h2>Aggiungi immagine</h2><form method="post" enctype="multipart/form-data" action="/idemaclima/admin/content/references/image"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="reference_id" value="<?= (int)$row['id'] ?>"><div class="formgrid"><label>Immagine<input type="file" name="image_file" accept="image/jpeg,image/png,image/webp" required></label><label>Testo alternativo<input name="alt_text" maxlength="255"></label><label class="full">Didascalia<input name="caption" maxlength="500"></label><label>Ordine<input type="number" name="sort_order" value="0"></label><label class="check"><input type="checkbox" name="published" value="1" checked> Pubblicata</label></div><p><button class="btn" type="submit">Aggiungi immagine</button></p></form></div>
<h2>Immagini</h2>
<?php foreach($images as $img): ?><div class="panel" style="margin-bottom:16px"><div class="formgrid"><div><img src="<?= htmlspecialchars((string)$img['image_path'],ENT_QUOTES,'UTF-8') ?>" alt="" style="width:160px;height:110px;object-fit:cover"></div><form method="post" action="/idemaclima/admin/content/references/image/update" class="full"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="id" value="<?= (int)$img['id'] ?>"><div class="formgrid"><label>Testo alternativo<input name="alt_text" maxlength="255" value="<?= htmlspecialchars((string)$img['alt_text'],ENT_QUOTES,'UTF-8') ?>"></label><label>Didascalia<input name="caption" maxlength="500" value="<?= htmlspecialchars((string)$img['caption'],ENT_QUOTES,'UTF-8') ?>"></label><label>Ordine<input type="number" name="sort_order" value="<?= (int)$img['sort_order'] ?>"></label><label class="check"><input type="checkbox" name="published" value="1" <?= (int)$img['published']?'checked':'' ?>> Pubblicata</label></div><button class="btn" type="submit">Aggiorna immagine</button></form><form method="post" action="/idemaclima/admin/content/references/image/delete" onsubmit="return confirm('Eliminare definitivamente questa immagine?');"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="id" value="<?= (int)$img['id'] ?>"><button type="submit">Elimina immagine</button></form></div></div><?php endforeach; ?>
<form method="post" action="/idemaclima/admin/content/references/archive" onsubmit="return confirm('Archiviare questa referenza? Non sarà più visibile sul sito pubblico.');" style="margin-top:24px"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><button type="submit">Archivia referenza</button></form>
<?php endif; ?>
<?php require __DIR__.'/_layout_end.php'; ?>
