<?php $title=((int)$document['id']?'Modifica':'Nuovo').' documento'; require __DIR__.'/_layout_start.php'; ?><h1><?= htmlspecialchars($title,ENT_QUOTES,'UTF-8') ?></h1><?php foreach($errors as $e): ?><div class="error"><?= htmlspecialchars($e,ENT_QUOTES,'UTF-8') ?></div><?php endforeach; ?>
<form class="panel formgrid" method="post" action="/idemaclima/admin/documents/save" enctype="multipart/form-data"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="id" value="<?= (int)$document['id'] ?>"><input type="hidden" name="existing_filename" value="<?= htmlspecialchars((string)($document['filename']??''),ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="existing_file_path" value="<?= htmlspecialchars((string)($document['file_path']??''),ENT_QUOTES,'UTF-8') ?>">
<label>Tipo<select name="document_type_id" required><option value="">Seleziona</option><?php foreach($types as $t): ?><option value="<?= (int)$t['id'] ?>" <?= (int)$document['document_type_id']===(int)$t['id']?'selected':'' ?>><?= htmlspecialchars($t['name'],ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></label><label>Titolo<input name="title" required maxlength="255" value="<?= htmlspecialchars((string)$document['title'],ENT_QUOTES,'UTF-8') ?>"></label>
<label class="full">File PDF<input type="file" name="document_file" accept="application/pdf" <?= (int)$document['id']===0?'required':'' ?>><small>Solo PDF, massimo 25 MB.<?php if(!empty($document['file_path'])): ?> File attuale: <a href="<?= htmlspecialchars((string)$document['file_path'],ENT_QUOTES,'UTF-8') ?>" target="_blank" rel="noopener"><?= htmlspecialchars((string)($document['filename']??'Apri PDF'),ENT_QUOTES,'UTF-8') ?></a>. Caricandone uno nuovo verrà sostituito.<?php endif; ?></small></label><label>Anno<input type="number" name="document_year" value="<?= htmlspecialchars((string)($document['document_year']??''),ENT_QUOTES,'UTF-8') ?>"></label><label>Revisione<input name="revision" maxlength="80" value="<?= htmlspecialchars((string)($document['revision']??''),ENT_QUOTES,'UTF-8') ?>"></label>
<label>Categoria<select name="category_id"><option value="">—</option><?php foreach($categories as $c): ?><option value="<?= (int)$c['id'] ?>" <?= (int)($document['category_id']??0)===(int)$c['id']?'selected':'' ?>><?= htmlspecialchars($c['name'],ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></label><label>Prodotto<select name="product_id"><option value="">—</option><?php foreach($products as $p): ?><option value="<?= (int)$p['id'] ?>" <?= (int)($document['product_id']??0)===(int)$p['id']?'selected':'' ?>><?= htmlspecialchars($p['name'],ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></label><label>Modello<select name="model_id"><option value="">—</option><?php foreach($models as $m): ?><option value="<?= (int)$m['id'] ?>" <?= (int)($document['model_id']??0)===(int)$m['id']?'selected':'' ?>><?= htmlspecialchars($m['code'],ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></label><label>Ordine<input type="number" name="sort_order" value="<?= (int)$document['sort_order'] ?>"></label><label class="check"><input type="checkbox" name="published" value="1" <?= $document['published']?'checked':'' ?>> Pubblicato</label><div class="full"><button class="btn" type="submit">Salva documento</button> <a href="/idemaclima/admin/documents">Annulla</a></div></form>
<?php if ((int)$document['id'] > 0 && empty($document['category_id']) && empty($document['product_id']) && empty($document['model_id'])): ?>
<form class="panel" method="post" action="/idemaclima/admin/documents/delete" onsubmit="return confirm('Eliminare definitivamente questo documento orfano? Il PDF condiviso con altre schede verrà conservato.');">
<input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>">
<input type="hidden" name="id" value="<?= (int)$document['id'] ?>">
<button class="btn danger" type="submit">Elimina documento orfano</button>
</form>
<?php endif; ?>
<?php require __DIR__.'/_layout_end.php'; ?>

