<?php require __DIR__.'/_layout_start.php'; ?>
<div class="toolbar"><div><h1><?= htmlspecialchars((string)$page['title'],ENT_QUOTES,'UTF-8') ?></h1><p class="muted">Contenuti della pagina e collegamenti pubblici.</p></div><a href="/idemaclima/admin/editorial">Torna alle pagine</a></div>
<form method="post" action="/idemaclima/admin/editorial/save" class="panel"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="id" value="<?= (int)$page['id'] ?>"><div class="formgrid">
<label>Titolo<input name="title" required maxlength="220" value="<?= htmlspecialchars((string)$page['title'],ENT_QUOTES,'UTF-8') ?>"></label><label>Etichetta<input name="eyebrow" maxlength="220" value="<?= htmlspecialchars((string)($page['eyebrow']??''),ENT_QUOTES,'UTF-8') ?>"></label>
<label class="full">Introduzione<textarea name="intro" rows="3"><?= htmlspecialchars((string)($page['intro']??''),ENT_QUOTES,'UTF-8') ?></textarea></label><label class="full">Testo principale<textarea name="body" rows="8"><?= htmlspecialchars((string)($page['body']??''),ENT_QUOTES,'UTF-8') ?></textarea></label>
<label>Titolo SEO<input name="meta_title" maxlength="220" value="<?= htmlspecialchars((string)($page['meta_title']??''),ENT_QUOTES,'UTF-8') ?>"></label><label>Ordine<input type="number" name="sort_order" value="<?= (int)$page['sort_order'] ?>"></label>
<label class="full">Descrizione SEO<textarea name="meta_description" rows="3"><?= htmlspecialchars((string)($page['meta_description']??''),ENT_QUOTES,'UTF-8') ?></textarea></label><label class="check"><input type="checkbox" name="published" value="1" <?= !empty($page['published'])?'checked':'' ?>> Pubblicato</label></div><button class="btn" type="submit">Salva pagina</button></form>

<h2>Sezioni</h2><?php foreach($sections as $section): ?><form method="post" action="/idemaclima/admin/editorial/section/save" class="panel"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="id" value="<?= (int)$section['id'] ?>"><input type="hidden" name="page_id" value="<?= (int)$page['id'] ?>"><div class="formgrid"><label>Titolo<input name="title" required value="<?= htmlspecialchars((string)$section['title'],ENT_QUOTES,'UTF-8') ?>"></label><label>Ancora<input name="anchor_slug" value="<?= htmlspecialchars((string)($section['anchor_slug']??''),ENT_QUOTES,'UTF-8') ?>"></label><label class="full">Testo<textarea name="body" rows="5"><?= htmlspecialchars((string)($section['body']??''),ENT_QUOTES,'UTF-8') ?></textarea></label><label>Ordine<input type="number" name="sort_order" value="<?= (int)$section['sort_order'] ?>"></label><label class="check"><input type="checkbox" name="published" value="1" <?= !empty($section['published'])?'checked':'' ?>> Pubblicata</label></div><button class="btn" type="submit">Salva sezione</button> <button class="btn btn-secondary" formaction="/idemaclima/admin/editorial/section/delete" onclick="return confirm('Eliminare questa sezione?')">Elimina</button></form><?php endforeach; ?>
<form method="post" action="/idemaclima/admin/editorial/section" class="panel"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="page_id" value="<?= (int)$page['id'] ?>"><h3>Nuova sezione</h3><div class="formgrid"><label>Titolo<input name="title" required></label><label>Ancora<input name="anchor_slug"></label><label class="full">Testo<textarea name="body" rows="4"></textarea></label><label>Ordine<input type="number" name="sort_order" value="0"></label></div><button class="btn" type="submit">Aggiungi sezione</button></form>

<h2>Domande frequenti</h2><?php foreach($faqs as $faq): ?><form method="post" action="/idemaclima/admin/editorial/faq/save" class="panel"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="id" value="<?= (int)$faq['id'] ?>"><input type="hidden" name="page_id" value="<?= (int)$page['id'] ?>"><div class="formgrid"><label class="full">Domanda<input name="question" required value="<?= htmlspecialchars((string)$faq['question'],ENT_QUOTES,'UTF-8') ?>"></label><label class="full">Risposta<textarea name="answer" rows="4" required><?= htmlspecialchars((string)$faq['answer'],ENT_QUOTES,'UTF-8') ?></textarea></label><label>Ordine<input type="number" name="sort_order" value="<?= (int)$faq['sort_order'] ?>"></label><label class="check"><input type="checkbox" name="published" value="1" <?= !empty($faq['published'])?'checked':'' ?>> Pubblicata</label></div><button class="btn" type="submit">Salva FAQ</button> <button class="btn btn-secondary" formaction="/idemaclima/admin/editorial/faq/delete" onclick="return confirm('Eliminare questa FAQ?')">Elimina</button></form><?php endforeach; ?>
<form method="post" action="/idemaclima/admin/editorial/faq" class="panel"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="page_id" value="<?= (int)$page['id'] ?>"><h3>Nuova FAQ</h3><div class="formgrid"><label class="full">Domanda<input name="question" required></label><label class="full">Risposta<textarea name="answer" rows="4" required></textarea></label><label>Ordine<input type="number" name="sort_order" value="0"></label></div><button class="btn" type="submit">Aggiungi FAQ</button></form>

<h2>Documenti collegati</h2><div class="panel"><?php foreach($links as $link): ?><form method="post" action="/idemaclima/admin/editorial/document/delete" style="display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:12px"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="id" value="<?= (int)$link['id'] ?>"><input type="hidden" name="page_id" value="<?= (int)$page['id'] ?>"><span><strong><?= htmlspecialchars((string)($link['label']?:$link['title']),ENT_QUOTES,'UTF-8') ?></strong><br><span class="muted"><?= htmlspecialchars((string)($link['group_label']??'Documenti'),ENT_QUOTES,'UTF-8') ?></span></span><button class="btn btn-secondary" onclick="return confirm('Scollegare il documento?')">Scollega</button></form><?php endforeach; ?>
<form method="post" action="/idemaclima/admin/editorial/document"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="page_id" value="<?= (int)$page['id'] ?>"><div class="formgrid"><label>Documento<select name="document_id" required><option value="">Seleziona</option><?php foreach($documents as $document): ?><option value="<?= (int)$document['id'] ?>"><?= htmlspecialchars((string)$document['title'],ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></label><label>Gruppo<input name="group_label" maxlength="220"></label><label>Etichetta<input name="label" maxlength="220"></label><label>Ordine<input type="number" name="sort_order" value="0"></label></div><button class="btn" type="submit">Collega documento</button></form></div>
<?php require __DIR__.'/_layout_end.php'; ?>
