<?php require __DIR__.'/_layout_start.php'; ?>
<h1><?= htmlspecialchars($page['title'],ENT_QUOTES,'UTF-8') ?></h1>
<form class="panel formgrid" method="post" action="/admin/editorial/save"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="id" value="<?= (int)$page['id'] ?>">
<label>Titolo<input name="title" required maxlength="220" value="<?= htmlspecialchars($page['title'],ENT_QUOTES,'UTF-8') ?>"></label><label>Eyebrow<input name="eyebrow" maxlength="160" value="<?= htmlspecialchars((string)($page['eyebrow']??''),ENT_QUOTES,'UTF-8') ?>"></label>
<label class="full">Introduzione<textarea name="intro" rows="3"><?= htmlspecialchars((string)($page['intro']??''),ENT_QUOTES,'UTF-8') ?></textarea></label><label class="full">Corpo pagina<textarea name="body" rows="8"><?= htmlspecialchars((string)($page['body']??''),ENT_QUOTES,'UTF-8') ?></textarea></label>
<label>Meta title<input name="meta_title" maxlength="255" value="<?= htmlspecialchars((string)($page['meta_title']??''),ENT_QUOTES,'UTF-8') ?>"></label><label>Meta description<input name="meta_description" maxlength="320" value="<?= htmlspecialchars((string)($page['meta_description']??''),ENT_QUOTES,'UTF-8') ?>"></label>
<label>Ordine<input type="number" name="sort_order" value="<?= (int)$page['sort_order'] ?>"></label><label class="check"><input type="checkbox" name="published" value="1" <?= $page['published']?'checked':'' ?>> Pubblicata</label><div class="full"><button class="btn">Salva pagina</button></div></form>
<h2>Sezioni</h2><div class="panel"><?php foreach($sections as $s): ?><p><strong><?= htmlspecialchars($s['title'],ENT_QUOTES,'UTF-8') ?></strong> <span class="muted">#<?= htmlspecialchars((string)($s['anchor_slug']??''),ENT_QUOTES,'UTF-8') ?></span></p><?php endforeach; ?><form class="formgrid" method="post" action="/admin/editorial/section"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="page_id" value="<?= (int)$page['id'] ?>"><label>Titolo<input name="title" required></label><label>Ancora<input name="anchor_slug"></label><label class="full">Testo<textarea name="body" rows="5"></textarea></label><label>Ordine<input type="number" name="sort_order" value="0"></label><div><button class="btn">Aggiungi sezione</button></div></form></div>
<h2>FAQ</h2><div class="panel"><?php foreach($faqs as $f): ?><p><strong><?= htmlspecialchars($f['question'],ENT_QUOTES,'UTF-8') ?></strong></p><?php endforeach; ?><form class="formgrid" method="post" action="/admin/editorial/faq"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="page_id" value="<?= (int)$page['id'] ?>"><label class="full">Domanda<input name="question" required></label><label class="full">Risposta<textarea name="answer" rows="5" required></textarea></label><label>Ordine<input type="number" name="sort_order" value="0"></label><div><button class="btn">Aggiungi FAQ</button></div></form></div>
<h2>Documenti collegati</h2><div class="panel"><?php foreach($links as $l): ?><p><strong><?= htmlspecialchars((string)($l['label']?:$l['title']),ENT_QUOTES,'UTF-8') ?></strong> <span class="muted"><?= htmlspecialchars((string)($l['group_label']??''),ENT_QUOTES,'UTF-8') ?></span></p><?php endforeach; ?><form class="formgrid" method="post" action="/admin/editorial/document"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="page_id" value="<?= (int)$page['id'] ?>"><label>Documento<select name="document_id" required><option value="">Seleziona</option><?php foreach($documents as $d): ?><option value="<?= (int)$d['id'] ?>"><?= htmlspecialchars($d['title'],ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></label><label>Gruppo<input name="group_label" placeholder="Es. Linea Residenziale"></label><label>Etichetta<input name="label"></label><label>Ordine<input type="number" name="sort_order" value="0"></label><div class="full"><button class="btn">Collega documento</button></div></form></div>
<?php require __DIR__.'/_layout_end.php'; ?>
