<?php require __DIR__.'/_layout_start.php'; ?>
<style>.easytool-actions{display:flex;flex-wrap:wrap;gap:8px;align-items:center}.easytool-actions form{margin:0}.admin-modern .inlineform.easytool-filters{grid-template-columns:minmax(0,1fr) 100px auto}.easytool-filters .btn,.easytool-filters .btnlink{white-space:nowrap;min-height:42px}@media(max-width:760px){.admin-modern .inlineform.easytool-filters{grid-template-columns:1fr}.easytool-filters .btn,.easytool-filters .btnlink{width:100%}}</style>
<div class="toolbar"><div><h1>Richieste EasyTool<?= !empty($trashed)?' — Cestino':'' ?></h1><p class="muted">Richieste inviate dal modulo EasyTool.</p></div><div style="display:flex;gap:10px;flex-wrap:wrap"><a class="btnlink" href="/idemaclima/admin/incentives/import">Importa da WPForms</a><a class="btnlink" href="/idemaclima/admin/editorial">Gestisci contenuti</a></div></div>
<p><a class="btnlink" href="/idemaclima/admin/incentives?trash=<?= !empty($trashed)?'0':'1' ?>"><?= !empty($trashed)?'Torna alle richieste':'Cestino' ?></a></p>
<p class="muted"><?= count($rows) ?> richieste<?= $status!==''?' nel filtro selezionato':' in archivio' ?></p>
<form method="get" class="panel" style="margin-bottom:18px"><input type="hidden" name="trash" value="<?= !empty($trashed)?'1':'0' ?>"><div class="inlineform easytool-filters"><label>Stato<select name="status"><option value="">Tutti</option><?php foreach(['new'=>'Nuova','in_progress'=>'In lavorazione','closed'=>'Chiusa','spam'=>'Spam'] as $value=>$label): ?><option value="<?= $value ?>" <?= $status===$value?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></label><button class="btn" type="submit">Filtra</button><a class="btnlink" href="/idemaclima/admin/incentives?trash=<?= !empty($trashed)?'1':'0' ?>&amp;status=" data-reset-filters>Azzera filtri</a></div></form>
<div class="table-wrap"><table><thead><tr><th>Data</th><th>Nome</th><th>Località</th><th>Ruolo</th><th>Stato</th><th></th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><?= htmlspecialchars((string)$row['created_at']) ?></td><td><strong><?= htmlspecialchars($row['first_name'].' '.$row['last_name']) ?></strong><br><span class="muted"><?= htmlspecialchars($row['email']) ?></span><?php if(!empty($row['import_review_warning'])):?><br><span class="badge" style="white-space:nowrap">Da verificare</span><?php endif;?></td><td><?= htmlspecialchars($row['city'].' ('.$row['province'].')') ?></td><td><?= htmlspecialchars($row['professional_role']) ?></td><td><span class="badge" style="white-space:nowrap"><?= htmlspecialchars($row['status']) ?></span></td><td><div class="easytool-actions"><a href="/idemaclima/admin/incentives/request?id=<?= (int)$row['id'] ?>">Apri</a>
<form method="post" action="/idemaclima/admin/incentives/<?= !empty($trashed)?'restore':'delete' ?>"<?= empty($trashed)?' data-confirm="Spostare questa richiesta nel cestino? Potrai ripristinarla."':'' ?>>
<input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf) ?>"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>">
<button class="btn btn-secondary" type="submit"><?= !empty($trashed)?'Ripristina':'Elimina' ?></button></form>
<?php if(!empty($trashed)): ?><form method="post" action="/idemaclima/admin/incentives/purge" data-confirm="Eliminare definitivamente questa richiesta? Questa operazione non può essere annullata.">
<input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf) ?>"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><input type="hidden" name="confirm_permanent" value="1">
<button class="btn btn-secondary" type="submit">Elimina definitivamente</button></form><?php endif; ?>
</div></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="6" class="empty">Nessuna richiesta.</td></tr><?php endif; ?></tbody></table></div>
<?php require __DIR__.'/_layout_end.php'; ?>
