<?php require __DIR__.'/_layout_start.php'; ?>
<?php if(!empty($row['import_review_warning'])):?><div class="panel" style="margin-bottom:18px;border-color:#d97706"><strong>Da verificare</strong><p style="margin-bottom:0"><?= htmlspecialchars((string)$row['import_review_warning']) ?></p></div><?php endif;?>
<div class="toolbar"><div><h1>Richiesta #<?= (int)$row['id'] ?></h1><p class="muted">Ricevuta il <?= htmlspecialchars((string)$row['created_at']) ?></p></div><a class="btnlink" href="/idemaclima/admin/incentives<?= !empty($row['deleted_at'])?'?trash=1':'' ?>">Torna alle richieste</a></div>
<div class="cards" style="margin-bottom:18px"><div class="panel"><strong>Richiedente</strong><p><?= htmlspecialchars($row['first_name'].' '.$row['last_name']) ?><br><?= htmlspecialchars((string)($row['company']??'')) ?></p></div><div class="panel"><strong>Contatti</strong><p><?= htmlspecialchars($row['email']) ?><br><?= htmlspecialchars($row['phone']) ?></p></div><div class="panel"><strong>Località</strong><p><?= htmlspecialchars($row['postal_code'].' '.$row['city'].' ('.$row['province'].')') ?><br><?= htmlspecialchars($row['region']) ?></p></div><div class="panel"><strong>Profilo</strong><p><?= htmlspecialchars($row['professional_role']) ?></p></div></div>
<?php if(empty($row['deleted_at'])): ?><form class="panel" method="post" action="/idemaclima/admin/incentives/update"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf) ?>"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><div class="formgrid"><label>Stato<select name="status"><?php foreach(['new'=>'Nuova','in_progress'=>'In lavorazione','closed'=>'Chiusa','spam'=>'Spam'] as $value=>$label): ?><option value="<?= $value ?>" <?= $row['status']===$value?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></label><label class="full">Note amministrative<textarea name="admin_notes" maxlength="10000"><?= htmlspecialchars((string)($row['admin_notes']??'')) ?></textarea></label></div><button class="btn" type="submit">Salva</button></form><?php else: ?><p class="panel">Questa richiesta è nel Cestino.</p><?php endif; ?>
<form method="post" action="/idemaclima/admin/incentives/<?= empty($row['deleted_at'])?'delete':'restore' ?>"<?= empty($row['deleted_at'])?' data-confirm="Spostare questa richiesta nel cestino? Potrai ripristinarla."':'' ?> style="margin-top:18px">
<input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf) ?>"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><button class="btn btn-secondary" type="submit"><?= empty($row['deleted_at'])?'Elimina':'Ripristina' ?></button></form>
<?php if(!empty($row['deleted_at'])): ?><form method="post" action="/idemaclima/admin/incentives/purge" data-confirm="Eliminare definitivamente questa richiesta? Questa operazione non può essere annullata." style="margin-top:12px">
<input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf) ?>"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><input type="hidden" name="confirm_permanent" value="1"><button class="btn btn-secondary" type="submit">Elimina definitivamente</button></form><?php endif; ?>
<?php require __DIR__.'/_layout_end.php'; ?>
