<?php $title = 'Accesso amministrazione'; $user = null; require __DIR__ . '/_layout_start.php'; ?>
<!-- Controllo visibilità password amministratore -->
<style>
.admin-shell{display:block}.admin-content{min-height:100vh;display:grid;place-items:center}.admin-content main{width:100%;padding:24px}.login-panel{width:min(100%,440px);margin:0 auto;padding:30px}.login-panel .btn{width:100%}
.password-field{position:relative;margin-top:7px}.password-field input{width:100%;margin:0;padding-right:52px}.password-toggle{position:absolute;top:50%;right:5px;display:grid;width:40px;height:40px;padding:0;place-items:center;transform:translateY(-50%);border:0;border-radius:8px;background:transparent;color:inherit;cursor:pointer}.password-toggle:hover{background:rgba(15,72,94,.08)}.password-toggle:focus-visible{outline:2px solid var(--blue);outline-offset:1px}.password-toggle svg{width:21px;height:21px;fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:2}.password-toggle .eye-off{display:none}.password-toggle[aria-pressed="true"] .eye-on{display:none}.password-toggle[aria-pressed="true"] .eye-off{display:block}
</style>
<div class="panel login-panel"><h1>Accesso amministrazione</h1><p class="muted">Inserisci le credenziali per accedere al pannello IDEMA CLIMA.</p><?php if ($error): ?><div class="error"><?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8') ?></div><?php endif; ?><form method="post" action="/idemaclima/admin/login"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf, ENT_QUOTES, 'UTF-8') ?>"><label>Email o username<input name="login" autocomplete="username" required></label><br><br><label for="admin-password">Password</label><div class="password-field"><input id="admin-password" type="password" name="password" autocomplete="current-password" required><button class="password-toggle" type="button" aria-label="Mostra password" aria-controls="admin-password" aria-pressed="false"><svg class="eye-on" viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></svg><svg class="eye-off" viewBox="0 0 24 24" aria-hidden="true"><path d="m3 3 18 18"/><path d="M10.6 5.2A10.8 10.8 0 0 1 12 5c6.5 0 10 7 10 7a17.8 17.8 0 0 1-2.1 3.1M6.2 6.2C3.5 8.1 2 12 2 12s3.5 7 10 7a9.8 9.8 0 0 0 4.1-.9"/><path d="M9.9 9.9a3 3 0 0 0 4.2 4.2"/></svg></button></div><br><br><button class="btn" type="submit">Accedi</button></form></div>
<script nonce="<?= htmlspecialchars(\App\Core\Security::nonce(), ENT_QUOTES, 'UTF-8') ?>">(()=>{const button=document.querySelector('.password-toggle'),input=document.getElementById('admin-password');if(!button||!input)return;button.addEventListener('click',()=>{const show=input.type==='password';input.type=show?'text':'password';button.setAttribute('aria-pressed',show?'true':'false');button.setAttribute('aria-label',show?'Nascondi password':'Mostra password');input.focus()})})();</script>
<?php require __DIR__ . '/_layout_end.php'; ?>
