<?php require __DIR__.'/_layout_start.php'; ?>
<div class="toolbar"><div><h1>Importa pagina Mono Split</h1><p class="muted">Aggiorna testi e dati di un prodotto partendo da una pagina precisa di catalogo o listino.</p></div></div>
<?php if($imported): ?><p class="panel" style="border-color:#9acb70;background:#f3faed">Importazione completata. Il prodotto è stato aggiornato.</p><?php endif; ?>
<?php if($error): ?><p class="error"><?= htmlspecialchars($error,ENT_QUOTES,'UTF-8') ?></p><?php endif; ?>
<form class="panel" method="post" action="/idemaclima/admin/mono-split-import/run"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><div class="formgrid">
<label>Prodotto Mono Split<select name="product_id" required><option value="">Seleziona</option><?php foreach($products as $p): ?><option value="<?= (int)$p['id'] ?>" <?= (int)($old['product_id']??0)===(int)$p['id']?'selected':'' ?>><?= htmlspecialchars($p['family_name'].' — '.$p['name'],ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></label>
<label>Pagina del catalogo/listino<input type="number" name="source_page" min="1" max="999" value="<?= (int)($old['source_page']??1) ?>" required></label>
<label class="full">Collegamento al catalogo/listino<input type="url" name="source_url" maxlength="1000" value="<?= htmlspecialchars((string)($old['source_url']??''),ENT_QUOTES,'UTF-8') ?>" placeholder="https://www.idemaclima.it/..." required></label>
<label class="full">Testo della pagina<textarea name="source_text" rows="18" maxlength="60000" required placeholder="Incolla il testo della sola pagina. Usa le intestazioni CARATTERISTICHE, SPECIFICHE TECNICHE e ACCESSORI; per le specifiche usa Nome | Valore."><?= htmlspecialchars((string)($old['source_text']??''),ENT_QUOTES,'UTF-8') ?></textarea></label>
</div><p class="muted">Il controllo non modifica il sito. L’importazione sostituisce soltanto le sezioni riconosciute e conserva immagini, modelli e documenti PDF.</p><div style="display:flex;gap:10px;flex-wrap:wrap"><button class="btn" name="action" value="preview" type="submit">Controlla anteprima</button><?php if($preview): ?><button class="btn" name="action" value="execute" type="submit" data-confirm="Importare questi contenuti nel prodotto selezionato?">Importa nel prodotto</button><?php endif; ?></div></form>
<?php if($preview): ?><section class="panel" style="margin-top:20px"><h2>Anteprima contenuti riconosciuti</h2><h3>Descrizione</h3><p><?= nl2br(htmlspecialchars($preview['description'],ENT_QUOTES,'UTF-8')) ?></p><?php foreach(['features'=>'Caratteristiche','specifications'=>'Specifiche tecniche','accessories'=>'Accessori'] as $key=>$label): ?><h3><?= $label ?> (<?= count($preview[$key]) ?>)</h3><?php if($preview[$key]): ?><ul><?php foreach($preview[$key] as $row): ?><li><?= htmlspecialchars($row,ENT_QUOTES,'UTF-8') ?></li><?php endforeach; ?></ul><?php else: ?><p class="muted">Nessun elemento riconosciuto.</p><?php endif; ?><?php endforeach; ?></section><?php endif; ?>
<?php require __DIR__.'/_layout_end.php'; ?>
