<?php
$title='Schede tecniche — Gestione immagini prodotti';
$labels=['to_review'=>'Da verificare','insufficient'=>'Qualità insufficiente','recovered'=>'Recuperata dal catalogo','missing_catalog'=>'Catalogo mancante','approved'=>'Approvata'];
require __DIR__.'/_layout_start.php';
?>
<style>
.image-summary{display:grid;grid-template-columns:repeat(5,minmax(130px,1fr));gap:12px;margin:0 0 22px}.image-summary button{width:100%;text-align:left;padding:14px;border:1px solid var(--line);border-radius:12px;background:#fff;color:inherit}.image-summary strong{display:block;font-size:24px}.image-tools{display:grid;grid-template-columns:minmax(240px,1fr) 240px auto;gap:12px;margin-bottom:18px}.image-table{min-width:1180px}.product-image{width:84px;height:84px;object-fit:contain;background:#f8fafc;border:1px solid var(--line);border-radius:8px}.image-cell small{display:block;max-width:190px;overflow-wrap:anywhere}.review-form{display:grid;gap:8px;min-width:270px}.review-form input,.review-form select,.review-form textarea{margin:0}.review-form textarea{min-height:68px}.review-actions{display:flex;gap:8px;flex-wrap:wrap}.review-actions form{margin:0}.review-actions .btn{padding:8px 10px;min-height:38px}.approve{background:#167647}.protected{padding:9px;border-radius:8px;background:#eef2f7;color:var(--muted);font-weight:700}.quality-low{color:#a13b10;font-weight:700}
@media(max-width:760px){.image-summary{grid-template-columns:1fr 1fr}.image-tools{grid-template-columns:1fr}}
</style>
<div class="toolbar"><div><h1>Gestione immagini prodotti</h1><p class="muted">Confronta l’immagine attuale con quella recuperata dai cataloghi. All’approvazione il file viene rinominato in base al modello, convertito in WebP su tela 600×600 senza deformazioni e riassociato al prodotto.</p></div></div>
<?php if($saved):?><p class="panel">Revisione salvata senza modificare il frontend.</p><?php endif;?>
<?php if($approved):?><p class="panel">Immagine rinominata, approvata e assegnata al prodotto.</p><?php endif;?>
<?php if($removed):?><p class="panel">La nuova immagine è stata rimossa. È stata ripristinata quella precedente, quando disponibile.</p><?php endif;?>
<?php if($error!==''):?><p class="error"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></p><?php endif;?>
<div class="image-summary"><?php foreach($labels as $key=>$label):?><button type="button" data-status-jump="<?=$key?>"><strong><?=(int)($summary[$key]??0)?></strong><?=$label?></button><?php endforeach;?></div>
<div class="image-tools"><label>Cerca<input type="search" id="image-search" placeholder="Prodotto, serie o catalogo"></label><label>Stato<select id="image-status"><option value="">Tutti</option><?php foreach($labels as $key=>$label):?><option value="<?=$key?>"><?=$label?></option><?php endforeach;?></select></label><label class="check"><input type="checkbox" id="only-missing"> Solo immagini mancanti</label></div>
<div class="table-wrap"><table class="image-table"><thead><tr><th>Prodotto</th><th>Immagine attuale</th><th>Candidata</th><th>Revisione e provenienza</th></tr></thead><tbody id="image-rows">
<?php foreach($items as $item):
  $hasCurrent=(string)($item['image_path']??'')!=='';
  $search=strtolower(($item['category_group']??'').' '.($item['category_name']??'').' '.$item['name'].' '.($item['source_catalog']??''));
?>
<tr data-search="<?=htmlspecialchars($search,ENT_QUOTES,'UTF-8')?>" data-status="<?=htmlspecialchars((string)$item['review_status'],ENT_QUOTES,'UTF-8')?>" data-missing="<?=$hasCurrent?'0':'1'?>">
<td><strong><?=htmlspecialchars((string)$item['name'],ENT_QUOTES,'UTF-8')?></strong><br><small class="muted"><?=htmlspecialchars(trim(($item['category_group']??'').' · '.($item['category_name']??''),' ·'),ENT_QUOTES,'UTF-8')?></small><?php if((int)$item['protected']===1):?><br><span class="badge">Mono Split protetto</span><?php endif;?></td>
<td class="image-cell"><?php if($hasCurrent):?><img class="product-image" src="<?=htmlspecialchars((string)$item['image_path'],ENT_QUOTES,'UTF-8')?>" alt=""><small><?=htmlspecialchars((string)$item['image_path'],ENT_QUOTES,'UTF-8')?></small><small class="<?=($item['current_width']??0)<300?'quality-low':'muted'?>"><?php if($item['current_width']):?><?=(int)$item['current_width']?>×<?=(int)$item['current_height']?> px<?php else:?>Dimensioni non rilevate<?php endif;?></small><?php else:?><span class="quality-low">Mancante</span><?php endif;?></td>
<td class="image-cell"><?php if(!empty($item['candidate_path'])):?><img class="product-image" src="<?=htmlspecialchars((string)$item['candidate_path'],ENT_QUOTES,'UTF-8')?>" alt=""><small><?=htmlspecialchars((string)$item['candidate_path'],ENT_QUOTES,'UTF-8')?></small><small><?=(int)($item['candidate_width']??0)?>×<?=(int)($item['candidate_height']??0)?> px</small><?php else:?><span class="muted">Nessuna candidata</span><?php endif;?></td>
<td><?php if((int)$item['protected']===1):?><div class="protected">Escluso dal censimento e dalla sostituzione.</div><?php else:?>
<form class="review-form" method="post" action="/idemaclima/admin/product-images/save" enctype="multipart/form-data">
<input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="product_id" value="<?=(int)$item['product_id']?>">
<select name="review_status"><?php foreach(array_diff_key($labels,['approved'=>true]) as $key=>$label):?><option value="<?=$key?>" <?=$item['review_status']===$key?'selected':''?>><?=$label?></option><?php endforeach;?></select>
<input type="file" name="candidate_file" accept="image/jpeg,image/png,image/webp">
<select name="media_id"><option value="0">Oppure scegli dalla Media Library</option><?php foreach($media as $asset):?><option value="<?=(int)$asset['id']?>"><?=htmlspecialchars((string)$asset['title'],ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select>
<div class="formgrid"><input name="source_catalog" value="<?=htmlspecialchars((string)($item['source_catalog']??''),ENT_QUOTES,'UTF-8')?>" placeholder="Catalogo"><input type="number" min="1" name="source_page" value="<?=htmlspecialchars((string)($item['source_page']??''),ENT_QUOTES,'UTF-8')?>" placeholder="Pagina"></div>
<textarea name="notes" placeholder="Note"><?=htmlspecialchars((string)($item['notes']??''),ENT_QUOTES,'UTF-8')?></textarea><button class="btn" type="submit">Salva revisione</button></form>
<?php if(!empty($item['candidate_path'])):?><div class="review-actions"><form method="post" action="/idemaclima/admin/product-images/approve" onsubmit="return confirm(this.replace_existing.checked?'ATTENZIONE: se esiste un file diverso con lo stesso nome verrà sostituito. Continuare?':'Rinominare il file in base al modello, approvarlo e assegnarlo al prodotto?')"><input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="product_id" value="<?=(int)$item['product_id']?>"><label class="check"><input type="checkbox" name="replace_existing" value="1"> Sostituisci il file esistente</label><button class="btn approve" type="submit">Rinomina, approva e assegna</button></form></div><?php endif;?>
<?php if($item['review_status']==='approved'&&!empty($item['candidate_path'])):?><div class="review-actions"><form method="post" action="/idemaclima/admin/product-images/remove-assigned" onsubmit="return confirm('Eliminare la nuova immagine associata? Verrà ripristinata quella precedente, se disponibile.')"><input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="product_id" value="<?=(int)$item['product_id']?>"><button class="danger" type="submit">Rimuovi immagine assegnata</button></form></div><?php endif;?>
<?php endif;?></td></tr>
<?php endforeach;?></tbody></table></div><p class="empty" id="image-empty" hidden>Nessun prodotto corrisponde ai filtri.</p>
<script nonce="<?=htmlspecialchars(\App\Core\Security::nonce(),ENT_QUOTES,'UTF-8')?>">(()=>{const q=document.getElementById('image-search'),s=document.getElementById('image-status'),m=document.getElementById('only-missing'),rows=[...document.querySelectorAll('#image-rows tr')],empty=document.getElementById('image-empty');const apply=()=>{let visible=0;rows.forEach(row=>{const show=(!q.value.trim()||row.dataset.search.includes(q.value.trim().toLowerCase()))&&(!s.value||row.dataset.status===s.value)&&(!m.checked||row.dataset.missing==='1');row.hidden=!show;if(show)visible++});empty.hidden=visible!==0};[q,s,m].forEach(el=>el.addEventListener('input',apply));document.querySelectorAll('[data-status-jump]').forEach(button=>button.addEventListener('click',()=>{s.value=button.dataset.statusJump;apply()}))})();</script>
<?php require __DIR__.'/_layout_end.php'; ?>
