<?php
$title='Schede tecniche — Gestione immagini prodotti';
$labels=['to_review'=>'Da verificare','insufficient'=>'Qualità insufficiente','recovered'=>'Recuperata dal catalogo','missing_catalog'=>'Catalogo mancante','approved'=>'Approvata'];
require __DIR__.'/_layout_start.php';
?>
<style>
.image-summary{display:grid;grid-template-columns:repeat(5,minmax(130px,1fr));gap:12px;margin:0 0 22px}.image-summary button{width:100%;text-align:left;padding:14px;border:1px solid var(--line);border-radius:12px;background:#fff;color:inherit}.image-summary strong{display:block;font-size:24px}.image-tools{display:grid;grid-template-columns:minmax(240px,1fr) 240px auto;gap:12px;margin-bottom:18px}.image-table{min-width:1180px}.product-image{width:84px;height:84px;object-fit:contain;background:#f8fafc;border:1px solid var(--line);border-radius:8px}.image-cell small{display:block;max-width:190px;overflow-wrap:anywhere}.review-form{display:grid;gap:8px;min-width:270px}.review-form input,.review-form select,.review-form textarea{margin:0}.review-form textarea{min-height:68px}.review-actions{display:flex;gap:8px;flex-wrap:wrap}.review-actions form{margin:0}.review-actions .btn{padding:8px 10px;min-height:38px}.approve{background:#167647}.protected{padding:9px;border-radius:8px;background:#eef2f7;color:var(--muted);font-weight:700}.quality-low{color:#a13b10;font-weight:700}.bulk-import{margin:0 0 20px;padding:18px}.bulk-import form{display:grid;grid-template-columns:minmax(260px,1fr) minmax(220px,1fr) auto;gap:12px;align-items:end}.sort-button{border:0;background:transparent;padding:0;color:inherit;font:inherit;font-weight:800;cursor:pointer}.sort-button::after{content:' ↕';color:var(--muted)}.sort-button[data-direction='asc']::after{content:' ↑'}.sort-button[data-direction='desc']::after{content:' ↓'}
@media(max-width:760px){.image-summary{grid-template-columns:1fr 1fr}.image-tools,.bulk-import form{grid-template-columns:1fr}}
</style>
<div class="toolbar"><div><h1>Gestione immagini prodotti</h1><p class="muted">Confronta l’immagine attuale con quella recuperata dai cataloghi. All’approvazione il file viene rinominato in base al modello, convertito in WebP su tela 600×600 senza deformazioni e riassociato al prodotto.</p></div></div>
<section class="panel bulk-import"><h2>Importazione multipla immagini candidate</h2><p class="muted">Sono accettate esclusivamente immagini PNG o WebP con sfondo realmente trasparente. Il nome del file viene confrontato con il modello del prodotto. Le immagini restano candidate e non modificano il frontend.</p><form method="post" action="/idemaclima/admin/product-images/bulk-import" enctype="multipart/form-data"><input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><label>Immagini candidate<input type="file" name="candidate_files[]" accept="image/png,image/webp" multiple required></label><label>Catalogo o sorgente<input name="source_catalog" value="" maxlength="190"></label><button class="btn" type="submit">Importa candidate</button></form><form method="post" action="/idemaclima/admin/product-images/save" data-confirm="Verificare tutte le candidature esistenti e rimuovere quelle senza sfondo trasparente?"><input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="audit_transparency" value="1"><button class="btn danger" type="submit">Verifica trasparenza candidature esistenti</button></form></section>
<?php if($bulkImported||$bulkSkipped):?><div class="panel"><strong>Importazione completata:</strong> <?=(int)$bulkImported?> associazioni create o aggiornate; <?=(int)$bulkSkipped?> file scartati. Nessuna immagine è stata approvata o assegnata al frontend.<?php if($bulkErrors):?><details><summary>Dettagli file non importati</summary><ul><?php foreach($bulkErrors as $bulkError):?><li><?=htmlspecialchars((string)$bulkError,ENT_QUOTES,'UTF-8')?></li><?php endforeach;?></ul></details><?php endif;?></div><?php endif;?>
<?php if($saved):?><p class="panel">Revisione salvata senza modificare il frontend.</p><?php endif;?>
<?php if($approved):?><p class="panel">Immagine rinominata, approvata e assegnata al prodotto.</p><?php endif;?>
<?php if($candidateRemoved):?><p class="panel">L’immagine candidata è stata rimossa senza modificare il frontend.</p><?php endif;?>
<?php if($transparencyChecked):?><p class="panel">Controllo trasparenza completato: <?=(int)$transparencyChecked?> candidature verificate, <?=(int)$transparencyRemoved?> non conformi rimosse.</p><?php endif;?>
<?php if($removed):?><p class="panel">La nuova immagine è stata rimossa. È stata ripristinata quella precedente, quando disponibile.</p><?php endif;?>
<?php if($error!==''):?><p class="error"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></p><?php endif;?>
<div class="image-summary"><?php foreach($labels as $key=>$label):?><button type="button" data-status-jump="<?=$key?>"><strong><?=(int)($summary[$key]??0)?></strong><?=$label?></button><?php endforeach;?></div>
<div class="image-tools"><label>Cerca<input type="search" id="image-search" placeholder="Prodotto, serie o catalogo"></label><label>Stato<select id="image-status"><option value="">Tutti</option><?php foreach($labels as $key=>$label):?><option value="<?=$key?>"><?=$label?></option><?php endforeach;?></select></label><label class="check"><input type="checkbox" id="only-missing"> Solo immagini mancanti</label></div>
<datalist id="media-library-assets"><?php foreach($media as $asset):?><option value="<?=(int)$asset['id']?>" label="<?=htmlspecialchars((string)$asset['title'],ENT_QUOTES,'UTF-8')?>"></option><?php endforeach;?></datalist>
<div class="table-wrap"><table class="image-table"><thead><tr><th><button type="button" class="sort-button" data-sort="product">Prodotto</button></th><th><button type="button" class="sort-button" data-sort="current">Immagine attuale</button></th><th><button type="button" class="sort-button" data-sort="candidate">Candidata</button></th><th><button type="button" class="sort-button" data-sort="status">Revisione e provenienza</button></th></tr></thead><tbody id="image-rows">
<?php foreach($items as $item):
  $hasCurrent=(string)($item['image_path']??'')!=='' && !empty($item['current_width']);
  $canRestore=(int)$item['protected']===1 && !$hasCurrent;
  $search=strtolower(($item['category_group']??'').' '.($item['category_name']??'').' '.$item['name'].' '.($item['source_catalog']??''));
?>
<tr data-search="<?=htmlspecialchars($search,ENT_QUOTES,'UTF-8')?>" data-status="<?=htmlspecialchars((string)$item['review_status'],ENT_QUOTES,'UTF-8')?>" data-missing="<?=$hasCurrent?'0':'1'?>" data-sort-product="<?=htmlspecialchars(strtolower((string)$item['name']),ENT_QUOTES,'UTF-8')?>" data-sort-current="<?=(int)($item['current_width']??0)*(int)($item['current_height']??0)?>" data-sort-candidate="<?=(int)($item['candidate_width']??0)*(int)($item['candidate_height']??0)?>" data-sort-status="<?=htmlspecialchars((string)$item['review_status'],ENT_QUOTES,'UTF-8')?>">
<td><strong><?=htmlspecialchars((string)$item['name'],ENT_QUOTES,'UTF-8')?></strong><br><small class="muted"><?=htmlspecialchars(trim(($item['category_group']??'').' · '.($item['category_name']??''),' ·'),ENT_QUOTES,'UTF-8')?></small><?php if((int)$item['protected']===1):?><br><span class="badge">Mono Split protetto</span><?php endif;?></td>
<td class="image-cell"><?php if($hasCurrent):?><img class="product-image" src="<?=htmlspecialchars((string)$item['image_path'],ENT_QUOTES,'UTF-8')?>" alt=""><small><?=htmlspecialchars((string)$item['image_path'],ENT_QUOTES,'UTF-8')?></small><small class="<?=($item['current_width']??0)<300?'quality-low':'muted'?>"><?php if($item['current_width']):?><?=(int)$item['current_width']?>×<?=(int)$item['current_height']?> px<?php else:?>Dimensioni non rilevate<?php endif;?></small><?php else:?><span class="quality-low">Mancante</span><?php endif;?></td>
<td class="image-cell"><?php if(!empty($item['candidate_path'])):?><img class="product-image" src="<?=htmlspecialchars((string)$item['candidate_path'],ENT_QUOTES,'UTF-8')?>" alt=""><small><?=htmlspecialchars((string)$item['candidate_path'],ENT_QUOTES,'UTF-8')?></small><small><?=(int)($item['candidate_width']??0)?>×<?=(int)($item['candidate_height']??0)?> px</small><?php else:?><span class="muted">Nessuna candidata</span><?php endif;?></td>
<td><?php if((int)$item['protected']===1&&!$canRestore):?><div class="protected">Escluso dal censimento e dalla sostituzione.</div><?php else:?><?php if($canRestore):?><div class="protected">File mancante: è consentito solo il ripristino da Media Library.</div><?php endif;?>
<form class="review-form" method="post" action="/idemaclima/admin/product-images/save" enctype="multipart/form-data">
<input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="product_id" value="<?=(int)$item['product_id']?>">
<select name="review_status"><?php foreach(array_diff_key($labels,['approved'=>true]) as $key=>$label):?><option value="<?=$key?>" <?=$item['review_status']===$key?'selected':''?>><?=$label?></option><?php endforeach;?></select>
<input type="file" name="candidate_file" accept="image/png,image/webp">
<label>Media Library<input type="search" name="media_id" list="media-library-assets" inputmode="numeric" placeholder="Cerca o seleziona un’immagine"></label>
<div class="formgrid"><input name="source_catalog" value="<?=htmlspecialchars((string)($item['source_catalog']??''),ENT_QUOTES,'UTF-8')?>" placeholder="Catalogo"><input type="number" min="1" name="source_page" value="<?=htmlspecialchars((string)($item['source_page']??''),ENT_QUOTES,'UTF-8')?>" placeholder="Pagina"></div>
<textarea name="notes" placeholder="Note"><?=htmlspecialchars((string)($item['notes']??''),ENT_QUOTES,'UTF-8')?></textarea><button class="btn" type="submit">Salva revisione</button></form>
<?php if($item['review_status']!=='approved'&&!empty($item['candidate_path'])):?><div class="review-actions"><form method="post" action="/idemaclima/admin/product-images/approve" onsubmit="return confirm(this.replace_existing.checked?'ATTENZIONE: se esiste un file diverso con lo stesso nome verrà sostituito. Continuare?':'Approvare e assegnare questa immagine? La rinomina e la conversione saranno automatiche.')"><input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="product_id" value="<?=(int)$item['product_id']?>"><label class="check"><input type="checkbox" name="replace_existing" value="1"> Sostituisci il file esistente</label><button class="btn approve" type="submit">Approva e assegna</button></form></div><?php endif;?>
<?php if($item['review_status']!=='approved'&&!empty($item['candidate_path'])):?><div class="review-actions"><form method="post" action="/idemaclima/admin/product-images/remove-candidate" onsubmit="return confirm('Rimuovere questa immagine candidata? Il frontend non verrà modificato.')"><input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="product_id" value="<?=(int)$item['product_id']?>"><button class="danger" type="submit">Rimuovi immagine candidata</button></form></div><?php endif;?>
<?php if($item['review_status']==='approved'&&!empty($item['candidate_path'])):?><div class="review-actions"><form method="post" action="/idemaclima/admin/product-images/remove-assigned" onsubmit="return confirm('Eliminare la nuova immagine associata? Verrà ripristinata quella precedente, se disponibile.')"><input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="product_id" value="<?=(int)$item['product_id']?>"><button class="danger" type="submit">Rimuovi immagine assegnata</button></form></div><?php endif;?>
<?php endif;?></td></tr>
<?php endforeach;?></tbody></table></div><p class="empty" id="image-empty" hidden>Nessun prodotto corrisponde ai filtri.</p>
<script nonce="<?=htmlspecialchars(\App\Core\Security::nonce(),ENT_QUOTES,'UTF-8')?>">
(()=>{const q=document.getElementById('image-search'),s=document.getElementById('image-status'),m=document.getElementById('only-missing'),empty=document.getElementById('image-empty'),rows=[...document.querySelectorAll('#image-rows tr[data-search]')];
const apply=()=>{let visible=0;rows.forEach(row=>{const matchesText=!q.value||row.dataset.search.includes(q.value.toLowerCase());const matchesStatus=!s.value||row.dataset.status===s.value;const matchesMissing=!m.checked||row.dataset.missing==='1';const show=matchesText&&matchesStatus&&matchesMissing;row.hidden=!show;if(show)visible++;});empty.hidden=visible!==0;};
[q,s,m].forEach(control=>control&&control.addEventListener(control===q?'input':'change',apply));
document.querySelectorAll('[data-status-jump]').forEach(button=>button.addEventListener('click',()=>{s.value=button.dataset.statusJump;apply();q.focus();}));
document.querySelectorAll('.sort-button').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.sort;const direction=button.dataset.direction==='asc'?'desc':'asc';document.querySelectorAll('.sort-button').forEach(other=>{delete other.dataset.direction;other.removeAttribute('aria-sort');const mark=other.querySelector('[data-sort-marker]');if(mark)mark.textContent='↕';});button.dataset.direction=direction;button.setAttribute('aria-sort',direction==='asc'?'ascending':'descending');const mark=button.querySelector('[data-sort-marker]');if(mark)mark.textContent=direction==='asc'?'↑':'↓';const factor=direction==='asc'?1:-1;rows.sort((a,b)=>{const attr='sort'+key.charAt(0).toUpperCase()+key.slice(1);const av=a.dataset[attr]||'',bv=b.dataset[attr]||'';const result=(key==='current'||key==='candidate')?Number(av)-Number(bv):av.localeCompare(bv,'it',{numeric:true,sensitivity:'base'});return result*factor;});const body=document.getElementById('image-rows');rows.forEach(row=>body.appendChild(row));apply();}));
})();
</script>
<?php require __DIR__.'/_layout_end.php'; ?>
<?php /* Deployment sync: transparency controls. */ ?>
