<?php
$title='Schede tecniche — Gestione immagini prodotti';
$labels=['to_review'=>'Da verificare','insufficient'=>'Qualità insufficiente','recovered'=>'Recuperata dal catalogo','missing_catalog'=>'Catalogo mancante','approved'=>'Approvata'];
$lineCounts=[];
foreach($items as $imageItem){$line=trim((string)($imageItem['category_group']?:$imageItem['category_name']));if($line==='')$line='Altri Prodotti';$lineCounts[$line]=($lineCounts[$line]??0)+1;}
$lineOrder=['Linea Residenziale R32'=>0,'Linea Commerciale R32'=>1,'Linea VRF'=>2,'Linea Idronica'=>3,'Altri Prodotti'=>4];
uksort($lineCounts,static fn($a,$b)=>(($lineOrder[$a]??99)<=>($lineOrder[$b]??99))?:strnatcasecmp($a,$b));
require __DIR__.'/_layout_start.php';
?>
<style>
.image-summary{display:grid;grid-template-columns:repeat(5,minmax(130px,1fr));gap:12px;margin:0 0 22px}.image-summary button{width:100%;text-align:left;padding:14px;border:1px solid var(--line);border-radius:12px;background:#fff;color:inherit}.image-summary strong{display:block;font-size:24px}.image-tools{display:grid;grid-template-columns:minmax(240px,1fr) 240px auto;gap:12px;margin-bottom:18px}.image-table{min-width:1180px}.product-image{width:84px;height:84px;object-fit:contain;background:#f8fafc;border:1px solid var(--line);border-radius:8px}.image-cell small{display:block;max-width:190px;overflow-wrap:anywhere}.review-form{display:grid;gap:8px;min-width:270px}.review-form input,.review-form select,.review-form textarea{margin:0}.review-form textarea{min-height:68px}.review-actions{display:flex;gap:8px;flex-wrap:wrap}.review-actions form{margin:0}.review-actions .btn{padding:8px 10px;min-height:38px}.approve{background:#167647}.bulk-review-actions{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin:-6px 0 18px}.bulk-review-actions .btn{width:auto}.bulk-review-actions small{color:var(--muted)}.protected{padding:9px;border-radius:8px;background:#eef2f7;color:var(--muted);font-weight:700}.quality-low{color:#a13b10;font-weight:700}.bulk-import{margin:0 0 20px;padding:18px}.bulk-import>form:not(.transparency-audit-form){display:grid;grid-template-columns:minmax(260px,1fr) minmax(220px,1fr) auto;gap:12px;align-items:end}.transparency-audit-form{display:flex;justify-content:flex-end;margin-top:10px}.transparency-audit-form .btn{width:auto;min-height:32px;padding:6px 10px;font-size:12px;box-shadow:none}.sort-button{border:0;background:transparent;padding:0;color:inherit;font:inherit;font-weight:800;cursor:pointer}.sort-button::after{content:' ↕';color:var(--muted)}.sort-button[data-direction='asc']::after{content:' ↑'}.sort-button[data-direction='desc']::after{content:' ↓'}.image-jumps{display:flex;flex-wrap:wrap;gap:8px;margin:0 0 18px}.image-jumps button{padding:8px 12px;border:1px solid var(--line);border-radius:999px;background:#fff;color:var(--navy);font-weight:700;cursor:pointer}.image-jumps button:hover,.image-jumps button.is-active{border-color:var(--blue);color:var(--blue);background:#f3f7fa}.image-jumps .line-count{margin-left:5px;font-size:12px;opacity:.7}
@media(max-width:760px){.image-summary{grid-template-columns:1fr 1fr}.image-tools,.bulk-import>form:not(.transparency-audit-form){grid-template-columns:1fr}.transparency-audit-form{justify-content:flex-start}.transparency-audit-form .btn{min-height:36px}}

@media(max-width:1100px){
 .admin-modern main .table-wrap:has(>.image-table){overflow:visible;border:0;background:transparent}
 .admin-modern main .image-table{display:block;width:100%;min-width:0!important;table-layout:auto;background:transparent}
 .image-table thead{display:none}
 .image-table tbody{display:grid;gap:18px}
 .admin-modern main .image-table tbody tr:not([hidden]){display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);background:#fff;border:1px solid var(--line);border-radius:14px;overflow:hidden}
 .image-table tbody tr[hidden]{display:none!important}
 .admin-modern main .image-table tbody td{display:block;width:auto!important;min-width:0!important;padding:14px!important;white-space:normal!important;overflow-wrap:anywhere}
 .image-table tbody td:first-child,.image-table tbody td:last-child{grid-column:1/-1}
 .image-table .image-cell:before{display:block;margin-bottom:9px;color:var(--muted);font-size:12px;font-weight:700}
 .image-table .image-cell:nth-child(2):before{content:'Immagine attuale'}
 .image-table .image-cell:nth-child(3):before{content:'Candidata'}
 .image-table .product-image{width:100%;height:110px}
 .image-table .image-cell small{max-width:none;font-size:11px}
 .admin-modern .image-table .review-form{display:grid;grid-template-columns:minmax(0,1fr);min-width:0;width:100%;gap:12px;text-align:left}
 .admin-modern .image-table .review-form label{display:grid;grid-template-columns:minmax(0,1fr);gap:5px;white-space:normal;font-size:13px}
 .admin-modern .image-table .review-form input,.admin-modern .image-table .review-form select,.admin-modern .image-table .review-form textarea{min-width:0;width:100%;max-width:100%;margin:0;font-size:16px}
 .admin-modern .image-table .review-form input[type=file]{padding:8px;font-size:12px;overflow:hidden}
 .admin-modern .image-table .review-form .formgrid{grid-template-columns:minmax(0,1fr)!important;gap:12px}
 .admin-modern .image-table .review-form textarea{min-height:110px;resize:vertical}
 .admin-modern .image-table .review-actions,.admin-modern .image-table .media-picker-tools{display:grid;grid-template-columns:minmax(0,1fr);width:100%;gap:10px;margin-top:12px}
 .admin-modern .image-table .review-actions form{width:100%;min-width:0}
 .admin-modern .image-table .review-actions .check{display:flex;white-space:normal;margin-bottom:10px}
 .admin-modern .image-table .review-actions .check input{width:auto;flex:0 0 auto}
 .admin-modern main .image-table tbody td:last-child button{width:100%;min-height:44px!important;white-space:normal!important;text-align:center;line-height:1.4}
 .image-summary button,.image-jumps button,.bulk-review-actions button,.bulk-import button{white-space:normal!important}
 .bulk-review-actions .btn,.bulk-import button{width:100%!important}
}

/* Review fields use a vertical label/control flow at every viewport width. */
.admin-modern main .image-table{width:100%;min-width:0;table-layout:fixed}
.admin-modern main .image-table th:nth-child(1){width:24%}
.admin-modern main .image-table th:nth-child(2),.admin-modern main .image-table th:nth-child(3){width:16%}
.admin-modern main .image-table th:nth-child(4){width:44%}
.admin-modern main .image-table td:last-child{text-align:left;min-width:0!important}
.admin-modern main .image-table .review-form{display:grid;grid-template-columns:minmax(0,1fr);align-items:stretch!important;justify-content:normal!important;min-width:0;width:100%;gap:12px}
.admin-modern main .image-table .review-form label{display:grid;grid-template-columns:minmax(0,1fr);gap:5px;min-width:0;text-align:left;white-space:normal}
.admin-modern main .image-table .review-form :is(input,select,textarea){display:block;width:100%;min-width:0;max-width:100%;margin:0}
.admin-modern main .image-table .review-form input[type=file]{overflow:hidden;padding:9px;font-size:13px}
.admin-modern main .image-table .review-form .formgrid{display:grid;grid-template-columns:minmax(0,1fr) 90px;gap:12px;align-items:start}
.admin-modern main .image-table .review-form textarea{min-height:100px;resize:vertical}
.admin-modern main .image-table .review-form .media-picker-tools{display:flex;flex-wrap:wrap;justify-content:flex-start;gap:8px;margin:0}
.admin-modern main .image-table .review-form .media-picker-tools button{white-space:normal;text-align:left}
.admin-modern main .image-table .review-form>.btn{justify-self:start}
.admin-modern main .image-table .review-actions{justify-content:flex-start!important;align-items:stretch!important;margin-top:12px}
.admin-modern main .image-table .review-actions form{display:grid;justify-items:start;min-width:0;gap:8px}
.admin-modern main .image-table .review-actions .check{display:flex;align-items:center;gap:8px;text-align:left}
.admin-modern main .image-table .review-actions .check input{width:auto;flex:0 0 auto}
.admin-modern main .image-table td:last-child :is(button,a){white-space:normal!important;line-height:1.4!important}
@media(max-width:1100px){.admin-modern main .image-table .review-form .formgrid{grid-template-columns:minmax(0,1fr) 90px!important}.admin-modern main .image-table .review-form>.btn{justify-self:stretch}.admin-modern main .image-table .review-actions form{width:100%;justify-items:stretch}}
@media(max-width:480px){.admin-modern main .image-table .review-form .formgrid{grid-template-columns:minmax(0,1fr)!important}}
</style>
<div class="toolbar"><div><h1>Gestione immagini prodotti</h1><p class="muted">Confronta l’immagine attuale con quella recuperata dai cataloghi. Le nuove immagini trasparenti da 1000×1000 px vengono conservate nella loro risoluzione originale e associate al prodotto, in tutte le linee.</p></div></div>
<section class="panel bulk-import"><h2>Importazione multipla immagini candidate</h2><p class="muted">Sono accettate esclusivamente immagini PNG o WebP con sfondo realmente trasparente. Il nome del file viene confrontato con il modello del prodotto. Le immagini restano candidate e non modificano il frontend.</p><form method="post" action="/idemaclima/admin/product-images/bulk-import" enctype="multipart/form-data"><input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><label>Immagini candidate<input type="file" name="candidate_files[]" accept="image/png,image/webp" multiple required></label><label>Catalogo o sorgente<input name="source_catalog" value="" maxlength="190"></label><button class="btn" type="submit">Importa candidate</button></form><form class="transparency-audit-form" method="post" action="/idemaclima/admin/product-images/save" data-confirm="Verificare tutte le candidature esistenti e rimuovere quelle senza sfondo trasparente?"><input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="audit_transparency" value="1"><button class="btn danger" type="submit">Verifica trasparenza candidature esistenti</button></form></section>
<?php if($bulkImported||$bulkSkipped):?><div class="panel"><strong>Importazione completata:</strong> <?=(int)$bulkImported?> associazioni create o aggiornate; <?=(int)$bulkSkipped?> file scartati. Nessuna immagine è stata approvata o assegnata al frontend.<?php if($bulkErrors):?><details><summary>Dettagli file non importati</summary><ul><?php foreach($bulkErrors as $bulkError):?><li><?=htmlspecialchars((string)$bulkError,ENT_QUOTES,'UTF-8')?></li><?php endforeach;?></ul></details><?php endif;?></div><?php endif;?>
<?php if($saved):?><p class="panel">Revisione salvata senza modificare il frontend.</p><?php endif;?>
<?php if($approved):?><p class="panel">Immagine rinominata, approvata e assegnata al prodotto.</p><?php endif;?>
<?php if($candidateRemoved):?><p class="panel">L’immagine candidata è stata rimossa senza modificare il frontend.</p><?php endif;?>
<?php if($transparencyChecked):?><p class="panel">Controllo trasparenza completato: <?=(int)$transparencyChecked?> candidature verificate, <?=(int)$transparencyRemoved?> non conformi rimosse.</p><?php endif;?>
<?php if($removed):?><p class="panel">La nuova immagine è stata rimossa. È stata ripristinata quella precedente, quando disponibile.</p><?php endif;?>
<?php if($error!==''):?><p class="error"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></p><?php endif;?>
<div class="image-summary"><?php foreach($labels as $key=>$label):?><button type="button" data-status-jump="<?=$key?>"><strong><?=(int)($summary[$key]??0)?></strong><?=$label?></button><?php endforeach;?></div>
<div class="image-jumps" aria-label="Linee principali"><button type="button" class="is-active" data-line-jump="">Tutte le linee <span class="line-count"><?=(int)array_sum($lineCounts)?></span></button><?php foreach($lineCounts as $line=>$count):?><button type="button" data-line-jump="<?=htmlspecialchars(strtolower($line),ENT_QUOTES,'UTF-8')?>"><?=htmlspecialchars($line,ENT_QUOTES,'UTF-8')?> <span class="line-count"><?=(int)$count?></span></button><?php endforeach;?></div>
<div class="image-tools"><label>Cerca<input type="search" id="image-search" placeholder="Prodotto, serie o catalogo"></label><label>Stato<select id="image-status"><option value="">Tutti</option><?php foreach($labels as $key=>$label):?><option value="<?=$key?>"><?=$label?></option><?php endforeach;?></select></label><label class="check"><input type="checkbox" id="only-missing"> Solo immagini mancanti</label></div>
<div class="bulk-review-actions"><button class="btn approve" type="button" id="approve-visible">Approva e assegna tutte le candidature visibili (<span id="approve-visible-count">0</span>)</button><small>Sono escluse le immagini senza candidata, quelle già approvate e quelle con qualità insufficiente.</small></div>
<datalist id="media-library-assets"><?php foreach($media as $asset):?><option value="<?=(int)$asset['id']?>" label="<?=htmlspecialchars((string)$asset['title'],ENT_QUOTES,'UTF-8')?>"></option><?php endforeach;?></datalist>
<div class="table-wrap"><table class="image-table"><thead><tr><th><button type="button" class="sort-button" data-sort="product">Prodotto</button></th><th><button type="button" class="sort-button" data-sort="current">Immagine attuale</button></th><th><button type="button" class="sort-button" data-sort="candidate">Candidata</button></th><th><button type="button" class="sort-button" data-sort="status">Revisione e provenienza</button></th></tr></thead><tbody id="image-rows">
<?php foreach($items as $item):
  $hasCurrent=(string)($item['image_path']??'')!=='' && !empty($item['current_width']);
  $canRestore=(int)$item['protected']===1 && !$hasCurrent;
  $line=trim((string)($item['category_group']?:$item['category_name']));if($line==='')$line='Altri Prodotti';
  $search=strtolower(($item['category_group']??'').' '.($item['category_name']??'').' '.$item['name'].' '.($item['source_catalog']??''));
?>
<tr data-line="<?=htmlspecialchars(strtolower($line),ENT_QUOTES,'UTF-8')?>" data-search="<?=htmlspecialchars($search,ENT_QUOTES,'UTF-8')?>" data-status="<?=htmlspecialchars((string)$item['review_status'],ENT_QUOTES,'UTF-8')?>" data-missing="<?=$hasCurrent?'0':'1'?>" data-sort-product="<?=htmlspecialchars(strtolower((string)$item['name']),ENT_QUOTES,'UTF-8')?>" data-sort-current="<?=(int)($item['current_width']??0)*(int)($item['current_height']??0)?>" data-sort-candidate="<?=(int)($item['candidate_width']??0)*(int)($item['candidate_height']??0)?>" data-sort-status="<?=htmlspecialchars((string)$item['review_status'],ENT_QUOTES,'UTF-8')?>">
<td><strong><?=htmlspecialchars((string)$item['name'],ENT_QUOTES,'UTF-8')?></strong><br><small class="muted"><?=htmlspecialchars(trim(($item['category_group']??'').' · '.($item['category_name']??''),' ·'),ENT_QUOTES,'UTF-8')?></small><?php if((int)$item['protected']===1):?><br><span class="badge">Mono Split protetto</span><?php endif;?></td>
<td class="image-cell"><?php if($hasCurrent):?><img class="product-image" src="<?=htmlspecialchars((string)$item['image_path'],ENT_QUOTES,'UTF-8')?>" alt=""><small><?=htmlspecialchars((string)$item['image_path'],ENT_QUOTES,'UTF-8')?></small><small class="<?=($item['current_width']??0)<300?'quality-low':'muted'?>"><?php if($item['current_width']):?><?=(int)$item['current_width']?>×<?=(int)$item['current_height']?> px<?php else:?>Dimensioni non rilevate<?php endif;?></small><?php else:?><span class="quality-low">Mancante</span><?php endif;?></td>
<td class="image-cell"><?php if(!empty($item['candidate_path'])):?><img class="product-image" src="<?=htmlspecialchars((string)$item['candidate_path'],ENT_QUOTES,'UTF-8')?>" alt=""><small><?=htmlspecialchars((string)$item['candidate_path'],ENT_QUOTES,'UTF-8')?></small><small><?=(int)($item['candidate_width']??0)?>×<?=(int)($item['candidate_height']??0)?> px</small><?php else:?><span class="muted">Nessuna candidata</span><?php endif;?></td>
<td><?php if((int)$item['protected']===1&&!$canRestore):?><div class="protected">Escluso dal censimento e dalla sostituzione.</div><?php else:?><?php if($canRestore):?><div class="protected">File mancante: è consentito solo il ripristino da Media Library.</div><?php endif;?>
<form class="review-form" method="post" action="/idemaclima/admin/product-images/save" enctype="multipart/form-data">
<input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="product_id" value="<?=(int)$item['product_id']?>">
<label>Stato della revisione<select name="review_status"><?php foreach(array_diff_key($labels,['approved'=>true]) as $key=>$label):?><option value="<?=$key?>" <?=$item['review_status']===$key?'selected':''?>><?=$label?></option><?php endforeach;?></select></label>
<label>Carica immagine candidata<input type="file" name="candidate_file" accept="image/png,image/webp"></label>
<label>Media Library<input type="search" name="media_id" list="media-library-assets" inputmode="numeric" placeholder="Cerca o seleziona un’immagine"></label>
<div class="formgrid"><label>Catalogo o sorgente<input name="source_catalog" value="<?=htmlspecialchars((string)($item['source_catalog']??''),ENT_QUOTES,'UTF-8')?>" placeholder="Catalogo"></label><label>Pagina<input type="number" min="1" name="source_page" value="<?=htmlspecialchars((string)($item['source_page']??''),ENT_QUOTES,'UTF-8')?>" placeholder="Pagina"></label></div>
<label>Note<textarea name="notes" placeholder="Note"><?=htmlspecialchars((string)($item['notes']??''),ENT_QUOTES,'UTF-8')?></textarea></label><button class="btn" type="submit">Salva revisione</button></form>
<?php if($item['review_status']!=='approved'&&!empty($item['candidate_path'])):?><div class="review-actions"><form method="post" action="/idemaclima/admin/product-images/approve" onsubmit="return confirm(this.replace_existing.checked?'ATTENZIONE: se esiste un file diverso con lo stesso nome verrà sostituito. Continuare?':'Approvare e assegnare questa immagine? La nuova immagine da 1000×1000 px manterrà la risoluzione originale.')"><input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="product_id" value="<?=(int)$item['product_id']?>"><label class="check"><input type="checkbox" name="replace_existing" value="1"> Sostituisci il file esistente</label><button class="btn approve" type="submit">Approva e assegna</button></form></div><?php endif;?>
<?php if($item['review_status']!=='approved'&&!empty($item['candidate_path'])):?><div class="review-actions"><form method="post" action="/idemaclima/admin/product-images/remove-candidate" onsubmit="return confirm('Rimuovere questa immagine candidata? Il frontend non verrà modificato.')"><input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="product_id" value="<?=(int)$item['product_id']?>"><button class="danger" type="submit">Rimuovi immagine candidata</button></form></div><?php endif;?>
<?php if($item['review_status']==='approved'&&!empty($item['candidate_path'])):?><div class="review-actions"><form method="post" action="/idemaclima/admin/product-images/remove-assigned" onsubmit="return confirm('Eliminare la nuova immagine associata? Verrà ripristinata quella precedente, se disponibile.')"><input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="product_id" value="<?=(int)$item['product_id']?>"><button class="danger" type="submit">Rimuovi immagine assegnata</button></form></div><?php endif;?>
<?php endif;?></td></tr>
<?php endforeach;?></tbody></table></div><p class="empty" id="image-empty" hidden>Nessun prodotto corrisponde ai filtri.</p>
<script nonce="<?=htmlspecialchars(\App\Core\Security::nonce(),ENT_QUOTES,'UTF-8')?>">
(()=>{const q=document.getElementById('image-search'),s=document.getElementById('image-status'),m=document.getElementById('only-missing'),empty=document.getElementById('image-empty'),rows=[...document.querySelectorAll('#image-rows tr[data-search]')],lineButtons=[...document.querySelectorAll('[data-line-jump]')],approveVisible=document.getElementById('approve-visible'),approveCount=document.getElementById('approve-visible-count');let activeLine='';
const eligibleRows=()=>rows.filter(row=>!row.hidden&&row.dataset.status!=='insufficient'&&row.querySelector('form[action$="/approve"]'));
const updateBulkCount=()=>{const count=eligibleRows().length;if(approveCount)approveCount.textContent=String(count);if(approveVisible)approveVisible.disabled=count===0;};
const apply=()=>{let visible=0;rows.forEach(row=>{const matchesText=!q.value||row.dataset.search.includes(q.value.toLowerCase());const matchesStatus=!s.value||row.dataset.status===s.value;const matchesMissing=!m.checked||row.dataset.missing==='1';const matchesLine=!activeLine||row.dataset.line===activeLine;const show=matchesText&&matchesStatus&&matchesMissing&&matchesLine;row.hidden=!show;if(show)visible++;});empty.hidden=visible!==0;updateBulkCount();};
[q,s,m].forEach(control=>control&&control.addEventListener(control===q?'input':'change',apply));
lineButtons.forEach(button=>button.addEventListener('click',()=>{activeLine=button.dataset.lineJump||'';lineButtons.forEach(other=>other.classList.toggle('is-active',other===button));apply();const first=rows.find(row=>!row.hidden);if(first)first.scrollIntoView({behavior:'smooth',block:'center'});}));
document.querySelectorAll('[data-status-jump]').forEach(button=>button.addEventListener('click',()=>{s.value=button.dataset.statusJump;apply();q.focus();}));
approveVisible&&approveVisible.addEventListener('click',async()=>{const candidates=eligibleRows();if(!candidates.length)return;const total=candidates.length;if(!confirm('Approvare e assegnare '+total+' candidature visibili? Saranno escluse le righe insufficienti, senza candidata o già approvate.'))return;approveVisible.disabled=true;approveVisible.textContent='Approvazione in corso…';let completed=0;try{for(const row of candidates){const form=row.querySelector('form[action$="/approve"]');if(!form)continue;const response=await fetch(form.action,{method:'POST',body:new FormData(form),credentials:'same-origin'});if(!response.ok)throw new Error('Errore HTTP '+response.status);completed++;}window.location.assign('/idemaclima/admin/product-images?approved='+completed);}catch(error){alert('Operazione interrotta dopo '+completed+' approvazioni: '+error.message);window.location.reload();}});
document.querySelectorAll('.sort-button').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.sort;const direction=button.dataset.direction==='asc'?'desc':'asc';document.querySelectorAll('.sort-button').forEach(other=>{delete other.dataset.direction;other.removeAttribute('aria-sort');const mark=other.querySelector('[data-sort-marker]');if(mark)mark.textContent='↕';});button.dataset.direction=direction;button.setAttribute('aria-sort',direction==='asc'?'ascending':'descending');const mark=button.querySelector('[data-sort-marker]');if(mark)mark.textContent=direction==='asc'?'↑':'↓';const factor=direction==='asc'?1:-1;rows.sort((a,b)=>{const attr='sort'+key.charAt(0).toUpperCase()+key.slice(1);const av=a.dataset[attr]||'',bv=b.dataset[attr]||'';const result=(key==='current'||key==='candidate')?Number(av)-Number(bv):av.localeCompare(bv,'it',{numeric:true,sensitivity:'base'});return result*factor;});const body=document.getElementById('image-rows');rows.forEach(row=>body.appendChild(row));apply();}));
apply();
})();
</script>
<?php require __DIR__.'/_layout_end.php'; ?>
<?php /* Deployment sync: transparency controls. */ ?>