<?php
$title='Schede tecniche — Prodotti e modelli';
$tree=[];
$productLabel=static fn(int $count):string=>$count===1?'prodotto':'prodotti';
$modelLabel=static fn(int $count):string=>$count===1?'modello':'modelli';
$documentLabel=static fn(int $count):string=>$count===1?'PDF':'PDF';
foreach($products as $p){
    $group=(string)($p['category_group']?:$p['category_name']);
    $series=(string)($p['category_group']?$p['category_name']:'Prodotti');
    $tree[$group][$series][]=$p;
}
$lineOrder=['Linea Residenziale R32'=>0,'Linea Commerciale R32'=>1,'Linea VRF'=>2,'Linea Idronica'=>3,'Altri Prodotti'=>4];
$seriesOrder=['Mono Split'=>0,'Multi Split'=>1,'Multi Pro'=>2,'Accessori'=>3];
uksort($tree,static fn($a,$b)=>($lineOrder[$a]??99)<=>($lineOrder[$b]??99));
foreach($tree as &$seriesList)uksort($seriesList,static fn($a,$b)=>($seriesOrder[$a]??99)<=>($seriesOrder[$b]??99));unset($seriesList);
require __DIR__.'/_layout_start.php';
?>
<style>
.technical-admin-nav{display:flex;flex-wrap:wrap;gap:9px;margin:0 0 20px}.technical-admin-nav a{padding:9px 12px;border:1px solid var(--line);border-radius:9px;background:#fff;color:var(--navy);font-weight:700;text-decoration:none}.technical-admin-nav a:hover,.technical-admin-nav a.is-active{border-color:var(--blue);color:var(--blue);background:#f3f7fa}.product-search{max-width:560px;margin:0 0 12px}.product-jumps{display:flex;flex-wrap:wrap;gap:8px;margin:0 0 22px}.product-jumps button{padding:8px 12px;border:1px solid var(--line);border-radius:999px;background:#fff;color:var(--navy);font-weight:700}.product-jumps button:hover{border-color:var(--blue);color:var(--blue)}.product-tree{display:grid;gap:18px}.product-group,.product-series{border:1px solid var(--line);border-radius:14px;background:#fff;overflow:hidden}.product-group>summary,.product-series>summary{cursor:pointer;list-style:none}.product-group>summary::-webkit-details-marker,.product-series>summary::-webkit-details-marker{display:none}.product-group>summary{display:flex;justify-content:space-between;gap:16px;padding:18px 20px;background:var(--navy);color:#fff;font-size:18px;font-weight:800}.product-series{margin:14px}.product-series>summary{display:flex;justify-content:space-between;gap:14px;padding:14px 16px;background:#f3f7fa;font-weight:750}.tree-count{font-size:12px;font-weight:700;opacity:.75}.product-list{display:grid}.product-row{display:grid;grid-template-columns:minmax(220px,1.4fr) minmax(110px,.55fr) 90px 110px auto;gap:16px;align-items:center;padding:14px 16px;border-top:1px solid var(--line)}.product-name strong{display:block}.product-name small{display:block;color:var(--muted);overflow-wrap:anywhere}.product-actions{display:flex;gap:11px;align-items:center}.product-actions form{margin:0}.linkbutton{border:0;padding:0;background:transparent;color:var(--blue);font-weight:650;text-decoration:underline}.product-empty{display:none;padding:26px;text-align:center;color:var(--muted);background:#fff}
@media(max-width:820px){.product-row{grid-template-columns:minmax(0,1fr) auto}.product-role,.product-models{display:none}.product-status{text-align:right}.product-actions{grid-column:1/-1}.product-group>summary{font-size:16px;padding:16px}.product-series>summary{padding:13px}}
</style>
<div class="toolbar"><div><h1>Schede tecniche</h1><p class="muted">Gestione gerarchica per categoria, serie e prodotto.</p></div><a class="btnlink" href="/idemaclima/admin/products/form">Nuovo prodotto</a></div>\n<nav class="technical-admin-nav" aria-label="Gestione schede tecniche"><a href="/idemaclima/admin/categories">Categorie e serie</a><a class="is-active" href="/idemaclima/admin/products">Prodotti e modelli</a><a href="/idemaclima/admin/products/inventory">Riepilogo prodotti e documenti</a><a href="/idemaclima/admin/product-images">Gestione immagini prodotti</a><a href="/idemaclima/admin/documents">Documenti PDF</a><a href="/idemaclima/admin/mono-split-import">Importa pagina Mono Split</a></nav>
<label class="product-search">Cerca prodotto, modello o serie<input type="search" id="product-filter" placeholder="Es. ISPT, Multi Split, R32"></label><div class="product-jumps" aria-label="Linee principali"><?php foreach(array_slice(array_keys($tree),0,5) as $group):?><button type="button" data-jump="<?=htmlspecialchars(strtolower($group),ENT_QUOTES,'UTF-8')?>"><?=htmlspecialchars($group,ENT_QUOTES,'UTF-8')?></button><?php endforeach;?></div>
<div class="product-tree" id="product-tree">
<?php foreach($tree as $group=>$seriesList): $groupCount=array_sum(array_map('count',$seriesList)); ?>
<details class="product-group"><summary><span><?= htmlspecialchars($group,ENT_QUOTES,'UTF-8') ?></span><span class="tree-count"><?= $groupCount ?> <?= $productLabel($groupCount) ?></span></summary>
<?php foreach($seriesList as $series=>$items): ?>
<details class="product-series"><summary><span><?= htmlspecialchars($series,ENT_QUOTES,'UTF-8') ?></span><span class="tree-count"><?= count($items) ?></span></summary><div class="product-list">
<?php foreach($items as $p): ?><article class="product-row" data-search="<?= htmlspecialchars(strtolower($group.' '.$series.' '.$p['name'].' '.$p['slug'].' '.$p['product_role']),ENT_QUOTES,'UTF-8') ?>"><div class="product-name"><strong><?= htmlspecialchars($p['name'],ENT_QUOTES,'UTF-8') ?></strong><small><?= htmlspecialchars($p['slug'],ENT_QUOTES,'UTF-8') ?></small></div><div class="product-role"><?= htmlspecialchars($p['product_role'],ENT_QUOTES,'UTF-8') ?></div><div class="product-models"><?= (int)$p['model_count'] ?> <?= $modelLabel((int)$p['model_count']) ?><br><span class="muted"><?= (int)$p['document_count'] ?> <?= $documentLabel((int)$p['document_count']) ?></span></div><div class="product-status"><span class="badge"><?= htmlspecialchars(['draft'=>'Bozza','published'=>'Pubblicato','hidden'=>'Nascosto'][$p['content_status']??'']??($p['published']?'Pubblicato':'Nascosto'),ENT_QUOTES,'UTF-8') ?></span></div><div class="product-actions"><a href="/idemaclima/admin/products/form?id=<?= (int)$p['id'] ?>">Modifica</a><form method="post" action="/idemaclima/admin/products/duplicate"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="id" value="<?= (int)$p['id'] ?>"><button class="linkbutton" type="submit">Duplica</button></form></div></article><?php endforeach; ?>
</div></details><?php endforeach; ?></details><?php endforeach; ?>
</div><div class="product-empty" id="product-empty">Nessun prodotto corrisponde alla ricerca.</div>
<script nonce="<?= htmlspecialchars(\App\Core\Security::nonce(),ENT_QUOTES,'UTF-8') ?>">(()=>{const input=document.getElementById('product-filter'),tree=document.getElementById('product-tree'),empty=document.getElementById('product-empty');if(!input||!tree)return;tree.querySelectorAll('.product-group,.product-series').forEach(section=>section.open=false);tree.querySelectorAll('[data-jump]').forEach(()=>{});document.querySelectorAll('[data-jump]').forEach(button=>button.addEventListener('click',()=>{input.value=button.dataset.jump;input.dispatchEvent(new Event('input'));const visible=tree.querySelector('.product-group:not([hidden])');if(visible)visible.scrollIntoView({behavior:'smooth',block:'start'})}));input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();let total=0;tree.querySelectorAll('.product-series').forEach(series=>{let count=0;series.querySelectorAll('.product-row').forEach(row=>{const show=!q||row.dataset.search.includes(q);row.hidden=!show;if(show)count++});series.hidden=count===0;if(q&&count)series.open=true;total+=count});tree.querySelectorAll('.product-group').forEach(group=>{const show=[...group.querySelectorAll('.product-series')].some(series=>!series.hidden);group.hidden=!show;if(q&&show)group.open=true});empty.style.display=total?'none':'block'})})();</script>
<?php require __DIR__.'/_layout_end.php'; ?>
