<section class="hero"><div class="wrap"><div class="crumbs">Home / Campus / <?= e($event['title']) ?></div><h1><?= e($event['title']) ?></h1><p><?= e($event['short_description'] ?? '') ?></p></div></section>
<section class="content"><div class="wrap"><div class="panel">
<p><strong>Data:</strong> <?= e(date('d/m/Y H:i',strtotime((string)$event['starts_at']))) ?></p>
<?php if(!empty($event['ends_at'])):?><p><strong>Fine:</strong> <?= e(date('d/m/Y H:i',strtotime((string)$event['ends_at']))) ?></p><?php endif; ?>
<?php if(!empty($event['location'])):?><p><strong>Luogo:</strong> <?= e($event['location']) ?><?= !empty($event['address'])?' - '.e($event['address']):'' ?></p><?php endif; ?>
<?php if(!empty($event['description'])):?><div><?= nl2br(e($event['description'])) ?></div><?php endif; ?>
</div>
<?php $deadlineOk=empty($event['registration_deadline'])||strtotime((string)$event['registration_deadline'])>=time(); $open=(int)$event['registration_open']===1 && !(int)$event['cancelled'] && $deadlineOk; ?>
<?php if($open): ?><div class="panel" style="margin-top:24px"><h2>Iscriviti</h2><form method="post" action="<?= $event['audience']==='cat'?'/campus/cat/':'/campus/' ?><?= e($event['slug']) ?>/iscrizione"><input type="hidden" name="_csrf" value="<?= e($csrf) ?>"><div class="formgrid"><label>Nome<input name="first_name" required value="<?= e($catUser['contact_first_name']??'') ?>"></label><label>Cognome<input name="last_name" required value="<?= e($catUser['contact_last_name']??'') ?>"></label><label>Email<input type="email" name="email" required value="<?= e($catUser['email']??'') ?>"></label><label>Telefono<input name="phone" value="<?= e($catUser['phone']??'') ?>"></label><label>Azienda<input name="company" value="<?= e($catUser['company_name']??'') ?>"></label><label>Ruolo<input name="role"></label><label class="full">Note<textarea name="notes"></textarea></label><label class="full check"><input type="checkbox" name="privacy" value="1" required> Accetto l’informativa privacy</label></div><button class="btn" type="submit" style="margin-top:16px">Invia iscrizione</button></form></div><?php else:?><p style="margin-top:24px"><strong>Iscrizioni chiuse.</strong></p><?php endif; ?>
</div></section>
