<style>
/* I filtri prossimi, passati e annullati sono disponibili nella pagina Eventi aperti. */
.campus-lead{padding:64px 0}.campus-split{display:grid;grid-template-columns:1.05fr .95fr;gap:44px;align-items:center}.campus-split img{display:block;width:100%;min-height:390px;object-fit:cover;border-radius:28px}.campus-copy p,.campus-section p,.campus-benefit p{color:var(--muted-foreground);line-height:1.75}.campus-copy h2,.campus-section h2{font-size:clamp(30px,4vw,46px)}.campus-section{padding:72px 0}.campus-section.soft{background:var(--muted)}.campus-benefits{display:grid;grid-template-columns:repeat(5,1fr);gap:14px;margin-top:34px}.campus-benefit{padding:23px;border:1px solid var(--border);border-radius:20px;background:#fff}.campus-benefit strong{font-family:Sora}.campus-benefit p{font-size:13px}.campus-audience{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:34px}.campus-path{padding:31px;border:1px solid var(--border);border-radius:25px;background:#fff}.campus-path.cat{background:var(--gradient-dark);color:#fff}.campus-path.cat p{color:rgba(255,255,255,.72)}.campus-path .btn{margin-top:10px}@media(max-width:900px){.campus-split{grid-template-columns:1fr}.campus-benefits{grid-template-columns:repeat(2,1fr)}}@media(max-width:620px){.campus-benefits,.campus-audience{grid-template-columns:1fr}.campus-lead,.campus-section{padding:48px 0}.campus-split img{min-height:250px}}
</style>
<section class="hero"><div class="wrap"><span class="section-label">Formazione e aggiornamento</span><h1>IDEMA Campus</h1><p>Formazione per professionisti del settore della climatizzazione e del riscaldamento.</p></div></section>
<section class="campus-lead"><div class="wrap campus-split"><div class="campus-copy"><span class="section-label">Benvenuti in IDEMA Campus</span><h2>Competenze concrete per affrontare le sfide del settore.</h2><p>IDEMA CAMPUS è il programma di formazione esclusivo dedicato a installatori qualificati, centri assistenza e progettisti. Il nostro obiettivo è fornire le competenze e le conoscenze necessarie per affrontare le sfide della climatizzazione e del riscaldamento, specialmente nell’ambito delle pompe di calore.</p></div><img src="https://www.idemaclima.it/wp-content/uploads/idema-campus.jpg" alt="Formazione IDEMA Campus"></div></section>
<section class="campus-section soft"><div class="wrap campus-split"><img src="https://www.idemaclima.it/wp-content/uploads/yootheme/cache/6e/foto2-6e292628.png" alt="Moduli formativi IDEMA Campus" loading="lazy"><div class="campus-copy"><span class="section-label">I moduli formativi</span><h2>Teoria, normativa e applicazioni pratiche.</h2><p>IDEMA CAMPUS offre moduli progettati sulle esigenze dei professionisti. I partecipanti approfondiscono normative aggiornate, regolamentazioni e migliori pratiche del settore.</p><p>I corsi dedicati alle pompe di calore affrontano i sistemi integrati, le tecnologie di controllo avanzate, la gestione dell’energia e le strategie smart grid, con l’obiettivo di ottimizzare efficienza e prestazioni complessive degli impianti.</p></div></div></section>
<section class="campus-section"><div class="wrap"><span class="section-label">Le nostre sedi</span><h2>Formazione nella sede IDEMA e in sedi itineranti.</h2><p>I corsi si tengono sia presso IDEMA®, dove è possibile osservare le unità in funzione e sperimentare direttamente con i sistemi, sia in sedi itineranti. Una formula flessibile che garantisce formazione pratica, concreta e vicina ai professionisti.</p><div class="campus-benefits"><?php foreach([['Formazione specializzata','Tecnologie recenti e normative vigenti.'],['Approccio pratico','Esperienza diretta e utilizzo dei prodotti.'],['Esperti del settore','Formatori qualificati con esperienza concreta.'],['Networking efficace','Confronto con altri professionisti e nuove collaborazioni.'],['Certificazioni riconosciute','Attestazioni delle competenze acquisite.']] as $item):?><article class="campus-benefit"><strong><?=e($item[0])?></strong><p><?=e($item[1])?></p></article><?php endforeach;?></div></div></section>
<section class="campus-section soft"><div class="wrap"><span class="section-label">A chi è rivolto</span><h2>Scegli il percorso adatto alla tua attività.</h2><div class="campus-audience"><article class="campus-path"><span class="section-label">Installatori e progettisti</span><h3>Eventi aperti</h3><p>Corsi su sistemi idronici, pompe di calore, normative, R290 e integrazione efficiente nei sistemi complessi, con contenuti teorici e pratici.</p><a class="btn" href="/idemaclima/campus/eventi-aperti">Consulta gli eventi aperti</a></article><article class="campus-path cat"><span class="section-label">Centri Assistenza Tecnica</span><h3>Eventi CAT</h3><p>Formazione riservata ai CAT registrati su manutenzione, riparazione, diagnostica e ottimizzazione delle prestazioni degli impianti.</p><a class="btn" href="/idemaclima/campus/cat">Accedi agli eventi CAT</a></article></div></div></section>
