<?php

declare(strict_types=1);

require dirname(__DIR__) . '/scripts/bootstrap.php';

use App\Controllers\Admin\AuthController;
use App\Controllers\Admin\DashboardController;
use App\Controllers\Admin\CategoriesController;
use App\Controllers\Admin\DocumentsController;
use App\Controllers\Admin\ProductsController;
use App\Controllers\Admin\WarrantyController as AdminWarrantyController;
use App\Controllers\Admin\CampusController as AdminCampusController;
use App\Controllers\Admin\CampusActionsController as AdminCampusActionsController;
use App\Controllers\Admin\ContentController as AdminContentController;
use App\Controllers\Admin\GalleryContentController as AdminGalleryContentController;
use App\Controllers\Admin\CatalogsController as AdminCatalogsController;
use App\Controllers\Admin\CatalogImportController;
use App\Controllers\Admin\ReferenceImportController;
use App\Controllers\Admin\ContactsAnalyticsController as AdminContactsAnalyticsController;
use App\Controllers\Admin\RedirectsController;
use App\Controllers\Admin\AssistanceController as AdminAssistanceController;
use App\Controllers\Admin\EditorialController as AdminEditorialController;
use App\Controllers\Admin\IncentivesController as AdminIncentivesController;
use App\Controllers\Admin\SettingsController as AdminSettingsController;
use App\Controllers\Public\TechnicalSheetsController;
use App\Controllers\Public\WarrantyController;
use App\Controllers\Public\CampusController;
use App\Controllers\Public\CatAuthController;
use App\Controllers\Public\ContentController;
use App\Controllers\Public\ContactController;
use App\Controllers\Public\AnalyticsController;
use App\Controllers\Public\SystemController;
use App\Controllers\Public\AssistanceController;
use App\Controllers\Public\EditorialController;
use App\Controllers\Public\IncentivesController;
use App\Controllers\Public\SeoController;
use App\Core\Router;

$router = new Router();
$router->get('/', static function (): void {
    $title = 'IDEMA CLIMA® — Climatizzatori e pompe di calore ad alta efficienza';
    require dirname(__DIR__) . '/app/Views/public/home.php';
});
$router->get('/health', static function (): void { header('Content-Type: application/json; charset=UTF-8'); echo json_encode(['ok'=>true],JSON_THROW_ON_ERROR); });
$router->get('/sitemap.xml', [SeoController::class, 'sitemap']);
$router->get('/robots.txt', [SeoController::class, 'robots']);

$router->get('/schede-tecniche', [TechnicalSheetsController::class, 'index']);
$router->get('/schede-tecniche/ricerca', [TechnicalSheetsController::class, 'search']);
$router->get('/schede-tecniche/dichiarazioni-conformita-ce', static fn() => EditorialController::page('schede-tecniche/dichiarazioni-conformita-ce'));
$router->get('/schede-tecniche/famiglia/{slug}', [TechnicalSheetsController::class, 'family']);
$router->get('/schede-tecniche/prodotto/{slug}', [TechnicalSheetsController::class, 'product']);
$router->get('/schede-tecniche/{slug}', [TechnicalSheetsController::class, 'category']);
$router->get('/documento/{id}/download', [AnalyticsController::class, 'documentDownload']);
$router->get('/cataloghi', [ContentController::class, 'catalogs']);
$router->get('/assistenza', [AssistanceController::class, 'index']);
$router->get('/faq', static fn() => EditorialController::page('faq'));
$router->get('/configurazione-wi-fi', static fn() => EditorialController::page('configurazione-wi-fi'));
$router->get('/detrazioni-e-incentivi', static fn() => EditorialController::page('detrazioni-e-incentivi'));
$router->get('/detrazioni-e-incentivi/bonus-casa', static fn() => EditorialController::page('detrazioni-e-incentivi'));
$router->get('/detrazioni-e-incentivi/ecobonus', static fn() => EditorialController::page('detrazioni-e-incentivi'));
$router->get('/detrazioni-e-incentivi/conto-termico', static fn() => EditorialController::page('detrazioni-e-incentivi'));
$router->get('/detrazioni-e-incentivi/consulenza-energetica', static fn() => EditorialController::page('detrazioni-e-incentivi'));
$router->post('/detrazioni-e-incentivi/consulenza-energetica', [IncentivesController::class, 'submit']);
$router->get('/galleria', [ContentController::class, 'gallery']);
$router->get('/galleria/{slug}', [ContentController::class, 'galleryAlbum']);
$router->get('/referenze', [ContentController::class, 'references']);
$router->get('/referenze/{slug}', [ContentController::class, 'reference']);
$router->get('/contatti', [ContactController::class, 'form']);
$router->post('/contatti', [ContactController::class, 'submit']);
$router->get('/garanzia', [WarrantyController::class, 'form']);
$router->post('/garanzia', [WarrantyController::class, 'register']);

$router->get('/campus', [CampusController::class, 'index']);
$router->get('/campus/cat/login', [CatAuthController::class, 'loginForm']);
$router->post('/campus/cat/login', [CatAuthController::class, 'login']);
$router->get('/campus/cat/registrazione', [CatAuthController::class, 'registerForm']);
$router->post('/campus/cat/registrazione', [CatAuthController::class, 'register']);
$router->post('/campus/cat/logout', [CatAuthController::class, 'logout']);
$router->get('/campus/cat', [CampusController::class, 'catIndex']);
$router->get('/campus/cat/{slug}', [CampusController::class, 'catEvent']);
$router->post('/campus/cat/{slug}/iscrizione', [CampusController::class, 'register']);
$router->get('/campus/{slug}', [CampusController::class, 'event']);
$router->post('/campus/{slug}/iscrizione', [CampusController::class, 'register']);

$router->get('/admin/login', [AuthController::class, 'loginForm']);
$router->post('/admin/login', [AuthController::class, 'login']);
$router->post('/admin/logout', [AuthController::class, 'logout']);
$router->get('/admin', [DashboardController::class, 'index']);
$router->get('/admin/catalog-import', [CatalogImportController::class, 'index']);
$router->post('/admin/catalog-import/run', [CatalogImportController::class, 'run']);
$router->get('/admin/reference-import', [ReferenceImportController::class, 'index']);
$router->post('/admin/reference-import/run', [ReferenceImportController::class, 'run']);
$router->get('/admin/categories', [CategoriesController::class, 'index']);
$router->get('/admin/categories/form', [CategoriesController::class, 'form']);
$router->post('/admin/categories/save', [CategoriesController::class, 'save']);
$router->get('/admin/products', [ProductsController::class, 'index']);
$router->get('/admin/products/form', [ProductsController::class, 'form']);
$router->post('/admin/products/save', [ProductsController::class, 'save']);
$router->post('/admin/products/duplicate', [ProductsController::class, 'duplicate']);
$router->post('/admin/products/delete', [ProductsController::class, 'delete']);
$router->post('/admin/models/save', [ProductsController::class, 'saveModel']);
$router->get('/admin/documents', [DocumentsController::class, 'index']);
$router->get('/admin/documents/form', [DocumentsController::class, 'form']);
$router->post('/admin/documents/save', [DocumentsController::class, 'save']);
$router->get('/admin/warranties', [AdminWarrantyController::class, 'registrations']);
$router->get('/admin/warranties/registration', [AdminWarrantyController::class, 'registration']);
$router->post('/admin/warranties/status', [AdminWarrantyController::class, 'updateStatus']);
$router->post('/admin/warranties/update', [AdminWarrantyController::class, 'updateRegistration']);
$router->post('/admin/warranties/delete', [AdminWarrantyController::class, 'deleteRegistration']);
$router->post('/admin/warranties/certificate/generate', [AdminWarrantyController::class, 'generateCertificate']);
$router->get('/admin/warranties/certificate/{id}', [AdminWarrantyController::class, 'certificateFile']);
$router->post('/admin/warranties/certificate/send', [AdminWarrantyController::class, 'sendCertificate']);
$router->get('/admin/warranties/certificate-layout', [AdminWarrantyController::class, 'certificateLayoutEditor']);
$router->post('/admin/warranties/certificate-layout/save', [AdminWarrantyController::class, 'saveCertificateLayout']);
$router->post('/admin/warranties/certificate-layout/reset', [AdminWarrantyController::class, 'resetCertificateLayout']);
$router->get('/admin/warranties/certificate-layout/preview', [AdminWarrantyController::class, 'certificateLayoutPreview']);
$router->get('/admin/warranties/rules', [AdminWarrantyController::class, 'rules']);
$router->get('/admin/warranties/rules/form', [AdminWarrantyController::class, 'ruleForm']);
$router->post('/admin/warranties/rules/save', [AdminWarrantyController::class, 'saveRule']);
$router->get('/admin/warranties/file/{kind}/{id}', [AdminWarrantyController::class, 'privateFile']);
$router->get('/admin/assistance', [AdminAssistanceController::class, 'index']);
$router->get('/admin/assistance/form', [AdminAssistanceController::class, 'form']);
$router->post('/admin/assistance/save', [AdminAssistanceController::class, 'save']);
$router->post('/admin/assistance/archive', [AdminAssistanceController::class, 'archive']);
$router->get('/admin/editorial', [AdminEditorialController::class, 'index']);
$router->get('/admin/editorial/form', [AdminEditorialController::class, 'form']);
$router->post('/admin/editorial/save', [AdminEditorialController::class, 'savePage']);
$router->post('/admin/editorial/section', [AdminEditorialController::class, 'addSection']);
$router->post('/admin/editorial/section/save', [AdminEditorialController::class, 'saveSection']);
$router->post('/admin/editorial/section/delete', [AdminEditorialController::class, 'deleteSection']);
$router->post('/admin/editorial/faq', [AdminEditorialController::class, 'addFaq']);
$router->post('/admin/editorial/faq/save', [AdminEditorialController::class, 'saveFaq']);
$router->post('/admin/editorial/faq/delete', [AdminEditorialController::class, 'deleteFaq']);
$router->post('/admin/editorial/document', [AdminEditorialController::class, 'addDocument']);
$router->post('/admin/editorial/document/delete', [AdminEditorialController::class, 'deleteDocument']);
$router->get('/admin/incentives', [AdminIncentivesController::class, 'requests']);
$router->get('/admin/incentives/request', [AdminIncentivesController::class, 'request']);
$router->post('/admin/incentives/update', [AdminIncentivesController::class, 'update']);
$router->get('/admin/campus/events', [AdminCampusController::class, 'events']);
$router->get('/admin/campus/events/form', [AdminCampusController::class, 'eventForm']);
$router->post('/admin/campus/events/save', [AdminCampusController::class, 'saveEvent']);
$router->post('/admin/campus/events/duplicate', [AdminCampusActionsController::class, 'duplicate']);
$router->get('/admin/campus/registrations', [AdminCampusController::class, 'registrations']);
$router->get('/admin/campus/registrations/export', [AdminCampusActionsController::class, 'export']);
$router->post('/admin/campus/registrations/update', [AdminCampusController::class, 'updateRegistration']);
$router->get('/admin/cat/users', [AdminCampusController::class, 'catUsers']);
$router->get('/admin/cat/users/form', [AdminCampusController::class, 'catUserForm']);
$router->post('/admin/cat/users/save', [AdminCampusController::class, 'saveCatUser']);
$router->post('/admin/cat/users/status', [AdminCampusActionsController::class, 'updateCatStatus']);
$router->get('/admin/content/catalogs', [AdminCatalogsController::class, 'index']);
$router->get('/admin/content/catalogs/form', [AdminCatalogsController::class, 'form']);
$router->post('/admin/content/catalogs/save', [AdminCatalogsController::class, 'save']);
$router->post('/admin/content/catalogs/duplicate', [AdminCatalogsController::class, 'duplicate']);
$router->get('/admin/content/gallery', [AdminContentController::class, 'albums']);
$router->get('/admin/content/gallery/form', [AdminContentController::class, 'albumForm']);
$router->post('/admin/content/gallery/save', [AdminContentController::class, 'saveAlbum']);
$router->post('/admin/content/gallery/archive', [AdminContentController::class, 'archiveAlbum']);
$router->post('/admin/content/gallery/image', [AdminContentController::class, 'addGalleryImage']);
$router->post('/admin/content/gallery/image/update', [AdminContentController::class, 'updateGalleryImage']);
$router->post('/admin/content/gallery/image/delete', [AdminContentController::class, 'deleteGalleryImage']);
$router->get('/admin/content/gallery/manage', [AdminGalleryContentController::class, 'index']);
$router->post('/admin/content/gallery/section/save', [AdminGalleryContentController::class, 'saveSection']);
$router->post('/admin/content/gallery/item/save', [AdminGalleryContentController::class, 'saveItem']);
$router->post('/admin/content/gallery/item/delete', [AdminGalleryContentController::class, 'deleteItem']);
$router->get('/admin/content/references', [AdminContentController::class, 'references']);
$router->get('/admin/content/references/form', [AdminContentController::class, 'referenceForm']);
$router->post('/admin/content/references/save', [AdminContentController::class, 'saveReference']);
$router->post('/admin/content/references/archive', [AdminContentController::class, 'archiveReference']);
$router->post('/admin/content/references/duplicate', [AdminContentController::class, 'duplicateReference']);
$router->post('/admin/content/references/image', [AdminContentController::class, 'addReferenceImage']);
$router->post('/admin/content/references/image/update', [AdminContentController::class, 'updateReferenceImage']);
$router->post('/admin/content/references/image/delete', [AdminContentController::class, 'deleteReferenceImage']);
$router->get('/admin/contacts', [AdminContactsAnalyticsController::class, 'contacts']);
$router->get('/admin/contacts/view', [AdminContactsAnalyticsController::class, 'contact']);
$router->post('/admin/contacts/update', [AdminContactsAnalyticsController::class, 'updateContact']);
$router->get('/admin/contacts/file/{id}', [AdminContactsAnalyticsController::class, 'attachment']);
$router->get('/admin/analytics', [AdminContactsAnalyticsController::class, 'analytics']);
$router->post('/admin/analytics/save', [AdminContactsAnalyticsController::class, 'saveAnalytics']);
$router->get('/admin/settings/general', static fn() => AdminSettingsController::page('general'));
$router->post('/admin/settings/general/save', static fn() => AdminSettingsController::save('general'));
$router->get('/admin/settings/email', static fn() => AdminSettingsController::page('email'));
$router->post('/admin/settings/email/save', static fn() => AdminSettingsController::save('email'));
$router->get('/admin/settings/users', [AdminSettingsController::class, 'users']);
$router->get('/admin/settings/site', static fn() => AdminSettingsController::page('site'));
$router->post('/admin/settings/site/save', static fn() => AdminSettingsController::save('site'));
$router->get('/admin/settings/system', [AdminSettingsController::class, 'system']);
$router->get('/admin/redirects', [RedirectsController::class, 'index']);
$router->get('/admin/redirects/form', [RedirectsController::class, 'form']);
$router->post('/admin/redirects/save', [RedirectsController::class, 'save']);

$router->setNotFoundHandler([SystemController::class, 'notFound']);
$router->dispatch($_SERVER['REQUEST_METHOD'] ?? 'GET', $_SERVER['REQUEST_URI'] ?? '/');
