-- Ricollega l'archivio PDF storico ai dieci accordion Terminali idronici.
INSERT INTO document_types(name,slug,sort_order,active) VALUES
('Schede tecniche','scheda-tecnica',10,1),('Tabelle rese','tabella-rese',20,1),('Manuali installazione','manuale-installazione',50,1),('Manuali uso','manuale-uso',50,1),('Prestazioni','altro',60,1)
ON DUPLICATE KEY UPDATE active=1;

INSERT INTO documents(document_type_id,title,filename,file_path,published,sort_order)
SELECT dt.id,'Scheda tecnica CANALIZZABILE IMK-CBS','FC_UI_CANALIZZABILE_IMK-CBS.pdf','https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_CANALIZZABILE_IMK-CBS.pdf',1,10 FROM document_types dt WHERE dt.slug='scheda-tecnica' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_CANALIZZABILE_IMK-CBS.pdf')
UNION ALL SELECT dt.id,'Scheda tecnica CANALIZZABILE IMKT-V','FC_UI_CANALIZZABILE_IMKT-V.pdf','https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_CANALIZZABILE_IMKT-V.pdf',1,20 FROM document_types dt WHERE dt.slug='scheda-tecnica' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_CANALIZZABILE_IMKT-V.pdf')
UNION ALL SELECT dt.id,'Scheda tecnica CASSETTA 600X600 IMKD-V','FC_UI_CASSETTA_600X600_IMKD-V.pdf','https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_CASSETTA_600X600_IMKD-V.pdf',1,30 FROM document_types dt WHERE dt.slug='scheda-tecnica' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_CASSETTA_600X600_IMKD-V.pdf')
UNION ALL SELECT dt.id,'Scheda tecnica CASSETTA 840X840 IMKA-V','FC_UI_CASSETTA_840X840_IMKA-V.pdf','https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_CASSETTA_840X840_IMKA-V.pdf',1,40 FROM document_types dt WHERE dt.slug='scheda-tecnica' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_CASSETTA_840X840_IMKA-V.pdf')
UNION ALL SELECT dt.id,'Scheda tecnica PARETE IMKG-V-B','FC_UI_PARETE_IMKG-V-B.pdf','https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_PARETE_IMKG-V-B.pdf',1,50 FROM document_types dt WHERE dt.slug='scheda-tecnica' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_PARETE_IMKG-V-B.pdf')
UNION ALL SELECT dt.id,'Scheda tecnica PARETE IMKG-V-C','FC_UI_PARETE_IMKG-V-C.pdf','https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_PARETE_IMKG-V-C.pdf',1,60 FROM document_types dt WHERE dt.slug='scheda-tecnica' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_PARETE_IMKG-V-C.pdf')
UNION ALL SELECT dt.id,'Scheda tecnica SOFFITTO-PAVIMENTO IMKH2-V','FC_UI_SOFFITTO-PAVIMENTO_IMKH2-V.pdf','https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_SOFFITTO-PAVIMENTO_IMKH2-V.pdf',1,70 FROM document_types dt WHERE dt.slug='scheda-tecnica' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_SOFFITTO-PAVIMENTO_IMKH2-V.pdf')
UNION ALL SELECT dt.id,'Scheda tecnica VITRO-IFS','FC_UI_VITRO-IFS.pdf','https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_VITRO-IFS.pdf',1,80 FROM document_types dt WHERE dt.slug='scheda-tecnica' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_VITRO-IFS.pdf')
UNION ALL SELECT dt.id,'Scheda tecnica VITRO-IHW','FC_UI_VITRO-IHW.pdf','https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_VITRO-IHW.pdf',1,90 FROM document_types dt WHERE dt.slug='scheda-tecnica' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_VITRO-IHW.pdf')
UNION ALL SELECT dt.id,'Manuale installazione e uso IMK-CBS','IM-UM_FC_UI_CANALIZZABILE_IMK-CBS.pdf','https://www.idemaclima.it/wp-content/uploads/schede/IM-UM_FC_UI_CANALIZZABILE_IMK-CBS.pdf',1,100 FROM document_types dt WHERE dt.slug='manuale-installazione' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/IM-UM_FC_UI_CANALIZZABILE_IMK-CBS.pdf')
UNION ALL SELECT dt.id,'Manuale installazione e uso IMKT-V','IM-UM_FC_UI_CANALIZZABILE_IMKT-V.pdf','https://www.idemaclima.it/wp-content/uploads/schede/IM-UM_FC_UI_CANALIZZABILE_IMKT-V.pdf',1,110 FROM document_types dt WHERE dt.slug='manuale-installazione' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/IM-UM_FC_UI_CANALIZZABILE_IMKT-V.pdf')
UNION ALL SELECT dt.id,'Manuale installazione e uso IMKD-V','IM-UM_FC_UI_CASSETTA_600X600_IMKD-V.pdf','https://www.idemaclima.it/wp-content/uploads/schede/IM-UM_FC_UI_CASSETTA_600X600_IMKD-V.pdf',1,120 FROM document_types dt WHERE dt.slug='manuale-installazione' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/IM-UM_FC_UI_CASSETTA_600X600_IMKD-V.pdf')
UNION ALL SELECT dt.id,'Manuale installazione e uso IMKA-V','IM-UM_FC_UI_CASSETTA_840X840_IMKA-V.pdf','https://www.idemaclima.it/wp-content/uploads/schede/IM-UM_FC_UI_CASSETTA_840X840_IMKA-V.pdf',1,130 FROM document_types dt WHERE dt.slug='manuale-installazione' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/IM-UM_FC_UI_CASSETTA_840X840_IMKA-V.pdf')
UNION ALL SELECT dt.id,'Manuale installazione e uso IMKH2-V','IM-UM_FC_UI_CONSOLE_IMKH2-V.pdf','https://www.idemaclima.it/wp-content/uploads/schede/IM-UM_FC_UI_CONSOLE_IMKH2-V.pdf',1,140 FROM document_types dt WHERE dt.slug='manuale-installazione' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/IM-UM_FC_UI_CONSOLE_IMKH2-V.pdf')
UNION ALL SELECT dt.id,'Manuale installazione e uso IMKG-V','IM-UM_FC_UI_PARETE_IMKG-V.pdf','https://www.idemaclima.it/wp-content/uploads/schede/IM-UM_FC_UI_PARETE_IMKG-V.pdf',1,150 FROM document_types dt WHERE dt.slug='manuale-installazione' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/IM-UM_FC_UI_PARETE_IMKG-V.pdf')
UNION ALL SELECT dt.id,'Prestazioni IMK-CBS','PA_UI_IMK-CBS.pdf','https://www.idemaclima.it/wp-content/uploads/schede/PA_UI_IMK-CBS.pdf',1,160 FROM document_types dt WHERE dt.slug='altro' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/PA_UI_IMK-CBS.pdf')
UNION ALL SELECT dt.id,'Prestazioni IMKT-V','PA_UI_IMKT-V.pdf','https://www.idemaclima.it/wp-content/uploads/schede/PA_UI_IMKT-V.pdf',1,170 FROM document_types dt WHERE dt.slug='altro' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/PA_UI_IMKT-V.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMK-CBS','TAB_UI_IMK-CBS.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMK-CBS.pdf',1,180 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMK-CBS.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKA-V1200R','TAB_UI_IMKA-V1200R.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKA-V1200R.pdf',1,190 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKA-V1200R.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKA-V1500R','TAB_UI_IMKA-V1500R.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKA-V1500R.pdf',1,200 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKA-V1500R.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKA-V600R','TAB_UI_IMKA-V600R.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKA-V600R.pdf',1,210 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKA-V600R.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKA-V750R','TAB_UI_IMKA-V750R.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKA-V750R.pdf',1,220 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKA-V750R.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKA-V850R','TAB_UI_IMKA-V850R.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKA-V850R.pdf',1,230 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKA-V850R.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKA-V950R','TAB_UI_IMKA-V950R.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKA-V950R.pdf',1,240 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKA-V950R.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKD-V300','TAB_UI_IMKD-V300.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKD-V300.pdf',1,250 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKD-V300.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKD-V400','TAB_UI_IMKD-V400.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKD-V400.pdf',1,260 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKD-V400.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKD-V500','TAB_UI_IMKD-V500.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKD-V500.pdf',1,270 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKD-V500.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKG-V250B','TAB_UI_IMKG-V250B.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V250B.pdf',1,280 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V250B.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKG-V300B','TAB_UI_IMKG-V300B.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V300B.pdf',1,290 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V300B.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKG-V300C','TAB_UI_IMKG-V300C.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V300C.pdf',1,300 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V300C.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKG-V400B','TAB_UI_IMKG-V400B.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V400B.pdf',1,310 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V400B.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKG-V400C','TAB_UI_IMKG-V400C.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V400C.pdf',1,320 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V400C.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKG-V500B','TAB_UI_IMKG-V500B.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V500B.pdf',1,330 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V500B.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKG-V600B','TAB_UI_IMKG-V600B.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V600B.pdf',1,340 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V600B.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKG-V600C','TAB_UI_IMKG-V600C.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V600C.pdf',1,350 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V600C.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKH2-V150-R3','TAB_UI_IMKH2-V150-R3.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKH2-V150-R3.pdf',1,360 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKH2-V150-R3.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKH2-V250-R3','TAB_UI_IMKH2-V250-R3.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKH2-V250-R3.pdf',1,370 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKH2-V250-R3.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKH2-V350-R3','TAB_UI_IMKH2-V350-R3.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKH2-V350-R3.pdf',1,380 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKH2-V350-R3.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKH2-V500-R3','TAB_UI_IMKH2-V500-R3.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKH2-V500-R3.pdf',1,390 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKH2-V500-R3.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKH2-V700-R3','TAB_UI_IMKH2-V700-R3.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKH2-V700-R3.pdf',1,400 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKH2-V700-R3.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKH2-V800-R3','TAB_UI_IMKH2-V800-R3.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKH2-V800-R3.pdf',1,410 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKH2-V800-R3.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKT2-V','TAB_UI_IMKT2-V.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKT2-V.pdf',1,420 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKT2-V.pdf')
UNION ALL SELECT dt.id,'Tabella rese IMKT3-V','TAB_UI_IMKT3-V.pdf','https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKT3-V.pdf',1,430 FROM document_types dt WHERE dt.slug='tabella-rese' AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.file_path='https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKT3-V.pdf');

INSERT INTO document_links(document_id,product_id)
SELECT d.id,p.id FROM (
SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_CANALIZZABILE_IMK-CBS.pdf' file_path,'terminali-idronici--imk-cbs' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_CANALIZZABILE_IMKT-V.pdf' file_path,'terminali-idronici--imkt2-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_CANALIZZABILE_IMKT-V.pdf' file_path,'terminali-idronici--imkt3-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_CASSETTA_600X600_IMKD-V.pdf' file_path,'terminali-idronici--imkd-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_CASSETTA_840X840_IMKA-V.pdf' file_path,'terminali-idronici--imka-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_PARETE_IMKG-V-B.pdf' file_path,'terminali-idronici--imkg-v-b' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_PARETE_IMKG-V-B.pdf' file_path,'terminali-idronici--imkg-v-c' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_PARETE_IMKG-V-C.pdf' file_path,'terminali-idronici--imkg-v-b' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_PARETE_IMKG-V-C.pdf' file_path,'terminali-idronici--imkg-v-c' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_SOFFITTO-PAVIMENTO_IMKH2-V.pdf' file_path,'terminali-idronici--imkh2-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_VITRO-IFS.pdf' file_path,'terminali-idronici--ifs' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/FC_UI_VITRO-IHW.pdf' file_path,'terminali-idronici--ihw' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/IM-UM_FC_UI_CANALIZZABILE_IMK-CBS.pdf' file_path,'terminali-idronici--imk-cbs' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/IM-UM_FC_UI_CANALIZZABILE_IMKT-V.pdf' file_path,'terminali-idronici--imkt2-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/IM-UM_FC_UI_CANALIZZABILE_IMKT-V.pdf' file_path,'terminali-idronici--imkt3-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/IM-UM_FC_UI_CASSETTA_600X600_IMKD-V.pdf' file_path,'terminali-idronici--imkd-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/IM-UM_FC_UI_CASSETTA_840X840_IMKA-V.pdf' file_path,'terminali-idronici--imka-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/IM-UM_FC_UI_CONSOLE_IMKH2-V.pdf' file_path,'terminali-idronici--imkh2-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/IM-UM_FC_UI_PARETE_IMKG-V.pdf' file_path,'terminali-idronici--imkg-v-b' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/IM-UM_FC_UI_PARETE_IMKG-V.pdf' file_path,'terminali-idronici--imkg-v-c' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/PA_UI_IMK-CBS.pdf' file_path,'terminali-idronici--imk-cbs' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/PA_UI_IMKT-V.pdf' file_path,'terminali-idronici--imkt2-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/PA_UI_IMKT-V.pdf' file_path,'terminali-idronici--imkt3-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMK-CBS.pdf' file_path,'terminali-idronici--imk-cbs' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKA-V1200R.pdf' file_path,'terminali-idronici--imka-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKA-V1500R.pdf' file_path,'terminali-idronici--imka-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKA-V600R.pdf' file_path,'terminali-idronici--imka-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKA-V750R.pdf' file_path,'terminali-idronici--imka-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKA-V850R.pdf' file_path,'terminali-idronici--imka-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKA-V950R.pdf' file_path,'terminali-idronici--imka-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKD-V300.pdf' file_path,'terminali-idronici--imkd-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKD-V400.pdf' file_path,'terminali-idronici--imkd-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKD-V500.pdf' file_path,'terminali-idronici--imkd-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V250B.pdf' file_path,'terminali-idronici--imkg-v-b' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V250B.pdf' file_path,'terminali-idronici--imkg-v-c' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V300B.pdf' file_path,'terminali-idronici--imkg-v-b' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V300B.pdf' file_path,'terminali-idronici--imkg-v-c' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V300C.pdf' file_path,'terminali-idronici--imkg-v-b' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V300C.pdf' file_path,'terminali-idronici--imkg-v-c' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V400B.pdf' file_path,'terminali-idronici--imkg-v-b' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V400B.pdf' file_path,'terminali-idronici--imkg-v-c' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V400C.pdf' file_path,'terminali-idronici--imkg-v-b' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V400C.pdf' file_path,'terminali-idronici--imkg-v-c' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V500B.pdf' file_path,'terminali-idronici--imkg-v-b' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V500B.pdf' file_path,'terminali-idronici--imkg-v-c' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V600B.pdf' file_path,'terminali-idronici--imkg-v-b' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V600B.pdf' file_path,'terminali-idronici--imkg-v-c' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V600C.pdf' file_path,'terminali-idronici--imkg-v-b' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKG-V600C.pdf' file_path,'terminali-idronici--imkg-v-c' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKH2-V150-R3.pdf' file_path,'terminali-idronici--imkh2-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKH2-V250-R3.pdf' file_path,'terminali-idronici--imkh2-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKH2-V350-R3.pdf' file_path,'terminali-idronici--imkh2-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKH2-V500-R3.pdf' file_path,'terminali-idronici--imkh2-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKH2-V700-R3.pdf' file_path,'terminali-idronici--imkh2-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKH2-V800-R3.pdf' file_path,'terminali-idronici--imkh2-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKT2-V.pdf' file_path,'terminali-idronici--imkt2-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKT2-V.pdf' file_path,'terminali-idronici--imkt3-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKT3-V.pdf' file_path,'terminali-idronici--imkt2-v' product_slug
UNION ALL SELECT 'https://www.idemaclima.it/wp-content/uploads/schede/TAB_UI_IMKT3-V.pdf' file_path,'terminali-idronici--imkt3-v' product_slug
) x JOIN documents d ON d.file_path=x.file_path JOIN products p ON p.slug=x.product_slug
WHERE NOT EXISTS (SELECT 1 FROM document_links dl WHERE dl.document_id=d.id AND dl.product_id=p.id);

