-- Importa integralmente i 20 accordion della pagina FAQ originale IDEMA.
DELETE f
FROM faq_items f
JOIN editorial_pages p ON p.id = f.page_id
WHERE p.slug = 'faq';

INSERT INTO faq_items(page_id,question,answer,sort_order,published)
SELECT id,'CHI PUÒ INSTALLARE I CLIMATIZZATORI?','Per poter installare i climatizzatori la ditta deve essere in possesso dei seguenti requisiti:

1) lettera C della Nuova 46/90 (Decreto 22 gennaio 2007) Camera di Commercio
2) Certificazione aziendale e personale secondo il DPR n.43 del 27 gennaio 2012 F-Gas con iscrizione al Registro Telematico Nazionale delle persone e delle imprese certificate
3) Qualifica FER Fonti di Energie Rinnovabili, (dal 31/07/2016) a norma del comma 1, lett. F dell’allegato 4 del D.lgs n. 28/2011

Requisiti necessari che consentono poi di rilasciare a norma di legge la “Dichiarazione di conformità dell’impianto alla regola dell’arte” dell’impianto di climatizzazione realizzato.',10,1 FROM editorial_pages WHERE slug='faq'
UNION ALL SELECT id,'CHE COSA COPRE LA GARANZIA DI UN CLIMATIZZATORE?','La legge stabilisce che se si acquista un bene di consumo mobile (si ha diritto a una garanzia legale minima di 2 anni che copra i difetti di fabbrica), IDEMA in alcuni modelli da una Garanzia di 5 anni sui difetti di fabbrica. La garanzia non copre difetti derivanti dall’installazione o da un uso improprio del climatizzatore.

Approfondimento sulla Garanzia (rimanda alla Garanzia)',20,1 FROM editorial_pages WHERE slug='faq'
UNION ALL SELECT id,'CALCOLO DELLA POTENZA NECESSARIA DEL CLIMATIZZATORE PER UN DETERMINATO LOCALE: PERCHÉ È IMPORTANTE?','Progettare gli impianti di condizionamento non significa soltanto scegliere il modello e installarlo. È necessario un sopralluogo del tecnico, che capirà effettivamente dove e come installare le macchine, pensando anche alle dimensioni dell’impianto in base all’esposizione al caldo, al freddo, classe energetica dell’abitazione, volumetria locali etc…',30,1 FROM editorial_pages WHERE slug='faq'
UNION ALL SELECT id,'PER FRUIRE DELL’ECOBONUS COSA VA INVIATO A ENEA?COME POSSO SAPERE SE LA MIA DOMANDA È STATA ACCETTATA?','Per la detrazione fiscale del 65% (Ecobonus) entro 90 giorni dal termine dei lavori deve essere trasmessa ad Enea, attraverso il sito dedicato dell’ente, la documentazione costituita da:

• Attestato di qualificazione energetica (Allegato A al “decreto edifici”);
• Scheda descrittiva degli interventi realizzati (Allegato E).

In alcuni casi è sufficiente una documentazione semplificata, costituita da:

• Allegato E (nel caso di sostituzione di impianti termici con caldaie a condensazione, pompe di calore ad alta efficienza o impianti geotermici a bassa entalpia o di sostituzione di scaldacqua di tipo tradizionale con scaldacqua a pompa di calore per A.C.S.);
• Allegato F (nel caso di sostituzione di infissi in singole unità immobiliari o di installazione di pannelli solari).

Effettuata la trasmissione, in automatico ritorna al mittente da ENEA una ricevuta informatica con il CPID (Codice Personale Identificativo), valida a tutti gli effetti come prova dell’avvenuto invio.
Non sono previsti altri riscontri da parte di Enea, né in caso di invio corretto, né in caso di invio incompleto, errato o non conforme.
Non vanno inviate asseverazioni, relazioni tecniche, fatture, copia di bonifici, piantine o documentazione varia che, invece, deve essere conservata a cura dell’utente ed esibita in caso di eventuali controlli da parte dell’Agenzia delle Entrate. Inoltre è facoltà dell’Agenzia richiedere l’esibizione degli originali degli Allegati inviati (A, E o F), debitamente firmati e datati.
Di conseguenza, si consiglia l’utente di stampare questi documenti e conservarli in caso di futuri possibili controlli. Si ricorda infine che l’allegato A deve essere necessariamente firmato e timbrato dal tecnico abilitato a certificare il rispetto dei requisiti richiesti all’impianto per accedere alle detrazioni.',40,1 FROM editorial_pages WHERE slug='faq'
UNION ALL SELECT id,'L’UNITÀ ESTERNA EMETTE FORTI VIBRAZIONI','I motivi per cui l’unità esterna emette delle vibrazioni posso essere vari ed alcuni riconducibili al tipo di installazione. Verificare se l’unità esterna è installata a livello, che siano stati montati correttamente tutti i sistemi ammortizzanti (sia che la macchina è stata montata a terra su degli appositi piedini, sia che la macchina è stata installata su apposite staffe da muro). Inoltre verificare sempre che le superfici di scambio risultino pulite.',50,1 FROM editorial_pages WHERE slug='faq'
UNION ALL SELECT id,'È POSSIBILE INSTALLARE UNA UNITÀ ESTERNA SOPRA IL TETTO?','Non ci sono particolari controindicazioni, l’importante è che l’apparecchio venga installato in modo raggiungibile in sicurezza per eventuali interventi di manutenzione futuri.',60,1 FROM editorial_pages WHERE slug='faq'
UNION ALL SELECT id,'COS’È UNA POMPA DI CALORE?','Una pompa di calore estrae energia a bassa temperatura dall’ambiente e ne aumenta la temperatura per riscaldare.',70,1 FROM editorial_pages WHERE slug='faq'
UNION ALL SELECT id,'COME SI OTTIENE LA DEUMIDIFICAZIONE DELL’ARIA?','La deumidificazione dell’aria si ottiene attraverso il climatizzatore in freddo oppure in sola deumidificazione in quanto raffreddando la propria batteria, trattiene il tasso di umidità e lo porta all’esterno attraverso un tubo di scarico condensa.',80,1 FROM editorial_pages WHERE slug='faq'
UNION ALL SELECT id,'COSA SONO I BTU/H?','È un’unità di misura che indica la potenza frigorifera di un climatizzatore al fine di dimensionarne la potenza in base ai locali da servire, nei prossimi anni sarà sostituita dal kW (1 kW = 3412 Btu/h).',90,1 FROM editorial_pages WHERE slug='faq'
UNION ALL SELECT id,'COS’È LA CLASSE ENERGETICA DEI CLIMATIZZATORI?','La classe energetica indica il rendimento energetico del climatizzatore a diverse temperature. Oggi i climatizzatori di alta fascia energetica sono quelli in classe A+++/A+++. Un modello a bassa efficienza può costarvi molte decine di euro in più all’anno di maggior consumo energetico.',100,1 FROM editorial_pages WHERE slug='faq'
UNION ALL SELECT id,'CAUSA DELLA PERDITA DI GAS REFRIGERANTE','In caso di una non corretta installazione e mancata pressatura dell’impianto (prova di tenuta con azoto dell’impianto), può verificarsi una perdita di gas refrigerante dalle giunzioni tra tubazione e raccordi dell’unità esterna o unità interna, per cui si consiglia di far installare il climatizzatore a personale specializzato e qualificato.',110,1 FROM editorial_pages WHERE slug='faq'
UNION ALL SELECT id,'QUAL È LA TEMPERATURA ADATTA DA IMPOSTARE?','La temperatura ottimale in riscaldamento tra i 20°C e 22°C, in raffreddamento è consigliato mantenere una differenza di temperatura tra interna ed esterna di 6/7°C e di sfruttare la funzione di deumidificazione.',120,1 FROM editorial_pages WHERE slug='faq'
UNION ALL SELECT id,'QUANDO BISOGNA EFFETTUARE LA RICARICA DEL GAS NEL CLIMATIZZATORE?','Non bisogna mai farlo. Il gas lavora in un circuito chiuso. Quindi se c’è una perdita significa che è stato installato male il climatizzatore. Diffidate da installatori che millantano che il climatizzatore deve essere ricaricato annualmente.',130,1 FROM editorial_pages WHERE slug='faq'
UNION ALL SELECT id,'IL CLIMATIZZATORE NON RAFFREDDA O RISCALDA A SUFFICIENZA?','Il motivo principale potrebbe essere quello di un cattivo scambio o dell’unità interna o dell’unità esterna, controllare pertanto che entrambe le unità siano pulite, soprattutto i filtri dell’unità interna e la parte posteriore dell’unità esterna. Rimuove ogni eventuale ostacolo che impedisco un corretto scambio d’aria. Il circuito frigorifero potrebbe avere una perdita di refrigerante, chiamate il vostro installatore per una verifica.',140,1 FROM editorial_pages WHERE slug='faq'
UNION ALL SELECT id,'DURANTE I PRIMI MINUTI DI FUNZIONAMENTO IN POMPA CALORE IL CLIMATIZZATORE NON EMETTE ARIA CALDA?','Quando il climatizzatore viene fatto funzionare in pompa di calore la ventilazione dell’unità interna partirà soltanto quando lo scambiatore avrà raggiunto una temperatura adeguata (circa 35/38°C) in modo da evitare che venga emessa aria fredda in ambiente. Questa fase di attesa viene appunto chiamata “preriscaldo”. Se il tempo di attesa per l’immissione di aria calda dovesse protrarsi oltre i 10 minuti, interpellate il vostro installatore per un controllo della resa dell’impianto, potrebbe esserci una perdita di refrigerante o l’occlusione dei filtri dell’aria.',150,1 FROM editorial_pages WHERE slug='faq'
UNION ALL SELECT id,'HO NOTATO PERDITE DI ACQUA DALL’UNITÀ INTERNA.QUALE PUÒ ESSERE LA CAUSA?','Se l’unità interna non è installata o messa a livello correttamente potrebbero verificarsi delle perdite di condensa. Una certa inclinazione è necessaria per consentire il corretto drenaggio.',160,1 FROM editorial_pages WHERE slug='faq'
UNION ALL SELECT id,'OGNI QUANTO SERVE PULIRE I FILTRI ARIA AL CLIMATIZZATORE?','Generalmente i climatizzatori ad uso residenziale è buona abitudine pulire i filtri almeno due volte l’anno, molto dipende anche dal numero di ore d’utilizzo.',170,1 FROM editorial_pages WHERE slug='faq'
UNION ALL SELECT id,'ACQUISTARE UN CLIMATIZZATORE DI POTENZA ADEGUATA','Molte persone tendono a pensare che un climatizzatore più grande raffreddi il locale più rapidamente e che sia anche più efficiente. In realtà, la capacità del climatizzatore dovrebbe essere sempre proporzionata all’ambiente in cui viene collocato. Un apparecchio sovradimensionato rispetto alla stanza che deve raffreddare non riesce a fornire una temperatura uniforme né a ridurre l’umidità dell’aria: al contrario, funziona in modo inefficiente, alternando in modo troppo rapido le fasi di accensione e di spegnimento. Allo stesso modo, anche un climatizzatore sotto dimensionato ha un pessimo rendimento. Il consiglio, quindi, è di acquistare sempre il climatizzatore in linea con le proprie effettive necessità, far fare un calcolo della potenza necessaria da un professionista qualificato senza essere approssimativi e senza voler strafare.',180,1 FROM editorial_pages WHERE slug='faq'
UNION ALL SELECT id,'POSSO “NASCONDERE” IL CLIMATIZZATORE','Il climatizzatore non è un complemento d’arredo elegante o di particolare valore estetico (quelli IDEMA lo sono!). Ciò non significa, però, che si debba nasconderlo dietro a piante o a tende: in questo modo, infatti, si privilegiano forse le apparenze ma si finisce per ostacolare la ventilazione, determinando un funzionamento poco efficiente e dispendioso dell’apparecchio. Siete certi che ne valga la pena?',190,1 FROM editorial_pages WHERE slug='faq'
UNION ALL SELECT id,'FARE LA MANUTENZIONE','Molti pensano che, una volta acquistato, il climatizzatore sia “per sempre”, ignorando che deve essere costantemente soggetto a pulizia e manutenzione: un po’ di attenzione, infatti, non solo migliora il rendimento del prodotto, ma ne allunga la vita. Per questo, i filtri dovrebbero essere controllati e puliti a cadenza bimestrale e, nel caso siano in cattive condizioni, sostituirli. Una volta ogni anno, poi, andrebbe controllata la batteria di evaporazione e il canale di scarico condensa. E non dimenticate di verificare che gli infissi di casa siano in buone condizioni e che non disperdano – a seconda della stagione – aria fresca o calore.',200,1 FROM editorial_pages WHERE slug='faq';
