-- Dati strutturati completi dei sei Mono Split
ALTER TABLE products ADD COLUMN tagline VARCHAR(255) NULL AFTER description;
ALTER TABLE products ADD COLUMN badges_text TEXT NULL AFTER tagline;
ALTER TABLE products ADD COLUMN warranty_label VARCHAR(100) NULL AFTER badges_text;
ALTER TABLE product_models ADD COLUMN cooling_kw DECIMAL(6,2) NULL AFTER name;
ALTER TABLE product_models ADD COLUMN seer DECIMAL(6,2) NULL AFTER cooling_kw;
ALTER TABLE product_models ADD COLUMN seer_class VARCHAR(20) NULL AFTER seer;
ALTER TABLE product_models ADD COLUMN heating_kw DECIMAL(6,2) NULL AFTER seer_class;
ALTER TABLE product_models ADD COLUMN scop DECIMAL(6,2) NULL AFTER heating_kw;
ALTER TABLE product_models ADD COLUMN scop_class VARCHAR(20) NULL AFTER scop;
ALTER TABLE product_models ADD COLUMN indoor_unit_code VARCHAR(100) NULL AFTER scop_class;
ALTER TABLE product_models ADD COLUMN outdoor_unit_code VARCHAR(100) NULL AFTER indoor_unit_code;
ALTER TABLE product_accessories ADD COLUMN availability_label VARCHAR(100) NULL AFTER description;
UPDATE products SET tagline='Top di gamma · Sensore di presenza · Wi-Fi di serie',description='Sistema Mono Split DC Inverter in pompa di calore serie ISPT-R32 ad altissima efficienza con sensore di presenza incorporato nel pannello, dispositivo Wi-Fi di serie, alette orizzontali e verticali motorizzate e funzione Active Clean ad alta temperatura per purificazione dell''aria da polvere e batteri.',badges_text='DC Inverter
Wi-Fi
R-32
ErP
Garanzia 5+5 anni',warranty_label='5+5 anni' WHERE name='ISPT-R32';
DELETE pf FROM product_features pf JOIN products p ON p.id=pf.product_id WHERE p.name='ISPT-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Sensore di presenza incorporato nel pannello',10 FROM products WHERE name='ISPT-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Dispositivo Wi-Fi di serie (compatibile Alexa e Google Home)',20 FROM products WHERE name='ISPT-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Funzione Active Clean ad alta temperatura per purificazione aria',30 FROM products WHERE name='ISPT-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Alette orizzontali e verticali motorizzate',40 FROM products WHERE name='ISPT-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Filtro agli ioni negativi incluso',50 FROM products WHERE name='ISPT-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Unità esterna compatta',60 FROM products WHERE name='ISPT-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Classe energetica fino a A+++/A+++',70 FROM products WHERE name='ISPT-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Gas refrigerante R32 a basso impatto ambientale',80 FROM products WHERE name='ISPT-R32';
DELETE pa FROM product_accessories pa JOIN products p ON p.id=pa.product_id WHERE p.name='ISPT-R32';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'RG10L1(G2HS)','Telecomando ad infrarossi',NULL,'Incluso',10,1 FROM products WHERE name='ISPT-R32';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'EU-OSK109','Chiavetta USB Wi-Fi (Alexa / Google Home)',NULL,'Incluso',20,1 FROM products WHERE name='ISPT-R32';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'12100206A00018','Filtro agli ioni negativi',NULL,'Incluso',30,1 FROM products WHERE name='ISPT-R32';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'KJR-120G1/TFBG-E','Comando remoto a parete con sensore temperatura e programmazione settimanale',NULL,'236,00 €',40,1 FROM products WHERE name='ISPT-R32';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'T-WACC-RC01','Scheda di collegamento per comando remoto a parete',NULL,'236,00 €',50,1 FROM products WHERE name='ISPT-R32';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'SMUV-101','Lampada a LED UVA/UVC germicida per disinfezione UV',NULL,'173,00 €',60,1 FROM products WHERE name='ISPT-R32';
INSERT INTO product_models(product_id,code,name,cooling_kw,seer,seer_class,heating_kw,scop,scop_class,indoor_unit_code,outdoor_unit_code,content_status,sort_order,published) SELECT id,'ISPT-25-R32',NULL,2.6,9,'A+++',3.8,5.1,'A+++','ISPT-25UI-R32','ISPT-25UE-R32','published',10,1 FROM products WHERE name='ISPT-R32' ON DUPLICATE KEY UPDATE cooling_kw=VALUES(cooling_kw),seer=VALUES(seer),seer_class=VALUES(seer_class),heating_kw=VALUES(heating_kw),scop=VALUES(scop),scop_class=VALUES(scop_class),indoor_unit_code=VALUES(indoor_unit_code),outdoor_unit_code=VALUES(outdoor_unit_code),sort_order=VALUES(sort_order),published=1,content_status='published';
INSERT INTO product_models(product_id,code,name,cooling_kw,seer,seer_class,heating_kw,scop,scop_class,indoor_unit_code,outdoor_unit_code,content_status,sort_order,published) SELECT id,'ISPT-35-R32',NULL,3.5,9.2,'A+++',3.8,5.1,'A+++','ISPT-35UI-R32','ISPT-35UE-R32','published',20,1 FROM products WHERE name='ISPT-R32' ON DUPLICATE KEY UPDATE cooling_kw=VALUES(cooling_kw),seer=VALUES(seer),seer_class=VALUES(seer_class),heating_kw=VALUES(heating_kw),scop=VALUES(scop),scop_class=VALUES(scop_class),indoor_unit_code=VALUES(indoor_unit_code),outdoor_unit_code=VALUES(outdoor_unit_code),sort_order=VALUES(sort_order),published=1,content_status='published';
INSERT INTO product_models(product_id,code,name,cooling_kw,seer,seer_class,heating_kw,scop,scop_class,indoor_unit_code,outdoor_unit_code,content_status,sort_order,published) SELECT id,'ISPT-50-R32',NULL,5,8.5,'A+++',5.6,4.6,'A++','ISPT-50UI-R32','ISPT-50UE-R32','published',30,1 FROM products WHERE name='ISPT-R32' ON DUPLICATE KEY UPDATE cooling_kw=VALUES(cooling_kw),seer=VALUES(seer),seer_class=VALUES(seer_class),heating_kw=VALUES(heating_kw),scop=VALUES(scop),scop_class=VALUES(scop_class),indoor_unit_code=VALUES(indoor_unit_code),outdoor_unit_code=VALUES(outdoor_unit_code),sort_order=VALUES(sort_order),published=1,content_status='published';
UPDATE products SET tagline='Alta efficienza · Filtro super ionizzatore germicida',description='Sistema Mono Split DC Inverter in pompa di calore serie ISAX-R32 ad alta efficienza con dispositivo Wi-Fi di serie, alette orizzontali e verticali motorizzate e filtro super ionizzatore germicida.',badges_text='DC Inverter
Wi-Fi
R-32
ErP',warranty_label='Garanzia standard' WHERE name='ISAX-R32';
DELETE pf FROM product_features pf JOIN products p ON p.id=pf.product_id WHERE p.name='ISAX-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Dispositivo Wi-Fi di serie (compatibile Alexa e Google Home)',10 FROM products WHERE name='ISAX-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Filtro super ionizzatore germicida incluso',20 FROM products WHERE name='ISAX-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Alette orizzontali e verticali motorizzate',30 FROM products WHERE name='ISAX-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Quattro taglie disponibili da 2,6 a 7,3 kW',40 FROM products WHERE name='ISAX-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Classe energetica fino a A+++/A++',50 FROM products WHERE name='ISAX-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Gas refrigerante R32 a basso impatto ambientale',60 FROM products WHERE name='ISAX-R32';
DELETE pa FROM product_accessories pa JOIN products p ON p.id=pa.product_id WHERE p.name='ISAX-R32';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'RG10A5(E)','Telecomando ad infrarossi',NULL,'Incluso',10,1 FROM products WHERE name='ISAX-R32';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'—','Filtro super ionizzatore germicida',NULL,'Incluso',20,1 FROM products WHERE name='ISAX-R32';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'EU-OSK105','Chiavetta USB Wi-Fi (Alexa / Google Home)',NULL,'Incluso',30,1 FROM products WHERE name='ISAX-R32';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'KJR-120G1/TFBG-E','Comando remoto a parete con sensore temperatura e programmazione settimanale',NULL,'236,00 €',40,1 FROM products WHERE name='ISAX-R32';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'T-WACC-RC01','Scheda di collegamento per comando remoto a parete',NULL,'236,00 €',50,1 FROM products WHERE name='ISAX-R32';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'12100206A00018','Filtro agli ioni negativi',NULL,'131,00 €',60,1 FROM products WHERE name='ISAX-R32';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'SMUV-101','Lampada a LED UVA/UVC germicida per disinfezione UV',NULL,'173,00 €',70,1 FROM products WHERE name='ISAX-R32';
INSERT INTO product_models(product_id,code,name,cooling_kw,seer,seer_class,heating_kw,scop,scop_class,indoor_unit_code,outdoor_unit_code,content_status,sort_order,published) SELECT id,'ISAX-25-R32',NULL,2.6,9.3,'A+++',2.9,4.6,'A++','ISAX-25UI-R32','ISAX-25UE-R32','published',10,1 FROM products WHERE name='ISAX-R32' ON DUPLICATE KEY UPDATE cooling_kw=VALUES(cooling_kw),seer=VALUES(seer),seer_class=VALUES(seer_class),heating_kw=VALUES(heating_kw),scop=VALUES(scop),scop_class=VALUES(scop_class),indoor_unit_code=VALUES(indoor_unit_code),outdoor_unit_code=VALUES(outdoor_unit_code),sort_order=VALUES(sort_order),published=1,content_status='published';
INSERT INTO product_models(product_id,code,name,cooling_kw,seer,seer_class,heating_kw,scop,scop_class,indoor_unit_code,outdoor_unit_code,content_status,sort_order,published) SELECT id,'ISAX-35-R32',NULL,3.5,8.5,'A+++',3.8,4.6,'A++','ISAX-35UI-R32','ISAX-35UE-R32','published',20,1 FROM products WHERE name='ISAX-R32' ON DUPLICATE KEY UPDATE cooling_kw=VALUES(cooling_kw),seer=VALUES(seer),seer_class=VALUES(seer_class),heating_kw=VALUES(heating_kw),scop=VALUES(scop),scop_class=VALUES(scop_class),indoor_unit_code=VALUES(indoor_unit_code),outdoor_unit_code=VALUES(outdoor_unit_code),sort_order=VALUES(sort_order),published=1,content_status='published';
INSERT INTO product_models(product_id,code,name,cooling_kw,seer,seer_class,heating_kw,scop,scop_class,indoor_unit_code,outdoor_unit_code,content_status,sort_order,published) SELECT id,'ISAX-50-R32',NULL,5.3,7,'A++',5.6,4,'A+','ISAX-50UI-R32','ISAX-50UE-R32','published',30,1 FROM products WHERE name='ISAX-R32' ON DUPLICATE KEY UPDATE cooling_kw=VALUES(cooling_kw),seer=VALUES(seer),seer_class=VALUES(seer_class),heating_kw=VALUES(heating_kw),scop=VALUES(scop),scop_class=VALUES(scop_class),indoor_unit_code=VALUES(indoor_unit_code),outdoor_unit_code=VALUES(outdoor_unit_code),sort_order=VALUES(sort_order),published=1,content_status='published';
INSERT INTO product_models(product_id,code,name,cooling_kw,seer,seer_class,heating_kw,scop,scop_class,indoor_unit_code,outdoor_unit_code,content_status,sort_order,published) SELECT id,'ISAX-70-R32',NULL,7.3,6.5,'A++',7.6,4,'A+','ISAX-70UI-R32','ISAX-70UE-R32','published',40,1 FROM products WHERE name='ISAX-R32' ON DUPLICATE KEY UPDATE cooling_kw=VALUES(cooling_kw),seer=VALUES(seer),seer_class=VALUES(seer_class),heating_kw=VALUES(heating_kw),scop=VALUES(scop),scop_class=VALUES(scop_class),indoor_unit_code=VALUES(indoor_unit_code),outdoor_unit_code=VALUES(outdoor_unit_code),sort_order=VALUES(sort_order),published=1,content_status='published';
UPDATE products SET tagline='Alta efficienza · Wi-Fi · Filtro ioni negativi',description='Sistema Mono Split DC Inverter in pompa di calore serie WTMC-R32 ad alta efficienza con dispositivo Wi-Fi di serie, filtro agli ioni negativi e alette orizzontali e verticali motorizzate.',badges_text='DC Inverter
Wi-Fi
R-32
ErP
Garanzia 2+3 anni',warranty_label='2+3 anni' WHERE name='WTMC-R32';
DELETE pf FROM product_features pf JOIN products p ON p.id=pf.product_id WHERE p.name='WTMC-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Dispositivo Wi-Fi di serie (compatibile Alexa e Google Home)',10 FROM products WHERE name='WTMC-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Filtro agli ioni negativi',20 FROM products WHERE name='WTMC-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Alette orizzontali e verticali motorizzate',30 FROM products WHERE name='WTMC-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Quattro taglie disponibili da 2,6 a 7,0 kW',40 FROM products WHERE name='WTMC-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Classe energetica fino a A+++/A++',50 FROM products WHERE name='WTMC-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Gas refrigerante R32 a basso impatto ambientale',60 FROM products WHERE name='WTMC-R32';
DELETE pa FROM product_accessories pa JOIN products p ON p.id=pa.product_id WHERE p.name='WTMC-R32';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'RCH-RTY2-0','Telecomando ad infrarossi',NULL,'Incluso',10,1 FROM products WHERE name='WTMC-R32';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'AEH-W0G2','Interfaccia Wi-Fi via cavo (Alexa / Google Home)',NULL,'Incluso',20,1 FROM products WHERE name='WTMC-R32';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'YXE-C02U1(E)','Comando remoto a parete con sensore di temperatura e programmazione settimanale',NULL,'191,00 €',30,1 FROM products WHERE name='WTMC-R32';
INSERT INTO product_models(product_id,code,name,cooling_kw,seer,seer_class,heating_kw,scop,scop_class,indoor_unit_code,outdoor_unit_code,content_status,sort_order,published) SELECT id,'WTMC-25-R32',NULL,2.6,8.5,'A+++',3,4.6,'A++','WTMC-25UI-R32','WTMC-25UE-R32','published',10,1 FROM products WHERE name='WTMC-R32' ON DUPLICATE KEY UPDATE cooling_kw=VALUES(cooling_kw),seer=VALUES(seer),seer_class=VALUES(seer_class),heating_kw=VALUES(heating_kw),scop=VALUES(scop),scop_class=VALUES(scop_class),indoor_unit_code=VALUES(indoor_unit_code),outdoor_unit_code=VALUES(outdoor_unit_code),sort_order=VALUES(sort_order),published=1,content_status='published';
INSERT INTO product_models(product_id,code,name,cooling_kw,seer,seer_class,heating_kw,scop,scop_class,indoor_unit_code,outdoor_unit_code,content_status,sort_order,published) SELECT id,'WTMC-35-R32',NULL,3.5,8.5,'A+++',3.9,4.6,'A++','WTMC-35UI-R32','WTMC-35UE-R32','published',20,1 FROM products WHERE name='WTMC-R32' ON DUPLICATE KEY UPDATE cooling_kw=VALUES(cooling_kw),seer=VALUES(seer),seer_class=VALUES(seer_class),heating_kw=VALUES(heating_kw),scop=VALUES(scop),scop_class=VALUES(scop_class),indoor_unit_code=VALUES(indoor_unit_code),outdoor_unit_code=VALUES(outdoor_unit_code),sort_order=VALUES(sort_order),published=1,content_status='published';
INSERT INTO product_models(product_id,code,name,cooling_kw,seer,seer_class,heating_kw,scop,scop_class,indoor_unit_code,outdoor_unit_code,content_status,sort_order,published) SELECT id,'WTMC-50-R32',NULL,5,8.5,'A+++',5.4,4.6,'A++','WTMC-50UI-R32','WTMC-50UE-R32','published',30,1 FROM products WHERE name='WTMC-R32' ON DUPLICATE KEY UPDATE cooling_kw=VALUES(cooling_kw),seer=VALUES(seer),seer_class=VALUES(seer_class),heating_kw=VALUES(heating_kw),scop=VALUES(scop),scop_class=VALUES(scop_class),indoor_unit_code=VALUES(indoor_unit_code),outdoor_unit_code=VALUES(outdoor_unit_code),sort_order=VALUES(sort_order),published=1,content_status='published';
INSERT INTO product_models(product_id,code,name,cooling_kw,seer,seer_class,heating_kw,scop,scop_class,indoor_unit_code,outdoor_unit_code,content_status,sort_order,published) SELECT id,'WTMC-70-R32',NULL,7,7.8,'A++',6.7,4.6,'A++','WTMC-70UI-R32','WTMC-70UE-R32','published',40,1 FROM products WHERE name='WTMC-R32' ON DUPLICATE KEY UPDATE cooling_kw=VALUES(cooling_kw),seer=VALUES(seer),seer_class=VALUES(seer_class),heating_kw=VALUES(heating_kw),scop=VALUES(scop),scop_class=VALUES(scop_class),indoor_unit_code=VALUES(indoor_unit_code),outdoor_unit_code=VALUES(outdoor_unit_code),sort_order=VALUES(sort_order),published=1,content_status='published';
UPDATE products SET tagline='Versione COLOR (BLACK) · Wi-Fi di serie',description='Sistema Mono Split DC Inverter in pompa di calore serie WTMC-R32 COLOR ad alta efficienza con dispositivo Wi-Fi di serie, filtro agli ioni negativi e alette orizzontali e verticali motorizzate. Disponibile in finitura BLACK.',badges_text='DC Inverter
Wi-Fi
R-32
Color Black
Garanzia 2+3 anni',warranty_label='2+3 anni' WHERE name='WTMC-R32 COLOR';
DELETE pf FROM product_features pf JOIN products p ON p.id=pf.product_id WHERE p.name='WTMC-R32 COLOR';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Versione COLOR — finitura Black di design',10 FROM products WHERE name='WTMC-R32 COLOR';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Dispositivo Wi-Fi di serie (compatibile Alexa e Google Home)',20 FROM products WHERE name='WTMC-R32 COLOR';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Filtro agli ioni negativi',30 FROM products WHERE name='WTMC-R32 COLOR';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Alette orizzontali e verticali motorizzate',40 FROM products WHERE name='WTMC-R32 COLOR';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Due taglie disponibili: 2,6 e 3,5 kW',50 FROM products WHERE name='WTMC-R32 COLOR';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Gas refrigerante R32 a basso impatto ambientale',60 FROM products WHERE name='WTMC-R32 COLOR';
DELETE pa FROM product_accessories pa JOIN products p ON p.id=pa.product_id WHERE p.name='WTMC-R32 COLOR';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'RCH-RTY2-0','Telecomando ad infrarossi',NULL,'Incluso',10,1 FROM products WHERE name='WTMC-R32 COLOR';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'AEH-W0G2','Interfaccia Wi-Fi via cavo (Alexa / Google Home)',NULL,'Incluso',20,1 FROM products WHERE name='WTMC-R32 COLOR';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'YXE-C02U1(E)','Comando remoto a parete con sensore di temperatura e programmazione settimanale',NULL,'191,00 €',30,1 FROM products WHERE name='WTMC-R32 COLOR';
INSERT INTO product_models(product_id,code,name,cooling_kw,seer,seer_class,heating_kw,scop,scop_class,indoor_unit_code,outdoor_unit_code,content_status,sort_order,published) SELECT id,'WTMC-25-BLK-R32',NULL,2.6,8.5,'A+++',3,4.6,'A++','WTMC-25UI-BLK-R32','WTMC-25UE-R32','published',10,1 FROM products WHERE name='WTMC-R32 COLOR' ON DUPLICATE KEY UPDATE cooling_kw=VALUES(cooling_kw),seer=VALUES(seer),seer_class=VALUES(seer_class),heating_kw=VALUES(heating_kw),scop=VALUES(scop),scop_class=VALUES(scop_class),indoor_unit_code=VALUES(indoor_unit_code),outdoor_unit_code=VALUES(outdoor_unit_code),sort_order=VALUES(sort_order),published=1,content_status='published';
INSERT INTO product_models(product_id,code,name,cooling_kw,seer,seer_class,heating_kw,scop,scop_class,indoor_unit_code,outdoor_unit_code,content_status,sort_order,published) SELECT id,'WTMC-35-BLK-R32',NULL,3.5,8.5,'A+++',3.9,4.6,'A++','WTMC-35UI-BLK-R32','WTMC-35UE-R32','published',20,1 FROM products WHERE name='WTMC-R32 COLOR' ON DUPLICATE KEY UPDATE cooling_kw=VALUES(cooling_kw),seer=VALUES(seer),seer_class=VALUES(seer_class),heating_kw=VALUES(heating_kw),scop=VALUES(scop),scop_class=VALUES(scop_class),indoor_unit_code=VALUES(indoor_unit_code),outdoor_unit_code=VALUES(outdoor_unit_code),sort_order=VALUES(sort_order),published=1,content_status='published';
UPDATE products SET tagline='Predisposizione Wi-Fi · Quattro taglie',description='Sistema Mono Split DC Inverter in pompa di calore serie ISZZ-R32 con predisposizione Wi-Fi.',badges_text='DC Inverter
Wi-Fi ready
R-32
ErP',warranty_label='Garanzia standard' WHERE name='ISZZ-R32';
DELETE pf FROM product_features pf JOIN products p ON p.id=pf.product_id WHERE p.name='ISZZ-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Predisposizione Wi-Fi (chiavetta USB opzionale)',10 FROM products WHERE name='ISZZ-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Quattro taglie disponibili da 2,6 a 7,0 kW',20 FROM products WHERE name='ISZZ-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Classe energetica A++/A+',30 FROM products WHERE name='ISZZ-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Gas refrigerante R32 a basso impatto ambientale',40 FROM products WHERE name='ISZZ-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Telecomando ad infrarossi incluso',50 FROM products WHERE name='ISZZ-R32';
DELETE pa FROM product_accessories pa JOIN products p ON p.id=pa.product_id WHERE p.name='ISZZ-R32';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'RG10A4(E)','Telecomando ad infrarossi',NULL,'Incluso',10,1 FROM products WHERE name='ISZZ-R32';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'EU-OSK105','Chiavetta USB Wi-Fi (Alexa / Google Home)',NULL,'131,00 €',20,1 FROM products WHERE name='ISZZ-R32';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'SMUV-101','Lampada a LED UVA/UVC germicida per disinfezione UV',NULL,'173,00 €',30,1 FROM products WHERE name='ISZZ-R32';
INSERT INTO product_models(product_id,code,name,cooling_kw,seer,seer_class,heating_kw,scop,scop_class,indoor_unit_code,outdoor_unit_code,content_status,sort_order,published) SELECT id,'ISZZ-25-R32',NULL,2.6,6.3,'A++',2.9,4,'A+','ISZZ-25UI-R32','ISZZ-25UE-R32','published',10,1 FROM products WHERE name='ISZZ-R32' ON DUPLICATE KEY UPDATE cooling_kw=VALUES(cooling_kw),seer=VALUES(seer),seer_class=VALUES(seer_class),heating_kw=VALUES(heating_kw),scop=VALUES(scop),scop_class=VALUES(scop_class),indoor_unit_code=VALUES(indoor_unit_code),outdoor_unit_code=VALUES(outdoor_unit_code),sort_order=VALUES(sort_order),published=1,content_status='published';
INSERT INTO product_models(product_id,code,name,cooling_kw,seer,seer_class,heating_kw,scop,scop_class,indoor_unit_code,outdoor_unit_code,content_status,sort_order,published) SELECT id,'ISZZ-35-R32',NULL,3.5,6.1,'A++',3.7,4,'A+','ISZZ-35UI-R32','ISZZ-35UE-R32','published',20,1 FROM products WHERE name='ISZZ-R32' ON DUPLICATE KEY UPDATE cooling_kw=VALUES(cooling_kw),seer=VALUES(seer),seer_class=VALUES(seer_class),heating_kw=VALUES(heating_kw),scop=VALUES(scop),scop_class=VALUES(scop_class),indoor_unit_code=VALUES(indoor_unit_code),outdoor_unit_code=VALUES(outdoor_unit_code),sort_order=VALUES(sort_order),published=1,content_status='published';
INSERT INTO product_models(product_id,code,name,cooling_kw,seer,seer_class,heating_kw,scop,scop_class,indoor_unit_code,outdoor_unit_code,content_status,sort_order,published) SELECT id,'ISZZ-50-R32',NULL,5.3,7.4,'A++',5.6,4,'A+','ISZZ-50UI-R32','ISZZ-50UE-R32','published',30,1 FROM products WHERE name='ISZZ-R32' ON DUPLICATE KEY UPDATE cooling_kw=VALUES(cooling_kw),seer=VALUES(seer),seer_class=VALUES(seer_class),heating_kw=VALUES(heating_kw),scop=VALUES(scop),scop_class=VALUES(scop_class),indoor_unit_code=VALUES(indoor_unit_code),outdoor_unit_code=VALUES(outdoor_unit_code),sort_order=VALUES(sort_order),published=1,content_status='published';
INSERT INTO product_models(product_id,code,name,cooling_kw,seer,seer_class,heating_kw,scop,scop_class,indoor_unit_code,outdoor_unit_code,content_status,sort_order,published) SELECT id,'ISZZ-70-R32',NULL,7,6.1,'A++',7.3,4,'A+','ISZZ-70UI-R32','ISZZ-70UE-R32','published',40,1 FROM products WHERE name='ISZZ-R32' ON DUPLICATE KEY UPDATE cooling_kw=VALUES(cooling_kw),seer=VALUES(seer),seer_class=VALUES(seer_class),heating_kw=VALUES(heating_kw),scop=VALUES(scop),scop_class=VALUES(scop_class),indoor_unit_code=VALUES(indoor_unit_code),outdoor_unit_code=VALUES(outdoor_unit_code),sort_order=VALUES(sort_order),published=1,content_status='published';
UPDATE products SET tagline='Soluzione entry · Predisposizione Wi-Fi',description='Sistema Mono Split DC Inverter in pompa di calore serie WTZ-R32 con predisposizione Wi-Fi.',badges_text='DC Inverter
Wi-Fi ready
R-32
Garanzia 2+3 anni',warranty_label='2+3 anni' WHERE name='WTZ-R32';
DELETE pf FROM product_features pf JOIN products p ON p.id=pf.product_id WHERE p.name='WTZ-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Predisposizione Wi-Fi (interfaccia opzionale)',10 FROM products WHERE name='WTZ-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Tre taglie disponibili da 2,6 a 5,0 kW',20 FROM products WHERE name='WTZ-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Classe energetica A++/A+',30 FROM products WHERE name='WTZ-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Gas refrigerante R32 a basso impatto ambientale',40 FROM products WHERE name='WTZ-R32';
INSERT INTO product_features(product_id,label,sort_order) SELECT id,'Telecomando ad infrarossi incluso',50 FROM products WHERE name='WTZ-R32';
DELETE pa FROM product_accessories pa JOIN products p ON p.id=pa.product_id WHERE p.name='WTZ-R32';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'DG11L1-12','Telecomando ad infrarossi',NULL,'Incluso',10,1 FROM products WHERE name='WTZ-R32';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'AEH-W41H1','Interfaccia Wi-Fi via cavo (Alexa / Google Home)',NULL,'129,00 €',20,1 FROM products WHERE name='WTZ-R32';
INSERT INTO product_accessories(product_id,code,name,description,availability_label,sort_order,published) SELECT id,'YXE-C02U1(E)','Comando remoto a parete con sensore di temperatura e programmazione settimanale',NULL,'191,00 €',30,1 FROM products WHERE name='WTZ-R32';
INSERT INTO product_models(product_id,code,name,cooling_kw,seer,seer_class,heating_kw,scop,scop_class,indoor_unit_code,outdoor_unit_code,content_status,sort_order,published) SELECT id,'WTZ-25-R32',NULL,2.6,6.3,'A++',2.7,4,'A+','WTZ-25UI-R32','WTZ-25UE-R32','published',10,1 FROM products WHERE name='WTZ-R32' ON DUPLICATE KEY UPDATE cooling_kw=VALUES(cooling_kw),seer=VALUES(seer),seer_class=VALUES(seer_class),heating_kw=VALUES(heating_kw),scop=VALUES(scop),scop_class=VALUES(scop_class),indoor_unit_code=VALUES(indoor_unit_code),outdoor_unit_code=VALUES(outdoor_unit_code),sort_order=VALUES(sort_order),published=1,content_status='published';
INSERT INTO product_models(product_id,code,name,cooling_kw,seer,seer_class,heating_kw,scop,scop_class,indoor_unit_code,outdoor_unit_code,content_status,sort_order,published) SELECT id,'WTZ-35-R32',NULL,3.2,6.8,'A++',3.3,4,'A+','WTZ-35UI-R32','WTZ-35UE-R32','published',20,1 FROM products WHERE name='WTZ-R32' ON DUPLICATE KEY UPDATE cooling_kw=VALUES(cooling_kw),seer=VALUES(seer),seer_class=VALUES(seer_class),heating_kw=VALUES(heating_kw),scop=VALUES(scop),scop_class=VALUES(scop_class),indoor_unit_code=VALUES(indoor_unit_code),outdoor_unit_code=VALUES(outdoor_unit_code),sort_order=VALUES(sort_order),published=1,content_status='published';
INSERT INTO product_models(product_id,code,name,cooling_kw,seer,seer_class,heating_kw,scop,scop_class,indoor_unit_code,outdoor_unit_code,content_status,sort_order,published) SELECT id,'WTZ-50-R32',NULL,5,6.1,'A++',5,4,'A+','WTZ-50UI-R32','WTZ-50UE-R32','published',30,1 FROM products WHERE name='WTZ-R32' ON DUPLICATE KEY UPDATE cooling_kw=VALUES(cooling_kw),seer=VALUES(seer),seer_class=VALUES(seer_class),heating_kw=VALUES(heating_kw),scop=VALUES(scop),scop_class=VALUES(scop_class),indoor_unit_code=VALUES(indoor_unit_code),outdoor_unit_code=VALUES(outdoor_unit_code),sort_order=VALUES(sort_order),published=1,content_status='published';
