<?php
$path=(string)(parse_url($_SERVER['REQUEST_URI']??'',PHP_URL_PATH)??'');$marker='/detrazioni-e-incentivi/';$key=str_contains($path,$marker)?trim(substr($path,strpos($path,$marker)+strlen($marker)),'/'):'';
$links=['bonus-casa'=>'Bonus Casa','ecobonus'=>'Ecobonus','conto-termico'=>'Conto Termico','consulenza-energetica'=>'Consulenza energetica'];
?>
<style>.inc-hero{padding:62px 0 72px;background:var(--gradient-cool);border-bottom:1px solid var(--border)}.inc-label{color:var(--primary-deep);font-size:12px;font-weight:600;letter-spacing:.3em;text-transform:uppercase}.inc-hero h1{max-width:1000px;margin:12px 0 17px;font-size:clamp(42px,6vw,68px);line-height:1.04}.inc-hero p,.inc-article p,.inc-article li{color:var(--muted-foreground);line-height:1.75}.inc-subnav{padding:18px 0;border-bottom:1px solid var(--border);background:var(--muted)}.inc-subnav .wrap{display:flex;gap:10px;flex-wrap:wrap}.inc-pill{padding:8px 13px;border:1px solid var(--border);border-radius:999px;background:#fff;font-size:12px}.inc-article{max-width:860px;padding-top:58px;padding-bottom:90px}.inc-section{margin-bottom:38px}.inc-section h2{font-size:28px}.inc-note{padding:22px;border:1px solid var(--border);border-radius:18px;background:var(--muted)}.inc-cards{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;padding:54px 0 80px}.inc-card{min-height:220px;padding:28px;border:1px solid var(--border);border-radius:22px;background:#fff}.inc-book{padding:72px 0;background:var(--muted)}.inc-faq{overflow:hidden;border:1px solid var(--border);border-radius:20px;background:#fff}.inc-faq details{padding:0 24px;border-bottom:1px solid var(--border)}.inc-faq summary{padding:21px 0;cursor:pointer;font-family:Sora;font-weight:600}.inc-answer{padding:0 0 22px;color:var(--muted-foreground);line-height:1.75}@media(max-width:850px){.inc-cards{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.inc-cards{grid-template-columns:1fr}}</style>
<?php if($key===''):?>
<section class="inc-hero"><div class="wrap"><span class="inc-label">Detrazioni e Incentivi</span><h1>Agevolazioni per l’efficienza energetica.</h1><p>Informazioni utili sulle detrazioni fiscali e sugli incentivi per climatizzatori e pompe di calore ad alta efficienza.</p></div></section>
<section class="wrap"><div class="inc-cards"><?php foreach($links as $slug=>$label):?><a class="inc-card" href="/idemaclima/detrazioni-e-incentivi/<?=e($slug)?>"><span class="inc-label">Approfondimento</span><h2><?=e($label)?></h2><p>Requisiti, spese ammesse, documentazione e procedura.</p></a><?php endforeach;?></div></section>
<section class="inc-book"><div class="wrap"><span class="inc-label">— Libretto d’impianto</span><h2>Quando e da chi va compilato e per quali impianti è obbligatorio.</h2><p>Dal 15 ottobre 2014 è obbligatorio dotarsi e compilare il nuovo libretto per tutti gli impianti termici, nel rispetto delle disposizioni regionali.</p><div class="inc-faq"><?php foreach($faqs as $i=>$f):?><details><summary><?=($i+1)?>. <?=e((string)$f['question'])?></summary><div class="inc-answer"><?=nl2br(e((string)$f['answer']))?></div></details><?php endforeach;?></div></div></section>
<?php else:$heads=['bonus-casa'=>['BONUS CASA','Detrazione per interventi edilizi: Bonus Casa'],'ecobonus'=>['ECOBONUS','Detrazioni per riqualificazione energetica'],'conto-termico'=>['CONTO TERMICO','Contributo statale GSE'],'consulenza-energetica'=>['CONSULENZA ENERGETICA','Supporto per le pratiche Conto Termico']];$h=$heads[$key]??$heads['bonus-casa'];?>
<section class="inc-hero"><div class="wrap"><span class="inc-label">Detrazioni e Incentivi</span><h1><?=e($h[0])?></h1><p><?=e($h[1])?></p></div></section><nav class="inc-subnav"><div class="wrap"><a class="inc-pill" href="/idemaclima/detrazioni-e-incentivi">← Panoramica</a><?php foreach($links as $slug=>$label):if($slug!==$key):?><a class="inc-pill" href="/idemaclima/detrazioni-e-incentivi/<?=e($slug)?>"><?=e($label)?></a><?php endif;endforeach;?></div></nav><article class="wrap inc-article">
<?php if($key==='bonus-casa'):?>
<section class="inc-section"><p>Il Bonus Casa consente di detrarre le spese per interventi edilizi e impiantistici, compresa l’installazione di pompe di calore finalizzata al risparmio energetico anche senza opere edilizie.</p><div class="inc-note"><strong>Aliquote 2025:</strong> 50% per l’abitazione principale e 36% per gli altri immobili, su una spesa massima di € 96.000 per unità immobiliare, in 10 quote annuali.</div></section>
<section class="inc-section"><h2>Interventi e requisiti</h2><ul><li>Installazione di climatizzatori e pompe di calore ad alta efficienza.</li><li>Nuovo impianto o sostituzione/integrazione dell’impianto esistente.</li><li>Rispetto delle prestazioni tecniche e conservazione delle certificazioni.</li></ul></section>
<section class="inc-section"><h2>Pagamento e documenti</h2><p>Il bonifico parlante deve indicare causale normativa, codice fiscale del beneficiario e partita IVA o codice fiscale del destinatario. Conservare fatture, ricevute, dichiarazioni di conformità e titoli abilitativi eventualmente richiesti.</p></section><section class="inc-section"><h2>Comunicazione ENEA</h2><p>Trasmettere i dati entro 90 giorni dalla fine lavori o dal collaudo quando previsto. Dal 2025 sono escluse dall’agevolazione le sostituzioni con caldaie uniche alimentate a combustibili fossili.</p></section>
<?php elseif($key==='ecobonus'):?>
<section class="inc-section"><p>L’Ecobonus riguarda la riqualificazione energetica di edifici esistenti e la sostituzione, integrale o parziale, degli impianti di climatizzazione invernale con pompe di calore ad alta efficienza o scaldacqua a pompa di calore.</p><div class="inc-note"><strong>Aliquote 2025:</strong> 50% per l’abitazione principale e 36% per gli altri immobili, fino a € 30.000, in 10 quote annuali.</div></section>
<section class="inc-section"><h2>Spese ammesse</h2><ul><li>Smontaggio e dismissione dell’impianto esistente.</li><li>Fornitura e posa delle nuove apparecchiature.</li><li>Opere idrauliche, murarie ed elettriche necessarie.</li><li>Sistemi di regolazione, controllo e prestazioni professionali.</li></ul></section>
<section class="inc-section"><h2>Adempimenti</h2><p>Pagare con bonifico parlante, conservare asseverazioni e dichiarazioni di conformità e inviare la scheda descrittiva a ENEA entro 90 giorni. Restano escluse le caldaie uniche a combustibili fossili; per redditi oltre € 75.000 possono applicarsi limiti di spesa.</p></section>
<?php elseif($key==='conto-termico'):?>
<section class="inc-section"><p>Il Conto Termico, disciplinato dal D.M. 16 febbraio 2016, incentiva la sostituzione completa di un impianto esistente con una pompa di calore equivalente e interventi di produzione termica da fonti rinnovabili.</p></section><section class="inc-section"><h2>Chi può accedere</h2><p>Amministrazioni pubbliche e soggetti privati, anche tramite ESCO. Per l’accesso diretto la domanda va presentata al GSE entro 60 giorni dalla conclusione dell’intervento.</p></section><section class="inc-section"><h2>Incentivo</h2><p>Può coprire fino al 65% della spesa ammissibile. Per importi fino a € 5.000 è normalmente erogato in un’unica soluzione; negli altri casi in rate annuali da 2 a 5 anni.</p></section><section class="inc-section"><h2>Requisiti essenziali</h2><ul><li>Edificio esistente già dotato di impianto.</li><li>Sostituzione, non semplice nuova installazione.</li><li>Pompa di calore rispondente ai requisiti di efficienza previsti dal GSE.</li><li>Documentazione tecnica e fotografica completa.</li></ul></section>
<?php else:?><section class="inc-section"><h2>Supporto alla pratica</h2><p>Il servizio aiuta a raccogliere i dati dell’impianto sostituito, stimare l’incentivo, predisporre i documenti e presentare la richiesta al GSE.</p></section><?php require __DIR__.'/incentives_easytool_form.php';?><?php endif;?></article><?php endif;?>
