<?php
$editorialSlug=(string)($page['slug']??'');
if($editorialSlug==='faq'){require __DIR__.'/faq.php';return;}
if($editorialSlug==='configurazione-wi-fi'){require __DIR__.'/wifi.php';return;}
if(str_starts_with($editorialSlug,'detrazioni-e-incentivi')){require __DIR__.'/incentives.php';return;}
?>
<style>
.section-label{color:var(--primary-deep);font-size:12px;font-weight:600;letter-spacing:.3em;text-transform:uppercase}.editorial-body{max-width:900px;margin-bottom:34px;padding:30px;border:1px solid var(--border);border-radius:26px;background:#fff;color:var(--muted-foreground);font-size:16px;line-height:1.75}.editorial-section{margin-top:34px}.editorial-section h2{font-size:28px}.editorial-panel{padding:26px;border:1px solid var(--border);border-radius:24px;background:#fff;color:var(--muted-foreground);line-height:1.7}.faq-list{display:grid;gap:13px}.faq-item{padding:0;border:1px solid var(--border);border-radius:20px;background:#fff;overflow:hidden}.faq-item summary{padding:20px 24px;cursor:pointer;color:var(--foreground);font-family:Sora;font-size:16px;font-weight:600;list-style:none}.faq-item summary::-webkit-details-marker{display:none}.faq-item summary:after{content:'+';float:right;color:var(--primary-deep);font-size:22px}.faq-item[open] summary:after{content:'−'}.faq-answer{padding:0 24px 22px;color:var(--muted-foreground);line-height:1.7}.editorial-docs{display:grid;gap:12px}
</style>
<section class="hero"><div class="wrap"><div class="crumbs"><a href="/idemaclima/">Home</a> / <?=e((string)$page['title'])?></div><?php if(!empty($page['eyebrow'])):?><span class="section-label"><?=e((string)$page['eyebrow'])?></span><?php endif;?><h1><?=e((string)$page['title'])?></h1><?php if(!empty($page['intro'])):?><p><?=e((string)$page['intro'])?></p><?php endif;?></div></section>
<section class="content"><div class="wrap"><?php if(!empty($page['body'])):?><div class="editorial-body"><?=nl2br(e((string)$page['body']))?></div><?php endif;?><?php foreach($sections as $section):?><section id="<?=e((string)($section['anchor_slug']??''))?>" class="editorial-section"><h2><?=e((string)$section['title'])?></h2><?php if(!empty($section['body'])):?><div class="editorial-panel"><?=nl2br(e((string)$section['body']))?></div><?php endif;?></section><?php endforeach;?><?php if($faqs):?><section class="editorial-section"><span class="section-label">Supporto</span><h2>Domande e risposte</h2><div class="faq-list"><?php foreach($faqs as $faq):?><details class="faq-item"><summary><?=e((string)$faq['question'])?></summary><div class="faq-answer"><?=nl2br(e((string)$faq['answer']))?></div></details><?php endforeach;?></div></section><?php endif;?><?php foreach($documentGroups as $group=>$documents):?><section class="editorial-section"><h2><?=e((string)$group)?></h2><div class="editorial-docs"><?php foreach($documents as $doc):?><div class="doc"><div><strong><?=e((string)($doc['label']?:$doc['title']))?></strong><br><small><?=e((string)$doc['document_type'])?></small></div><a class="btn" href="/idemaclima/documento/<?=(int)$doc['document_id']?>/download" target="_blank" rel="noopener">Scarica PDF ↗</a></div><?php endforeach;?></div></section><?php endforeach;?></div></section>