<?php
$systemType=static function(string $description):string{
    if(stripos($description,'Mini Chiller')!==false)return 'Mini Chiller';
    if(stripos($description,'Chiller')!==false)return 'Chiller';
    if(stripos($description,'Rooftop')!==false)return 'Rooftop';
    if(stripos($description,'Mini VRF')!==false && stripos($description,'+ VRF')===false)return 'Mini VRF';
    return 'VRF';
};
$counts=['Tutte'=>count($references),'VRF'=>0,'Mini VRF'=>0,'Chiller'=>0,'Mini Chiller'=>0,'Rooftop'=>0];
foreach($references as $item){$counts[$systemType((string)($item['short_description']??''))]++;}
?>
<style>
.references-hero{padding:58px 0 66px;background:var(--gradient-cool);border-bottom:1px solid var(--border)}.references-hero-copy{max-width:930px}.references-eyebrow{margin:0 0 12px;color:var(--primary-deep);font-size:12px;font-weight:700;letter-spacing:.3em;text-transform:uppercase}.references-hero h1{max-width:900px;margin:0;font-size:clamp(42px,6vw,68px);font-weight:800;line-height:1.05}.references-hero p:last-child{max-width:860px;margin:20px 0 0;color:var(--muted-foreground);font-size:18px;line-height:1.65}
.references-stats{padding:48px 0 42px}.references-stats-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px;max-width:900px;margin:auto}.references-stat{padding:25px 16px;text-align:center;border:1px solid var(--border);border-radius:18px;background:#fff}.references-stat strong{display:block;margin-bottom:5px;color:var(--primary-deep);font-family:Sora,system-ui,sans-serif;font-size:clamp(30px,3vw,42px);font-weight:800;line-height:1;letter-spacing:-.04em;font-variant-numeric:tabular-nums;font-feature-settings:"tnum" 1}.references-stat span{color:var(--muted-foreground);font-size:12px;letter-spacing:.1em;text-transform:uppercase}
.reference-radio{position:absolute;inline-size:1px;block-size:1px;opacity:0;pointer-events:none}.references-filter{padding:0 0 34px}.references-filter-row{display:flex;gap:18px;align-items:center}.references-filter-title{display:flex;flex:none;gap:8px;align-items:center;color:var(--muted-foreground);font-size:12px;font-weight:700;letter-spacing:.18em;text-transform:uppercase}.references-filter-title svg{width:17px;height:17px;fill:none;stroke:currentColor;stroke-width:2}.references-filter-buttons{display:flex;flex-wrap:wrap;gap:8px}.reference-filter{padding:9px 15px;border:1px solid var(--border);border-radius:999px;background:#fff;color:rgba(21,39,31,.75);font:inherit;font-size:14px;cursor:pointer;transition:.25s}.reference-filter:hover{border-color:rgba(139,220,35,.6);color:var(--foreground)}.reference-filter small{margin-left:7px;font-size:11px;opacity:.72}
#ref-all:checked~.references-filter label[for="ref-all"],#ref-vrf:checked~.references-filter label[for="ref-vrf"],#ref-mini-vrf:checked~.references-filter label[for="ref-mini-vrf"],#ref-chiller:checked~.references-filter label[for="ref-chiller"],#ref-mini-chiller:checked~.references-filter label[for="ref-mini-chiller"],#ref-rooftop:checked~.references-filter label[for="ref-rooftop"]{border-color:var(--primary);background:var(--primary);color:var(--foreground);box-shadow:var(--shadow-soft)}
#ref-vrf:checked~.references-section .reference-card:not([data-system="VRF"]),#ref-mini-vrf:checked~.references-section .reference-card:not([data-system="Mini VRF"]),#ref-chiller:checked~.references-section .reference-card:not([data-system="Chiller"]),#ref-mini-chiller:checked~.references-section .reference-card:not([data-system="Mini Chiller"]),#ref-rooftop:checked~.references-section .reference-card:not([data-system="Rooftop"]){display:none}
.references-section{padding:0 0 82px}.reference-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:24px}.reference-card{display:flex;min-width:0;flex-direction:column;overflow:hidden;border:1px solid var(--border);border-radius:22px;background:#fff;transition:.35s var(--ease)}.reference-card:hover{transform:translateY(-4px);box-shadow:var(--shadow-soft)}.reference-card[hidden]{display:none}.reference-media{position:relative;aspect-ratio:4/3;overflow:hidden;background:var(--muted)}.reference-media img{display:block;width:100%;height:100%;object-fit:cover;transition:transform .5s var(--ease)}.reference-card:hover .reference-media img{transform:scale(1.05)}.reference-tag{position:absolute;top:13px;left:13px;padding:7px 11px;border-radius:999px;background:rgba(255,255,255,.9);color:var(--primary-deep);font-size:11px;font-weight:700;letter-spacing:.09em;text-transform:uppercase;backdrop-filter:blur(8px)}.reference-info{display:flex;flex:1;flex-direction:column;padding:21px}.reference-location{display:flex;gap:7px;align-items:flex-start;margin-bottom:9px;color:var(--primary-deep);font-size:11px;font-weight:700;letter-spacing:.14em;text-transform:uppercase}.reference-location svg{flex:none;width:14px;height:14px;fill:none;stroke:currentColor;stroke-width:2}.reference-info h2{margin:0 0 17px;font-size:19px;line-height:1.3}.reference-system{display:flex;gap:8px;align-items:flex-start;margin-top:auto;padding-top:14px;border-top:1px solid var(--border);color:var(--muted-foreground);font-size:14px;line-height:1.45}.reference-system svg{flex:none;width:16px;height:16px;fill:none;stroke:var(--primary-deep);stroke-width:2}.references-empty{display:none;padding:45px;text-align:center;color:var(--muted-foreground)}
.references-cta{padding:0 0 88px}.references-cta-box{padding:50px;border-radius:28px;background:var(--gradient-dark);color:#fff;text-align:center}.references-cta-box h2{margin:0 0 14px;color:#fff;font-size:clamp(30px,4vw,44px)}.references-cta-box p{max-width:650px;margin:0 auto 26px;color:rgba(255,255,255,.76);line-height:1.7}
@media(max-width:1050px){.reference-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:760px){.references-stats-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.references-filter-row{align-items:flex-start;flex-direction:column}.references-section{padding-bottom:60px}}@media(max-width:580px){.references-hero{padding:44px 0 48px}.references-hero p:last-child{font-size:16px}.references-stats{padding:38px 0}.references-stat{padding:21px 10px}.references-stat span{font-size:10px}.reference-grid{grid-template-columns:1fr}.references-cta-box{padding:38px 22px}}
</style>
<section class="references-hero"><div class="wrap"><div class="references-hero-copy"><p class="references-eyebrow">Referenze</p><h1>I nostri prodotti in Italia e nel Mondo.</h1><p>Una selezione di installazioni IDEMA CLIMA® realizzate in ambito commerciale, industriale, ricettivo e sanitario: sistemi VRF, Mini VRF, Chiller, Mini Chiller e Rooftop al servizio dei nostri clienti.</p></div></div></section>
<section class="references-stats"><div class="wrap"><div class="references-stats-grid"><div class="references-stat"><strong><?=count($references)?>+</strong><span>Progetti realizzati</span></div><div class="references-stat"><strong>5</strong><span>Tipologie di sistema</span></div><div class="references-stat"><strong>20+</strong><span>Città servite</span></div><div class="references-stat"><strong>2</strong><span>Paesi</span></div></div></div></section>
<?php $filterIds=['Tutte'=>'ref-all','VRF'=>'ref-vrf','Mini VRF'=>'ref-mini-vrf','Chiller'=>'ref-chiller','Mini Chiller'=>'ref-mini-chiller','Rooftop'=>'ref-rooftop']; foreach($filterIds as $filter=>$id): ?><input class="reference-radio" type="radio" name="reference-filter" id="<?=$id?>"<?=$filter==='Tutte'?' checked':''?>><?php endforeach;?>
<section class="references-filter"><div class="wrap"><div class="references-filter-row"><div class="references-filter-title"><svg viewBox="0 0 24 24"><path d="M4 5h16M7 12h10M10 19h4"/></svg>Filtra per sistema</div><div class="references-filter-buttons"><?php foreach($counts as $filter=>$count): ?><label class="reference-filter" for="<?=$filterIds[$filter]?>"><?=e($filter)?><small><?=$count?></small></label><?php endforeach;?></div></div></div></section>
<section class="references-section"><div class="wrap"><div class="reference-grid"><?php foreach($references as $reference): $description=(string)($reference['short_description']??'');$type=$systemType($description); ?><article class="reference-card" data-system="<?=e($type)?>"><div class="reference-media"><?php if(!empty($reference['cover_image'])): ?><img src="<?=e($reference['cover_image'])?>" alt="<?=e($reference['title'].' — '.($reference['location']??''))?>" loading="lazy"><?php endif; ?><span class="reference-tag"><?=e($type)?></span></div><div class="reference-info"><div class="reference-location"><svg viewBox="0 0 24 24"><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg><span><?=e((string)($reference['location']??''))?></span></div><h2><?=e($reference['title'])?></h2><div class="reference-system"><svg viewBox="0 0 24 24"><path d="m13 2-9 12h7l-1 8 10-13h-7z"/></svg><span><?=e($description)?></span></div></div></article><?php endforeach;?></div><p class="references-empty">Nessuna referenza per questo filtro.</p></div></section>
<section class="references-cta"><div class="wrap"><div class="references-cta-box"><h2>Hai un progetto da climatizzare?</h2><p>Il nostro ufficio tecnico è a disposizione per studiare la soluzione più efficiente per la tua attività: residenziale, commerciale o industriale.</p><a class="btn" href="/idemaclima/contatti">Contattaci</a></div></div></section>