<?php
$categoryMeta = [
 'linea-residenziale-r32'=>['Comfort domestico','Climatizzatori Mono Split, Multi Split e Multi PRO per la casa, con gas refrigerante R32 a basso impatto ambientale.','home',['Mono Split','Multi Split','Multi Pro','Accessori']],
 'linea-commerciale-r32'=>['Uffici & negozi','Soluzioni dedicate a uffici, negozi, ristoranti e ambienti professionali. Cassette, canalizzati, console e soffitto/pavimento.','building',['Unità esterne','Unità interne','Accessori']],
 'linea-vrf'=>['Sistemi industriali','Atomix R32, Mini VRF Monoventola, VRF Side Discharge e VRF Top Discharge per grandi edifici a flusso variabile.','factory',['Atomix R32','Mini VRF Monoventola','Unità interne','VRF Side Discharge','VRF Top Discharge','Accessori']],
 'linea-idronica'=>['Pompe di calore','Pompe di calore monoblocco, sistemi All-in-One e scaldacqua per riscaldamento e produzione di acqua calda sanitaria.','droplets',['PdC Monoblocco','PdC All-in-One','Scaldacqua']],
 'altri-prodotti'=>['Aria pulita',"Recuperatori di calore con scambio entalpico, purificatori d'aria HEPA e barriere a lama d'aria.",'wind',['Recuperatori di calore','Purificatori d’aria','Barriere a lama d’aria']],
];
$categoryOrder=['linea-residenziale-r32'=>0,'linea-commerciale-r32'=>1,'linea-vrf'=>2,'linea-idronica'=>3,'altri-prodotti'=>4];
usort($categories,static fn($a,$b)=>($categoryOrder[$a['slug']]??99)<=>($categoryOrder[$b['slug']]??99));
$totalProducts=array_sum(array_map(static fn($c)=>(int)$c['product_count'],$categories));
$totalDocuments=array_sum(array_map(static fn($c)=>(int)$c['document_count'],$categories));
$icon=static function(string $type):string{
 $paths=[
  'home'=>'<path d="m3 10 9-7 9 7"/><path d="M5 9v11h14V9"/><path d="M9 20v-6h6v6"/>',
  'building'=>'<path d="M6 22V4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v18Z"/><path d="M6 12H4a2 2 0 0 0-2 2v8h20v-8a2 2 0 0 0-2-2h-2"/><path d="M10 6h4M10 10h4M10 14h4M10 18h4"/>',
  'factory'=>'<path d="M2 20h20M4 20V10l6 3V8l6 3V4h4v16"/><path d="M8 17h1M12 17h1M16 17h1"/>',
  'droplets'=>'<path d="M12 2.7 6.6 8.9A7.8 7.8 0 1 0 17.4 8.9Z"/><path d="M8.5 15.2A3.8 3.8 0 0 0 12 18"/>',
  'wind'=>'<path d="M3 8h11a3 3 0 1 0-3-3"/><path d="M3 12h15a3 3 0 1 1-3 3"/><path d="M3 16h7"/>',
 ];return $paths[$type]??$paths['wind'];
};
?>
<style>
.technical-hero{padding:58px 0 66px;background:var(--gradient-cool);border-bottom:1px solid var(--border)}.technical-hero-copy{max-width:850px}.technical-eyebrow{margin:0 0 10px;color:var(--primary-deep);font-size:12px;font-weight:700;letter-spacing:.2em;text-transform:uppercase}.technical-hero h1{margin:0;font-size:clamp(42px,6vw,68px);font-weight:800;line-height:1.04}.technical-hero-description{margin:20px 0 0;color:var(--muted-foreground);font-size:18px;line-height:1.65}
.technical-content{padding:40px 0 88px}.technical-search{position:relative;max-width:680px;margin:0 auto 48px}.technical-search svg{position:absolute;z-index:1;left:18px;top:50%;width:18px;height:18px;transform:translateY(-50%);fill:none;stroke:var(--muted-foreground);stroke-width:2}.technical-search input{width:100%;height:50px;margin:0;padding:0 20px 0 50px;border-radius:999px}.technical-search button{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap}
.technical-stats{display:flex;justify-content:center;align-items:center;gap:34px;margin:0 auto 48px}.technical-stat{text-align:center}.technical-stat strong{display:block;color:var(--primary-deep);font-family:Sora,system-ui,sans-serif;font-size:34px;font-weight:800;line-height:1;letter-spacing:-.04em;font-variant-numeric:tabular-nums;font-feature-settings:"tnum" 1}.technical-stat small{display:block;margin-top:7px;text-transform:uppercase;letter-spacing:.13em;color:var(--muted-foreground)}.technical-stat-line{width:1px;height:44px;background:var(--border)}
.technical-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:24px}.technical-card{display:flex;flex-direction:column;min-height:390px;padding:26px;border:1px solid var(--border);border-radius:26px;background:#fff;transition:.4s var(--ease)}.technical-card:hover{transform:translateY(-4px);border-color:var(--primary);box-shadow:var(--shadow-elegant)}.technical-card-head{display:flex;gap:16px;align-items:flex-start}.technical-icon{width:58px;height:58px;display:grid;place-items:center;flex:none;border-radius:18px;background:rgba(145,208,37,.12);color:var(--primary-deep);transition:.35s}.technical-icon svg{width:29px;height:29px;fill:none;stroke:currentColor;stroke-width:1.5;stroke-linecap:round;stroke-linejoin:round}.technical-card:hover .technical-icon{background:var(--primary);color:var(--primary-ink)}.technical-card small{color:var(--primary-deep);font-weight:700;text-transform:uppercase;letter-spacing:.12em}.technical-card h2{margin:3px 0;font-size:21px}.technical-card p{color:var(--muted-foreground);font-size:14px;line-height:1.65}.technical-sub-list{display:grid;gap:7px;margin:10px 0 22px}.technical-sub-list span{font-size:14px}.technical-sub-list span:before{content:"";display:inline-block;width:6px;height:6px;margin-right:9px;border-radius:50%;background:var(--primary)}.technical-card-foot{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-top:auto;padding-top:16px;border-top:1px solid var(--border);font-size:13px}.technical-card-foot b{color:var(--primary-deep)}.technical-note{text-align:center;margin-top:42px;color:var(--muted-foreground);font-size:13px}
@media(max-width:950px){.technical-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:640px){.technical-hero{padding:44px 0 48px}.technical-grid{grid-template-columns:1fr}.technical-stats{gap:18px}.technical-stat strong{font-size:28px}.technical-stat small{font-size:10px}.technical-card{min-height:0}}
</style>
<section class="technical-hero"><div class="wrap"><div class="technical-hero-copy"><p class="technical-eyebrow">Documentazione</p><h1>Schede tecniche</h1><p class="technical-hero-description">Tutta la documentazione tecnica ufficiale Idemaclima, organizzata per linea di prodotto come nel catalogo originale.</p></div></div></section>
<section class="technical-content"><div class="wrap">
<form class="technical-search" action="/idemaclima/schede-tecniche/ricerca" method="get"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="8"></circle><path d="m21 21-4.3-4.3"></path></svg><label for="technical-search" class="hp">Cerca prodotto, modello o documento</label><input id="technical-search" type="search" name="q" placeholder="Cerca prodotto, modello o documento..." autocomplete="off"><button type="submit">Cerca</button></form>
<div class="technical-stats"><div class="technical-stat"><strong><?=count($categories)?></strong><small>Linee</small></div><i class="technical-stat-line"></i><div class="technical-stat"><strong><?=$totalProducts?></strong><small>Prodotti</small></div><i class="technical-stat-line"></i><div class="technical-stat"><strong><?=$totalDocuments?></strong><small>Schede PDF</small></div></div>
<div class="technical-grid"><?php foreach($categories as $category):$m=$categoryMeta[$category['slug']]??['Prodotti IDEMA','Documentazione tecnica ufficiale.','wind',[]];?><a class="technical-card" href="/idemaclima/schede-tecniche/<?=e($category['slug'])?>"><div class="technical-card-head"><span class="technical-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><?=$icon($m[2])?></svg></span><div><small><?=e($m[0])?></small><h2><?=e($category['name'])?></h2></div></div><p><?=e($m[1])?></p><div class="technical-sub-list"><?php foreach($m[3] as $sub):?><span><?=e($sub)?></span><?php endforeach;?></div><div class="technical-card-foot"><span><?= (int)$category['product_count']?> prodotti · <?= (int)$category['document_count']?> PDF</span><b>Apri →</b></div></a><?php endforeach;?></div>
<p class="technical-note">Le schede tecniche in PDF sono ospitate sul sito ufficiale idemaclima.it.</p>
</div></section>
