<?php
/** @var string $title */
function e(string $value): string { return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }
?><!doctype html>
<html lang="it">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title><?= e($title ?? 'IDEMA Clima') ?></title>
<meta name="robots" content="index,follow">
<style>
:root{--ink:#111827;--muted:#6b7280;--line:#e5e7eb;--soft:#f7f7f5;--brand:#f4c542;--dark:#171717}
*{box-sizing:border-box}body{margin:0;font-family:Arial,Helvetica,sans-serif;color:var(--ink);background:#fff;line-height:1.5}a{color:inherit;text-decoration:none}.wrap{width:min(1180px,calc(100% - 32px));margin:auto}.top{background:var(--dark);color:#fff}.top .wrap{min-height:72px;display:flex;align-items:center;justify-content:space-between;gap:24px}.brand{font-weight:800;letter-spacing:.08em}.nav{display:flex;gap:16px;font-size:14px;flex-wrap:wrap}.hero{padding:64px 0 36px;background:var(--soft);border-bottom:1px solid var(--line)}.hero h1{font-size:clamp(34px,5vw,64px);line-height:1;margin:0 0 16px}.hero p{max-width:760px;color:var(--muted);font-size:18px}.crumbs{font-size:13px;color:var(--muted);margin-bottom:20px}.content{padding:40px 0 72px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.card,.panel{border:1px solid var(--line);border-radius:14px;padding:22px;background:#fff}.card{transition:.2s}.card:hover{transform:translateY(-2px);box-shadow:0 10px 30px rgba(0,0,0,.06)}.card h2,.card h3{margin:0 0 8px}.meta{color:var(--muted);font-size:14px}.status{display:inline-block;padding:5px 9px;border-radius:999px;font-size:12px;font-weight:700;background:#eee}.status.active{background:#e9f7ef}.status.unavailable,.status.discontinued{background:#f3f4f6;color:#6b7280}.product-head{display:grid;grid-template-columns:minmax(0,280px) 1fr;gap:34px;align-items:start}.product-img{width:100%;aspect-ratio:1/1;object-fit:contain;border:1px solid var(--line);border-radius:16px;background:#fff}.doc-group{margin-top:34px}.doc-list{display:grid;gap:10px}.doc{display:flex;align-items:center;justify-content:space-between;gap:20px;border:1px solid var(--line);border-radius:10px;padding:14px 16px}.doc small{color:var(--muted)}.btn{display:inline-flex;align-items:center;justify-content:center;background:var(--brand);padding:10px 14px;border:0;border-radius:8px;font-weight:700;cursor:pointer}.models{display:flex;flex-wrap:wrap;gap:8px;margin-top:16px}.model{padding:7px 10px;border:1px solid var(--line);border-radius:8px;font-size:13px}.footer{border-top:1px solid var(--line);padding:24px 0;color:var(--muted);font-size:13px}input,select,textarea{width:100%;box-sizing:border-box;padding:10px 12px;border:1px solid #cad4df;border-radius:8px;margin-top:5px;background:#fff;font:inherit}.formgrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.formgrid .full{grid-column:1/-1}.check{display:flex;align-items:center;gap:8px}.check input{width:auto;margin:0}.error{background:#fee2e2;color:#991b1b;padding:10px;border-radius:8px;margin-bottom:12px}label small{display:block;color:var(--muted);margin-top:5px}@media(max-width:800px){.grid,.formgrid{grid-template-columns:1fr}.product-head{grid-template-columns:1fr}.product-img{max-width:280px}.nav{display:none}.hero{padding-top:42px}}
</style>
</head>
<body>
<header class="top"><div class="wrap"><a class="brand" href="/">IDEMA CLIMA</a><nav class="nav"><a href="/schede-tecniche">Schede tecniche</a><a href="/cataloghi">Cataloghi</a><a href="/garanzia">Garanzia</a><a href="/campus">Campus</a><a href="/galleria">Galleria</a><a href="/referenze">Referenze</a></nav></div></header>
