<style>
:root{--font-body:Inter,system-ui,-apple-system,"Segoe UI",sans-serif;--font-display:Sora,system-ui,-apple-system,"Segoe UI",sans-serif}html{font-synthesis:none}body{font-family:var(--font-body);font-weight:400;text-rendering:optimizeLegibility;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}button,input,select,textarea{font-family:var(--font-body);font-weight:400}h1,h2,h3,h4,.num,.family-no,.references-stat strong,.technical-stat strong,.stat strong,.year strong,.pillar-num,.unit-top>span,.warranty-step b{font-family:var(--font-display);font-synthesis:none}h1,h2,h3,h4{font-weight:700}.hero h1,.technical-hero h1,.ts-hero h1,.catalog-hero h1,.gallery-hero h1,.album-hero h1,.references-hero h1,.project-hero h1,.support-hero h1,.inc-hero h1{font-family:var(--font-display);font-weight:800;letter-spacing:-.02em}.technical-hero-description,.ts-subtitle,.catalog-hero-description,.gallery-hero p:last-child,.album-hero-description,.references-hero p:last-child,.project-hero p,.support-hero p,.inc-hero p{font-family:var(--font-body);font-weight:400}.eyebrow,.section-label,.technical-eyebrow,.ts-eyebrow,.catalog-eyebrow,.catalog-section-label,.gallery-eyebrow,.gallery-section-label,.album-eyebrow,.references-eyebrow,.project-label,.support-eyebrow,.support-section-label,.inc-eyebrow,.inc-label{font-family:var(--font-body);font-weight:600}.num,.family-no,.references-stat strong,.technical-stat strong,.stat strong,.year strong,.pillar-num,.unit-top>span,.inc-top{font-variant-numeric:tabular-nums;font-feature-settings:"tnum" 1,"ss01" 1,"cv02" 1}.nav a,.mobile-nav a{font-weight:500}.card h2,.card h3,.family-card h2,.product-info h2,.inc-card h2,.support-main-card h2,.resource-card h3{font-family:var(--font-display);font-weight:700}.doc strong{font-weight:500;color:var(--foreground)}.product-page-link,.contact-btn,.btn,.tab-button,.product-open{font-weight:600}.product-meta>span:first-child,.documents-title>span,.doc-count{font-weight:400}.manifesto strong{font-weight:800}

.hero .wrap,.technical-hero .wrap,.ts-hero .wrap,.catalog-hero .wrap,.gallery-hero .wrap,.album-hero .wrap,.references-hero .wrap,.project-hero .wrap,.support-hero .wrap,.inc-hero .wrap{width:min(768px,calc(100% - 64px));margin-left:auto;margin-right:auto}.hero h1,.hero p,.technical-hero h1,.technical-hero-description,.ts-hero h1,.ts-subtitle,.catalog-hero h1,.catalog-hero-description,.gallery-hero h1,.gallery-hero p:last-child,.album-hero h1,.album-hero-description,.references-hero h1,.references-hero p:last-child,.project-hero h1,.project-hero p,.support-hero h1,.support-hero p,.inc-hero h1,.inc-hero p{text-align:left;margin-left:0;margin-right:0}@media(max-width:800px){.hero .wrap,.technical-hero .wrap,.ts-hero .wrap,.catalog-hero .wrap,.gallery-hero .wrap,.album-hero .wrap,.references-hero .wrap,.project-hero .wrap,.support-hero .wrap,.inc-hero .wrap{width:min(768px,calc(100% - 32px))}}
img,svg,video,iframe{max-width:100%}h1,h2,h3,h4{text-wrap:balance;overflow-wrap:normal}p,li{overflow-wrap:break-word}p{text-wrap:pretty}button,.btn,.contact-btn,.product-page-link{min-height:44px}@media(max-width:800px){input,select,textarea{font-size:16px}.footer-links{flex-wrap:wrap;gap:12px 20px}}@media(max-width:480px){.wrap,.hero .wrap,.technical-hero .wrap,.ts-hero .wrap,.catalog-hero .wrap,.gallery-hero .wrap,.album-hero .wrap,.references-hero .wrap,.project-hero .wrap,.support-hero .wrap,.inc-hero .wrap{width:calc(100% - 24px)}.hero h1,.technical-hero h1,.ts-hero h1,.catalog-hero h1,.gallery-hero h1,.album-hero h1,.references-hero h1,.project-hero h1,.support-hero h1,.inc-hero h1{font-size:clamp(32px,10vw,44px);line-height:1.08}.card,.panel{border-radius:18px}.footer-legal{gap:18px}}
/* Shared visual language for internal pages. The video home hero remains intentionally distinct. */
body :is(.hero,.technical-hero,.ts-hero,.catalog-hero,.gallery-hero,.album-hero,.references-hero,.project-hero,.support-hero,.inc-hero,.faq-hero,.wifi-hero){padding:60px 0 68px;border-bottom:1px solid var(--border)}
body :is(.hero,.technical-hero,.ts-hero,.catalog-hero,.gallery-hero,.album-hero,.references-hero,.project-hero,.support-hero,.inc-hero,.faq-hero,.wifi-hero) h1{margin:10px 0 18px;font-size:clamp(42px,6vw,68px);line-height:1.04;letter-spacing:-.025em}
body :is(.technical-hero-description,.ts-subtitle,.catalog-hero-description,.gallery-hero p:last-child,.album-hero-description,.references-hero p:last-child,.project-hero p:last-child,.support-hero p:last-child,.inc-hero p:last-child,.faq-hero p:last-child,.wifi-hero p:last-child,.hero>.wrap>p:last-child){max-width:850px;margin:0;color:var(--muted-foreground);font-size:18px;line-height:1.68}
body :is(.section-label,.technical-eyebrow,.ts-eyebrow,.catalog-eyebrow,.catalog-section-label,.gallery-eyebrow,.gallery-section-label,.album-eyebrow,.references-eyebrow,.project-label,.support-eyebrow,.support-section-label,.inc-eyebrow,.inc-label,.faq-eyebrow,.wifi-eyebrow){font-family:var(--font-body);font-size:12px;font-weight:600;line-height:1.4;letter-spacing:.22em;text-transform:uppercase}
body :is(.event-card,.reference-card,.catalog-card,.support-main-card,.resource-card,.warranty-series-card,.campus-path){border-radius:22px}
body :is(.section-head h2,.gallery-heading h2,.support-section-head h2,.inc-book h2){line-height:1.1;letter-spacing:-.02em}
body :is(.event-info p,.reference-system,.catalog-group-head p,.support-main-card p,.resource-card p,.inc-card p,.campus-path p){line-height:1.65}
body :is(.contact-form,.warranty-form,.easy-form,.contact-info){border-radius:22px}
body :is(.contact-form,.warranty-form,.easy-form){padding:30px}
body :is(.contact-form,.warranty-form,.easy-form) :is(input,select,textarea){min-height:44px;border-radius:12px}
body :is(.contact-form,.warranty-form,.easy-form) textarea{min-height:132px;line-height:1.55}
body :is(.contact-form,.warranty-form,.easy-form) label{line-height:1.45}
@media(max-width:800px){body :is(.hero,.technical-hero,.ts-hero,.catalog-hero,.gallery-hero,.album-hero,.references-hero,.project-hero,.support-hero,.inc-hero,.faq-hero,.wifi-hero){padding:44px 0 48px}body :is(.technical-hero-description,.ts-subtitle,.catalog-hero-description,.gallery-hero p:last-child,.album-hero-description,.references-hero p:last-child,.project-hero p:last-child,.support-hero p:last-child,.inc-hero p:last-child,.faq-hero p:last-child,.wifi-hero p:last-child,.hero>.wrap>p:last-child){font-size:16px;line-height:1.62}}
@media(max-width:620px){body :is(.contact-form,.warranty-form,.easy-form){padding:22px}}
@media(max-width:620px){
body :is(.hero-actions,.warranty-doc-links){align-items:stretch;flex-direction:column}
body :is(.hero-actions,.warranty-doc-links)>:is(a,button){width:100%;text-align:center}
body .doc{align-items:flex-start;gap:12px}
body .doc>span:first-child{min-width:0}
body .doc-open{flex:0 0 auto;white-space:nowrap}
body :is(.section-label,.technical-eyebrow,.ts-eyebrow,.catalog-eyebrow,.catalog-section-label,.gallery-eyebrow,.gallery-section-label,.album-eyebrow,.references-eyebrow,.project-label,.support-eyebrow,.support-section-label,.inc-eyebrow,.inc-label,.faq-eyebrow,.wifi-eyebrow){letter-spacing:.16em}
body :is(.privacy-check,.easy-check,.check){line-height:1.55}
body :is(.references-cta-box,.event-block,.registration){padding-left:22px;padding-right:22px}
}
body .wifi-accordion summary{font-family:var(--font-display);font-size:17px;font-weight:600}\nbody :is(.wifi-nav strong,.wifi-os h3,.wifi-foundation-card h3,.wifi-step h3){font-family:var(--font-display);font-weight:700}\n</style>
